The procedure support the following config parameters:

.Config parameters
[opts=header, cols="1,1,1,3"]
|===
| name | type | default | description
| batchSize | Long | 10000 | run the specified number of operation statements in a single tx - params: {_count, _batch}
| parallel | boolean | false | run operation statements in parallel (note that statements might deadlock if conflicting)
| retries | Long | 0 | if the operation statement fails with an error, sleep 100ms and retry until retries-count is reached - param \{_retry}
| batchMode | String | "BATCH" a| how data-driven statements should be processed by operation statement. Valid values are:

* "BATCH" - execute operation statement once per batchSize. Operation statement is prefixed with the following, which extracts each field returned in the data-driven statement from the `$_batch` parameter:
[source,cypher]
----
UNWIND $_batch AS _batch
WITH _batch.field1 AS field1, _batch.field2 AS field2
----
* "SINGLE" - execute operation statement one at a time
* "BATCH_SINGLE" - execute operation statement once per batchSize, but leaves unpacking of batch to the operation statement.
The operation query can access the batched values via the `$_batch` parameter.

| params | Map | {} | externally pass in map of params
| concurrency | Long | 50 | number of concurrent tasks are generated when using `parallel:true`
| failedParams | Long |  -1 | if set to a non-negative value, each failed batch up to `failedParams` parameter sets are returned in `yield failedParams`.
| planner | Enum[DEFAULT, COST, IDP, DP] |  DEFAULT | Any planner other than `DEFAULT` will be prepended to the second statement as `cypher planner=[VALUE_OF_CONFIG]` (or insert `planner=[VALUE_OF_CONFIG]` with any existing query options).
    This planner value (except for `DEFAULT`) has higher precedence than the planner defined in the query (if any).
|===

[NOTE]
====
In APOC versions 4.0.0.11 and earlier, the `iterateList` config key was used to control the batching of values returned by the data-driven statement.
This was replaced by `batchMode` in version 4.0.0.12.
These config keys are treated as follows:

* If `batchMode` is provided, its value takes precedence over `iterateList`
* If `batchMode` is not provided and `iterateList` is provided, the value of `iterateList` will be translated as described in the table below.
* If neither `batchMode` nor `iterateList` are provided, `batchMode` defaults to `BATCH`, which is the same as `iterateList:true`
====

.Deprecated Config
[options=header, cols="1,1,3"]
|===
| param | default | description
| iterateList | true a| execute operation statements once per batchSize (whole batchSize list is passed in as parameter \{_batch})

* A value of true is equivalent to `batchMode: "BATCH"`
* A value of false is equivalent to `batchMode: "SINGLE"`
|===