////
This file is generated by DocsTest, so don't change it!
////

= apoc.custom
:description: This section contains reference documentation for the apoc.custom procedures.

[.procedures, opts=header, cols='5a,1a']
|===
| Qualified Name | Type
|xref::overview/apoc.custom/apoc.custom.dropAll.adoc[apoc.custom.dropAll icon:book[]]

apoc.custom.dropAll(databaseName) - Eventually drops all previously added custom procedures/functions and returns info
|label:procedure[]
|xref::overview/apoc.custom/apoc.custom.dropFunction.adoc[apoc.custom.dropFunction icon:book[]]

apoc.custom.dropFunction(name, databaseName) - Eventually drops the targeted custom function
|label:procedure[]
|xref::overview/apoc.custom/apoc.custom.dropProcedure.adoc[apoc.custom.dropProcedure icon:book[]]

apoc.custom.dropProcedure(name, databaseName) - Eventually drops the targeted custom procedure
|label:procedure[]
|xref::overview/apoc.custom/apoc.custom.installFunction.adoc[apoc.custom.installFunction icon:book[]]

apoc.custom.installFunction(signature, statement, databaseName, forceSingle, description) - Eventually registers a custom cypher function
|label:procedure[]
|xref::overview/apoc.custom/apoc.custom.installProcedure.adoc[apoc.custom.installProcedure icon:book[]]

apoc.custom.installProcedure(signature, statement, databaseName, mode, description) - Eventually registers a custom cypher procedure
|label:procedure[]
|xref::overview/apoc.custom/apoc.custom.list.adoc[apoc.custom.list icon:book[]]

apoc.custom.list() - provide a list of custom procedures/function registered
|label:procedure[]
|xref::overview/apoc.custom/apoc.custom.show.adoc[apoc.custom.show icon:book[]]

apoc.custom.show(databaseName) - Provides a list of custom procedures/function registered
|label:procedure[]
|===

