== Node Neighbors

You can find the distinct connected nodes "n" levels or away quickly with these following procedures.

You can use '>' or '<' for all outgoing or incoming relationships, or specify the types you are interested in.

[cols="1m,5"]
|===
| apoc.neighbors.tohop(node, rel-direction-pattern, distance) | returns distinct nodes of the given relationships in the pattern up to a certain distance
| apoc.neighbors.tohop.count(node, rel-direction-pattern, distance) | returns the count of distinct nodes of the given relationships in the pattern up to a certain distance
| apoc.neighbors.byhop(node, rel-direction-pattern, distance) | returns distinct nodes of the given relationships in the pattern grouped by distance
| apoc.neighbors.byhop.count(node, rel-direction-pattern, distance) | returns the count distinct nodes of the given relationships in the pattern grouped by distance
| apoc.neighbors.athop(node, rel-direction-pattern, distance) | returns distinct nodes of the given relationships in the pattern at a certain distance
| apoc.neighbors.athop.count(node, rel-direction-pattern, distance) | returns the count of distinct nodes of the given relationships in the pattern at a certain distance
|===




=== Example

.Graph Setup
[source,cypher]
----
CREATE (a:First), (b:Neighbor), (c:Neighbor), (d:Neighbor),
(a)-[:KNOWS]->(b), (b)-[:KNOWS]->(a),
(b)-[:KNOWS]->(c), (c)-[:KNOWS]->(d)
----

[source,cypher]
----
MATCH (n:First) WITH n
CALL apoc.neighbors.tohop(n,'KNOWS>', 3) YIELD node AS neighbor
RETURN neighbor
----

[source,cypher]
----
MATCH (n:First) WITH n
CALL apoc.neighbors.tohop.count(n,'KNOWS>', 3) YIELD value AS number
RETURN number
----

[source,cypher]
----
MATCH (n:First) WITH n
CALL apoc.neighbors.byhop(n,'KNOWS>', 3) YIELD nodes AS neighbors
RETURN neighbors
----

[source,cypher]
----
MATCH (n:First) WITH n
CALL apoc.neighbors.byhop.count(n,'KNOWS>', 3) YIELD value AS numbers
RETURN numbers
----

[source,cypher]
----
MATCH (n:First) WITH n
CALL apoc.neighbors.athop(n,'KNOWS>', 3) YIELD nodes AS neighbors
RETURN neighbors
----

[source,cypher]
----
MATCH (n:First) WITH n
CALL apoc.neighbors.athop.count(n,'KNOWS>', 3) YIELD value AS numbers
RETURN numbers
----