[[expand-subgraph-nodes]]
== Expand to nodes in a subgraph

[abstract]
--
This section describes a procedure that expands a subgraph from a set of start nodes, and returns all nodes within the subgraph.
--

This procedure expands to subgraph nodes reachable from the start node following relationships to max-level adhering to the label filters.
It allows fine grained control over the traversals that expand the subgraph.

This section includes:

* <<expand-subgraph-nodes-overview>>
* <<expand-subgraph-nodes-config>>
* <<expand-subgraph-nodes-examples>>

[[expand-subgraph-nodes-overview]]
=== Procedure Overview

The procedure is described below:

[separator=¦,opts=header,cols="1,1m,1m,5"]
|===
include::../../../build/generated-documentation/apoc.path.subgraphNodes.csv[]
|===

[[expand-subgraph-nodes-config]]
=== Configuration parameters

include::config-params.adoc[]


[[expand-subgraph-nodes-relationship-filters]]
==== Relationship Filters

The syntax for relationship filters is described below:

include::relationship-filter.adoc[]

[[expand-subgraph-nodes-label-filters]]
==== Label Filters

The syntax for label filters is described below:

include::label-filter.adoc[]

*Label filter operator precedence and behavior*

include::label-filter-precedence.adoc[]

[[expand-subgraph-nodes-examples]]
=== Examples


Expand to all nodes of a connected subgraph:

[source,cypher]
----
MATCH (user:User) WHERE user.id = 460
CALL apoc.path.subgraphNodes(user, {}) YIELD node
RETURN node;
----

Expand to all nodes reachable by :FRIEND relationships:

[source,cypher]
----
MATCH (user:User) WHERE user.id = 460
CALL apoc.path.subgraphNodes(user, {relationshipFilter:'FRIEND'}) YIELD node
RETURN node;
----
