[[expand-subgraph]]
== Expand to subgraph

[abstract]
--
This section describes a procedure that expands a subgraph from a set of start nodes, and returns all nodes and relationships within the subgraph.
--

The expand to subgraph procedure expands to subgraph nodes reachable from the start node following relationships to max-level adhering to the label filters.
Returns the collection of nodes in the subgraph, and the collection of relationships between all subgraph nodes.
It allows fine grained control over the traversals that expand these subgraphs.

This section includes:

* <<expand-subgraph-overview>>
* <<expand-subgraph-config>>
* <<expand-subgraph-examples>>

[[expand-subgraph-overview]]
=== Procedure Overview

The procedure is described below:

[separator=¦,opts=header,cols="1,1m,1m,5"]
|===
include::../../../build/generated-documentation/apoc.path.subgraphAll.csv[]
|===

[[expand-subgraph-config]]
=== Configuration parameters

include::config-params.adoc[]

[[expand-subgraph-relationship-filters]]
==== Relationship Filters

The syntax for relationship filters is described below:

include::relationship-filter.adoc[]

[[expand-subgraph-label-filters]]
==== Label Filters

The syntax for label filters is described below:

include::label-filter.adoc[]

*Label filter operator precedence and behavior*

include::label-filter-precedence.adoc[]


[[expand-subgraph-examples]]
=== Examples


Expand to local subgraph (and all its relationships) within 4 traversals:

[source,cypher]
----
MATCH (user:User) WHERE user.id = 460
CALL apoc.path.subgraphAll(user, {maxLevel:4}) YIELD nodes, relationships
RETURN nodes, relationships;
----

