[[path-expander-paths-config]]
== Expand paths with config

[abstract]
--
This section describes a procedure that can be used to expand the paths of variable length path traversals, while providing configuration options.
--

[[path-expander-paths-config-overview]]
=== Procedure Overview

The procedure is described below:

[separator=¦,opts=header,cols="1,1m,1m,5"]
|===
include::../../../build/generated-documentation/apoc.path.expandConfig.csv[]
|===

[[path-expander-paths-config-config]]
=== Configuration

Takes an additional map parameter, `config`, to provide configuration options:

----
{minLevel: -1|number,
 maxLevel: -1|number,
 relationshipFilter: '[<]RELATIONSHIP_TYPE1[>]|[<]RELATIONSHIP_TYPE2[>], [<]RELATIONSHIP_TYPE3[>]|[<]RELATIONSHIP_TYPE4[>]',
 labelFilter: '[+-/>]LABEL1|LABEL2|*,[+-/>]LABEL1|LABEL2|*,...',
 uniqueness: RELATIONSHIP_PATH|NONE|NODE_GLOBAL|NODE_LEVEL|NODE_PATH|NODE_RECENT|
             RELATIONSHIP_GLOBAL|RELATIONSHIP_LEVEL|RELATIONSHIP_RECENT,
 bfs: true|false,
 filterStartNode: true|false,
 limit: -1|number,
 optional: true|false,
 endNodes: [nodes],
 terminatorNodes: [nodes],
 beginSequenceAtStart: true|false}
----

*Label filter operator precedence and behavior*

include::label-filter-precedence.adoc[]

*Sequences*

include::sequences.adoc[]
include::sequence-tips.adoc[]


*Start node and label filters*

include::start-node-label-filters.adoc[]


*Limit*

include::limit-expand.adoc[]


*Optional*

include::optional.adoc[]


*Uniqueness*

include::uniqueness-expand.adoc[]


*Node filters*

include::node-filter.adoc[]


[[path-expander-paths-config-examples]]
=== Examples

.Termination and end node label filter example

We will first set a `:Western` label on some nodes.

[source,cypher]
----
match (p:Person)
where p.name in ['Clint Eastwood', 'Gene Hackman']
set p:Western
----

Now expand from 'Keanu Reeves' to all `:Western` nodes with a termination filter:

[source,cypher]
----
match (k:Person {name:'Keanu Reeves'})
call apoc.path.expandConfig(k, {relationshipFilter:'ACTED_IN|PRODUCED|DIRECTED', labelFilter:'/Western', uniqueness: 'NODE_GLOBAL'}) yield path
return path
----

The one returned path only matches up to 'Gene Hackman'.
While there is a path from 'Keanu Reeves' to 'Clint Eastwood' through 'Gene Hackman', no further expansion is permitted through a node in the termination filter.

If you didn't want to stop expansion on reaching 'Gene Hackman', and wanted 'Clint Eastwood' returned as well, use the end node filter  instead (`>`).

You can turn this cypher query:

[source,cypher]
----
MATCH (user:User) WHERE user.id = 460
MATCH (user)-[:RATED]->(movie)<-[:RATED]-(collab)-[:RATED]->(reco)
RETURN count(*);
----

into this procedure call, with changed semantics for uniqueness and bfs (which is Cypher's expand mode)

[source,cypher]
----
MATCH (user:User) WHERE user.id = 460
CALL apoc.path.expandConfig(user,{
    relationshipFilter:"RATED",
    minLevel:3,
    maxLevel:3,
    bfs:false,
    uniqueness:"NONE"
})
YIELD path
RETURN count(*);
----
