version: '3'

x-shared:
  &common
  NEO4J_AUTH: neo4j/foobar
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_causal__clustering_initial__discovery__members: core1:5000,core2:5000,core3:5000
  NEO4J_dbms_memory_pagecache_size: "1G"
  NEO4J_dbms_memory_heap_initial__size: "1G"
  NEO4J_dbms_memory_heap_max__size: "1G"
  NEO4J_dbms_routing_enabled: "true"
  NEO4J_dbms_allow__upgrade: "true"
  NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
  apoc.trigger.enabled: "true"
  apoc.uuid.enabled: "true"
  NEO4J_dbms_routing_listen__address: 0.0.0.0:7618

x-shared-core:
  &common-core
  <<: *common
  NEO4J_dbms_mode: CORE
  NEO4J_causal__clustering_minimum__core__cluster__size__at__formation: 3

services:
  core1:
    image: neo4j:4.4-enterprise
    hostname: core1
    networks:
      neo4j-net:
        aliases:
          - neo4j-network
    ports:
      - "7474:7474"
      - "7687:7687"
      - "5005:5005"
    volumes:
      - /Users/ncordon/neo4j/apoc-4.4/full/build/libs/:/var/lib/neo4j/plugins
    environment:
      <<: *common-core
      NEO4J_causal__clustering_discovery__advertised__address: core1:5000
      NEO4J_causal__clustering_transaction__advertised__address: core1:6000
      NEO4J_causal__clustering_raft__advertised__address: core1:7000
      NEO4J_dbms_routing_advertised__address: core1:7618
      NEO4J_dbms_routing_default__router: "SERVER"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687"
      NEO4J_dbms_jvm_additional: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

  core2:
    image: neo4j:4.4-enterprise
    hostname: core2
    networks:
      neo4j-net:
        aliases:
          - neo4j-network
    ports:
      - "7475:7474"
      - "7688:7687"
      - "5006:5006"
    volumes:
      - /Users/ncordon/neo4j/apoc-4.4/full/build/libs/:/var/lib/neo4j/plugins
    environment:
      <<: *common-core
      NEO4J_causal__clustering_discovery__advertised__address: core2:5000
      NEO4J_causal__clustering_transaction__advertised__address: core2:6000
      NEO4J_causal__clustering_raft__advertised__address: core2:7000
      NEO4J_dbms_routing_advertised__address: core2:7618
      NEO4J_dbms_routing_default__router: "SERVER"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7688"
      NEO4J_dbms_jvm_additional: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"

  core3:
    image: neo4j:4.4-enterprise
    hostname: core3
    networks:
      neo4j-net:
        aliases:
          - neo4j-network
    ports:
      - "7476:7474"
      - "7689:7687"
      - "5007:5007"
    volumes:
      - /Users/ncordon/neo4j/apoc-4.4/full/build/libs/:/var/lib/neo4j/plugins
    environment:
      <<: *common-core
      NEO4J_causal__clustering_discovery__advertised__address: core3:5000
      NEO4J_causal__clustering_transaction__advertised__address: core3:6000
      NEO4J_causal__clustering_raft__advertised__address: core3:7000
      NEO4J_dbms_routing_advertised__address: core3:7618
      NEO4J_dbms_routing_default__router: "SERVER"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7689"
      NEO4J_dbms_jvm_additional: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007"

  readreplica1:
    image: neo4j:4.4-enterprise
    hostname: readreplica1
    networks:
      neo4j-net:
        aliases:
          - neo4j-network
    ports:
      - "7477:7474"
      - "7690:7687"
      - "5008:5008"
    volumes:
      - /Users/ncordon/neo4j/apoc-4.4/full/build/libs/:/var/lib/neo4j/plugins
    environment:
      <<: *common
      NEO4J_dbms_mode: READ_REPLICA
      NEO4J_causal__clustering_discovery__advertised__address: readreplica1:5000
      NEO4J_causal__clustering_transaction__advertised__address: readreplica1:6000
      NEO4J_causal__clustering_raft__advertised__address: readreplica1:7000
      NEO4J_dbms_routing_advertised__address: readreplica1:7618
      NEO4J_dbms_routing_default__router: "SERVER"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7690"
      NEO4J_dbms_jvm_additional: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008"

networks:
  neo4j-net:
