////
This file is generated by DocsTest, so don't change it!
////

= apoc.node
:description: This section contains reference documentation for the apoc.node procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.node/apoc.node.degree.adoc[apoc.node.degree icon:book[]]

apoc.node.degree(node, rel-direction-pattern) - returns total degrees of the given relationships in the pattern, can use '>' or '<' for all outgoing or incoming relationships
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.node/apoc.node.degree.in.adoc[apoc.node.degree.in icon:book[]]

apoc.node.degree.in(node, relationshipName) - returns total number number of incoming relationships
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.node/apoc.node.degree.out.adoc[apoc.node.degree.out icon:book[]]

apoc.node.degree.out(node, relationshipName) - returns total number number of outgoing relationships
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.node/apoc.node.id.adoc[apoc.node.id icon:book[]]

returns id for (virtual) nodes
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.node/apoc.node.labels.adoc[apoc.node.labels icon:book[]]

returns labels for (virtual) nodes
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.node/apoc.node.relationship.exists.adoc[apoc.node.relationship.exists icon:book[]]

apoc.node.relationship.exists(node, rel-direction-pattern) - returns true when the node has the relationships of the pattern
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.node/apoc.node.relationship.types.adoc[apoc.node.relationship.types icon:book[]]

apoc.node.relationship.types(node, rel-direction-pattern) - returns a list of distinct relationship types
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.node/apoc.node.relationships.exist.adoc[apoc.node.relationships.exist icon:book[]]

apoc.node.relationships.exist(node, rel-direction-pattern) - returns a map with rel-pattern, boolean for the given relationship patterns
|label:function[]
|label:apoc-core[]
|===

