We can extract the metadata and h2 heading from the https://en.wikipedia.org/[Wikipedia home page^], by running the following query:

[source,cypher]
----
CALL apoc.load.html("https://en.wikipedia.org/",{metadata:"meta", h2:"h2"});
----

.Results
[opts="header",cols="1"]
|===
| Output
a|
[source,json]
----
{
   "metadata":[
      {
         "tagName":"meta",
         "attributes":{
            "charset":"UTF-8"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "name":"ResourceLoaderDynamicStyles"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "name":"generator",
            "content":"MediaWiki 1.36.0-wmf.16"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "name":"referrer",
            "content":"origin"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "name":"referrer",
            "content":"origin-when-crossorigin"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "name":"referrer",
            "content":"origin-when-cross-origin"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "property":"og:image",
            "content":"https://upload.wikimedia.org/wikipedia/commons/1/1c/Orion_pulse_unit_%28transparent%29.png"
         }
      }
   ],
   "h2":[
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-tfa-h2"
         },
         "text":"From today's featured article",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-dyk-h2"
         },
         "text":"Did you know ...",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-itn-h2"
         },
         "text":"In the news",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-otd-h2"
         },
         "text":"On this day",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-tfl-h2"
         },
         "text":"From today's featured list",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-tfp-h2"
         },
         "text":"Today's featured picture",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-other"
         },
         "text":"Other areas of Wikipedia",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-sister"
         },
         "text":"Wikipedia's sister projects",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-lang"
         },
         "text":"Wikipedia languages",
         "tagName":"h2"
      },
      {
         "tagName":"h2",
         "text":"Navigation menu"
      }
   ]
}
----
|===

Let's suppose we have a `test.html` file like this:
[source,html]
----
<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">
  <h6 i d="error">test</h6>
  <h6 id="correct">test</h6>
</html>
----

We can handle the parse error caused by `i d` through `failSilently` configuration.
So, we can execute:

[source,cypher]
----
CALL apoc.load.html("test.html",{h6:"h6"});
----
.Results
[opts="header"]
|===
| Failed to invoke procedure `apoc.load.html`: Caused by: java.lang.RuntimeException: Error during parsing element: <h6 i d="error">test</h6>
|===

or with failSilently `WITH_LIST`:

[source,cypher]
----
CALL apoc.load.html("test.html",{h6:"h6"}, {failSilently: 'WITH_LIST'});
----

.Results
[opts="header"]
|===
| Output
a|
[source,json]
----
{
  "errorList": [
    "<h6 i d="error">test</h6>"
  ],
  "h6": [
    {
      "attributes": {
        "id": "correct"
      },
      "text": "test",
      "tagName": "h6"
    }
  ]
}
----
|===

or with failSilently `WITH_LOG` (note that will be created a `log.warn("Error during parsing element: <h6 i d="error">test</h6>")` ):

[source,cypher]
----
CALL apoc.load.html("test.html",{h6:"h6"}, {failSilently: 'WITH_LOG'});
----

.Results
[opts="header"]
|===
| Output
a|
[source,json]
----
{
  "h6": [
    {
      "attributes": {
        "id": "correct"
      },
      "text": "test",
      "tagName": "h6"
    }
  ]
}
----
|===

include::partial$html/runtime.adoc[]

For example, with the above file we can execute:

[source,cypher]
----
CALL apoc.load.html("test.html",{strong: "strong"}, {browser: "FIREFOX"});
----
.Results
[opts="header"]
|===
| Output
a|
[source,json]
----
{
  "strong": [
    {
      "tagName": "strong",
      "text": "This is a new text node"
    }
  ]
}
----
|===

If we have to parse a tag from a slow async call, we can use `wait` config to waiting for 10 second (in this example):

[source,cypher]
----
CALL apoc.load.html("test.html",{asyncTag: "#asyncTag"}, {browser: "FIREFOX", wait: 10});
----



We can also pass an HTML string into the 1st parameter by putting as a config parameter `htmlString: true`, for example:

[source,cypher]
----
CALL apoc.load.html("<!DOCTYPE html> <html> <body> <p class='firstClass'>My first paragraph.</p> </body> </html>",{body:"body"}, {htmlString: true})
YIELD value
RETURN value["body"] as body
----

.Results
[opts="header"]
|===
| body
a|
[source, json]
----
[{
  "attributes": {},
  "text": "My first paragraph.",
  "tagName": "body"
}]
----
|===


include::partial$html/query-selectors.adoc[]

For example, we can execute:

[source,cypher]
----
CALL apoc.load.html($url, {nameKey: '#idName'})
----

.Results
[opts="header"]
|===
| Output
a|
[source,json]
----
{
  "h6": [
    {
      "attributes": {
        "id": "idName"
      },
      "text": "test",
      "tagName": "h6"
    }
  ]
}
----
|===

== Html plain text representation

If, instead of a map of json list results, 
you want to get a map of plain text representations,
you can use the xref::overview/apoc.load/apoc.load.htmlPlainText.adoc[apoc.load.htmlPlainText procedure], which use the same syntax, logic and config parameters as `apoc.load.html`.

