The following converts a JSON map into a Cypher map:

[source, cypher]
----
RETURN apoc.convert.fromJsonMap('{"name": "Graph Data Science Library"}') AS output;
----

.Results
[opts="header"]
|===
| Output
| {name: "Graph Data Science Library"}
|===

We can also use JSON path expressions to extract part of a JSON map.
For example, the following extracts the `product` property from a JSON map and returns a map:

[source, cypher]
----
RETURN apoc.convert.fromJsonMap('{"product": {"name": "Bloom"}}', '$.product') AS output;
----

.Results
[opts="header"]
|===
| Output
| {name: "Bloom"}
|===

If we try to convert a non-map structure, we'll get an exception.
For example:

[source, cypher]
----
RETURN apoc.convert.fromJsonMap('[{"name": "Neo4j"}]') AS output;
----

.Results
|===
| Failed to invoke function `apoc.convert.fromJsonMap`: Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` out of START_ARRAY token
at [Source: (String)"[{"name": "Neo4j"}]"; line: 1, column: 1]
|===

In this case we should instead use xref::overview/apoc.convert/apoc.convert.fromJsonList.adoc[].


Moreover, we can customize the Json path options, adding as third parameter (`pathOptions`) a list of strings,
where the strings are based on https://javadoc.io/doc/com.jayway.jsonpath/json-path/2.4.0/com/jayway/jsonpath/Option.html[Enum<Option>].
The default value is `["SUPPRESS_EXCEPTIONS", "DEFAULT_PATH_LEAF_TO_NULL"]`. Note that we can also insert `[]`, that is "without options".
So we can execute (with default pathOptions):

[source, cypher]
----
RETURN apoc.convert.fromJsonMap('{ "columns": {
      "col2": {
        "_id": "772col2"
      }
    }
}', '$.columns.col2') AS output;
----

.Results
[opts="header"]
|===
| output
| { "_id": "772col2" }
|===

or, with custom path options:

[source, cypher]
----
RETURN apoc.convert.fromJsonMap('{ "columns": {
      "col2": {
        "_id": "772col2"
      }
    }
}', '$.columns.col2', ['ALWAYS_RETURN_LIST']) AS output;
----

.Results
[opts="header"]
|===
| Failed to invoke function `apoc.convert.getJsonPropertyMap`: Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` out of START_ARRAY token at [Source: UNKNOWN; line: -1, column: -1]
|===