The examples in this section are based on the following sample graph:

[source,cypher]
----
CREATE (Keanu:Person {name:'Keanu Reeves', born:1964})
CREATE (TomH:Person {name:'Tom Hanks', born:1956})

CREATE (TheMatrix:Movie {title:'The Matrix', released:1999, tagline:'Welcome to the Real World'})
CREATE (TheMatrixReloaded:Movie {title:'The Matrix Reloaded', released:2003, tagline:'Free your mind'})
CREATE (TheMatrixRevolutions:Movie {title:'The Matrix Revolutions', released:2003, tagline:'Everything that has a beginning has an end'})
CREATE (SomethingsGottaGive:Movie {title:"Something's Gotta Give", released:2003})
CREATE (TheDevilsAdvocate:Movie {title:"The Devil's Advocate", released:1997, tagline:'Evil has its winning ways'})

CREATE (YouveGotMail:Movie {title:"You've Got Mail", released:1998, tagline:'At odds in life... in love on-line.'})
CREATE (SleeplessInSeattle:Movie {title:'Sleepless in Seattle', released:1993, tagline:'What if someone you never met, someone you never saw, someone you never knew was the only someone for you?'})
CREATE (ThatThingYouDo:Movie {title:'That Thing You Do', released:1996, tagline:'In every life there comes a time when that thing you dream becomes that thing you do'})
CREATE (CloudAtlas:Movie {title:'Cloud Atlas', released:2012, tagline:'Everything is connected'})

CREATE (Keanu)-[:ACTED_IN {roles:['Neo']}]->(TheMatrix)
CREATE (Keanu)-[:LEADING_ACTOR {roles:['Neo']}]->(TheMatrix)
CREATE (Keanu)-[:ACTED_IN {roles:['Neo']}]->(TheMatrixReloaded)
CREATE (Keanu)-[:ACTED_IN {roles:['Neo']}]->(TheMatrixRevolutions)
CREATE (Keanu)-[:ACTED_IN {roles:['Julian Mercer']}]->(SomethingsGottaGive)
CREATE (Keanu)-[:ACTED_IN {roles:['Kevin Lomax']}]->(TheDevilsAdvocate)

CREATE (TomH)-[:ACTED_IN {roles:['Joe Fox']}]->(YouveGotMail)
CREATE (TomH)-[:ACTED_IN {roles:['Sam Baldwin']}]->(SleeplessInSeattle)
CREATE (TomH)-[:ACTED_IN {roles:['Mr. White']}]->(ThatThingYouDo)
CREATE (TomH)-[:ACTED_IN {roles:['Zachry', 'Dr. Henry Goose', 'Isaac Sachs', 'Dermot Hoggins']}]->(CloudAtlas);
----

[source,cypher]
----
CALL apoc.meta.data();
----

.Results
[opts="header"]
|===
| label             | property          | count | unique | index | existence | type           | array | sample | leftCount | rightCount | left | right | other     | otherLabels | elementType
| "ACTED_IN"        | "Person"          | 9     | FALSE  | FALSE | FALSE     | "RELATIONSHIP" | TRUE  | NULL   | 0         | 0          | 0    | 0     | ["Movie"] | []          | "relationship"
| "ACTED_IN"        | "roles"           | 0     | FALSE  | FALSE | FALSE     | "LIST"         | TRUE  | NULL   | 0         | 0          | 0    | 0     | []        | []          | "relationship"
| "LEADING_ACTOR"	| "Person"          | 	1	| FALSE  | FALSE | FALSE     | "RELATIONSHIP" | FALSE | NULL   | 0	       | 0	        | 0    | 0	   | ["Movie"] | []          | "relationship"
| "LEADING_ACTOR"	| "roles"	        | 0	    | FALSE  | FALSE | FALSE     | "LIST"	      | TRUE  | NULL   | 0         | 0          | 0	   | 0	   | []	       | []          | "relationship"
| "Person"          | "ACTED_IN"        | 9     | FALSE  | FALSE | FALSE     | "RELATIONSHIP" | TRUE  | NULL   | 0         | 0          | 0    | 0     | ["Movie"] | []          | "node"
| "Person"	        | "LEADING_ACTOR"	| 1	    | FALSE  | FALSE | FALSE	 | "RELATIONSHIP" | FALSE | NULL   | 0         | 0	        | 0    | 0	   | ["Movie"] | []	         | "node"
| "Person"          | "name"            | 0     | FALSE  | FALSE | FALSE     | "STRING"       | FALSE | NULL   | 10        | 0          | 7    | 0     | []        | []          | "node"
| "Person"          | "born"            | 0     | FALSE  | FALSE | FALSE     | "INTEGER"      | FALSE | NULL   | 10        | 0          | 7    | 0     | []        | []          | "node"
| "Movie"           | "title"           | 0     | FALSE  | FALSE | FALSE     | "STRING"       | FALSE | NULL   | 0         | 10         | 0    | 9     | []        | []          | "node"
| "Movie"           | "tagline"         | 0     | FALSE  | FALSE | FALSE     | "STRING"       | FALSE | NULL   | 0         | 10         | 0    | 9     | []        | []          | "node"
| "Movie"           | "released"        | 0     | FALSE  | FALSE | FALSE     | "INTEGER"      | FALSE | NULL   | 0         | 9          | 0    | 8     | []        | []          | "node"
|===

The `unique` column shows if there is an unique constraint in that specific label and property.
Similarly, the `index` column show if there is an index or not, while the `existence` looks for an existence constraint.

The `array` column check if the row is of type array and, in case `type` columns is `"RELATIONSHIP"`,
the result will be `true` if there is at least one node with 2 outgoing relationships with the type of relation given by `label` or `property` column, 
so `ACTED_IN` in the example above.

The `leftCount`, `rightCount`, `left` and `right` columns regard only rows with column `elementType` equal to `"node"` and `type` not equal to `"RELATIONSHIP"` (otherwise they are equal to `0`)
In particular, `leftCount`, `rightCount` are the sum of respectively outgoing and incoming relationships.
The `left` and `right` values are the sum, for each node, of the relationship number divided by number of relationship type (rounded down). 
Even in this case, for the `left` number we consider only outgoing relationships, and for the `right` number we consider the incoming ones.
So, with the above dataset, `(Person {name:'Keanu Reeves'})` has 6 outgoing relationships and 2 rel-type (`ACTED_IN` and `LEADING_ACTOR`),
so the count is 3, while `(:Person {name:'Tom Hanks'})` has 4 relationships with the same type, so the count is 4, 
therefore the `left` for the rows with label `Person` is `3 + 4`.