The examples in this section are based on the following file:

.$NEO4J_HOME/import/createConstraint.cypher
[source, cypher]
----
CREATE CONSTRAINT ON (n:Person) ASSERT n.name IS UNIQUE;
----

.$NEO4J_HOME/import/dropConstraint.cypher
[source, cypher]
----
DROP CONSTRAINT ON (n:Person) ASSERT n.name IS UNIQUE;
----

We can run the Cypher commands in `createConstraint.cypher` and `dropConstraint.cypher`, by running the following query:

[source,cypher]
----
CALL apoc.cypher.runSchemaFiles(["createConstraint.cypher", "dropConstraint.cypher"]);
----

.Results
[opts="header", cols="1,5"]
|===
| row | result
| -1  | {constraintsRemoved: 0, indexesRemoved: 0, nodesCreated: 0, rows: 0, propertiesSet: 0, labelsRemoved: 0, relationshipsDeleted: 0, constraintsAdded: 1, nodesDeleted: 0, indexesAdded: 0, labelsAdded: 0, relationshipsCreated: 0, time: 0}
| -1  | {constraintsRemoved: 1, indexesRemoved: 0, nodesCreated: 0, rows: 0, propertiesSet: 0, labelsRemoved: 0, relationshipsDeleted: 0, constraintsAdded: 0, nodesDeleted: 0, indexesAdded: 0, labelsAdded: 0, relationshipsCreated: 0, time: 0}
|===

If we don't want to see statistics for each Cypher statement, we can set `statistics: false`:

[source,cypher]
----
CALL apoc.cypher.runSchemaFiles(["createConstraint.cypher", "dropConstraint.cypher"], {statistics: false});
----

.Results
[opts="header", cols="1,5"]
|===
| row | result
|===