[source,cypher]
----
CALL apoc.schema.assert({
  Person: ["id"]
}, {
  Person: ["name"]
});
----

We can create a uniqueness constraint on `:Person(name)` and an index on `:Person(id)` by running the following query:

.Results
[opts="header"]
|===
| label    | key    | keys     | unique | action
| "Person" | "id"   | ["id"]   | FALSE  | "CREATED"
| "Person" | "name" | ["name"] | TRUE   | "CREATED"
|===

We can drop all constraints and indexes, by running the following query.
Note that the cancellation mechanism doesn't consider indexes of type `LOOKUP` and multi-token indexes, that is indexes applicable to multiple rel-types or multiple labels, 
for example `CREATE FULLTEXT INDEX titlesAndDescriptions FOR (n:Movie|Book) ON EACH [n.title, n.description]` or `CALL db.index.fulltext.createRelationshipIndex('fullIdxRel', ['TYPE_1', 'TYPE_2'], ['alpha', 'beta'])`. 
This because they cannot be re-created by the `apoc.schema.assert` procedure:

[source,cypher]
----
CALL apoc.schema.assert({}, {});
----


.Results
[opts="header"]
|===
| label    | key    | keys     | unique | action
| "Person" | "id"   | ["id"]   | FALSE  | "DROPPED"
| "Person" | "name" | ["name"] | TRUE   | "DROPPED"
|===

