The following converts a JSON list into a Cypher list:

[source, cypher]
----
RETURN apoc.convert.fromJsonList('[1,2,3]') AS output;
----

.Results
[opts="header"]
|===
| Output
| [1, 2, 3]
|===

We can also use JSON path expressions to extract part of a JSON list.
For example, the following extracts the `name` property from a JSON list of objects and returns a list of Cypher strings:

[source, cypher]
----
RETURN apoc.convert.fromJsonList('[
  {"name": "Neo4j"},
  {"name": "Graph Data Science Library"},
  {"name": "Bloom"}
]', '.name') AS output;
----

.Results
[opts="header"]
|===
| Output
| ["Neo4j", "Graph Data Science Library", "Bloom"]
|===

Moreover, we can customize the Json path options, adding as third parameter (`pathOptions`) a list of strings,
where the strings are based on https://javadoc.io/doc/com.jayway.jsonpath/json-path/2.4.0/com/jayway/jsonpath/Option.html[Enum<Option>].
The default value is `["SUPPRESS_EXCEPTIONS", "DEFAULT_PATH_LEAF_TO_NULL"]`. Note that we can also insert `[]`, that is "without options".
So we can execute (with default pathOptions):

[source, cypher]
----
RETURN apoc.convert.fromJsonList('{ "columns": {
      "col2": {
        "_id": "772col2"
      }
    }
}', '$..columns') AS output;
----

.Results
[opts="header"]
|===
| output
| [ {"col2": { "_id": "772col2" }}, null, null ]
|===

or, with custom path options:

[source, cypher]
----
RETURN apoc.convert.fromJsonList('{ "columns": {
      "col2": {
        "_id": "772col2"
      }
    }
}', '$..columns', ['ALWAYS_RETURN_LIST']) AS output;
----

.Results
[opts="header"]
|===
| output
| [ {"col2": { "_id": "772col2" }} ]
|===



If we try to convert a non-list structure, we'll get an exception.
For example:

[source, cypher]
----
RETURN apoc.convert.fromJsonList('{"name": "Neo4j"}') AS output;
----

.Results
|===
| Failed to invoke function `apoc.convert.fromJsonList`: Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of START_OBJECT token
at [Source: (String)"{"name": "Neo4j"}"; line: 1, column: 1]
|===

In this case we should instead use xref::overview/apoc.convert/apoc.convert.fromJsonMap.adoc[].
