The examples in this section are based on the following sample graph:

[source,cypher]
----
CREATE (Keanu:Person {name:'Keanu Reeves', born:1964})
CREATE (TomH:Person {name:'Tom Hanks', born:1956})

CREATE (TheMatrix:Movie {title:'The Matrix', released:1999, tagline:'Welcome to the Real World'})
CREATE (TheMatrixReloaded:Movie {title:'The Matrix Reloaded', released:2003, tagline:'Free your mind'})
CREATE (TheMatrixRevolutions:Movie {title:'The Matrix Revolutions', released:2003, tagline:'Everything that has a beginning has an end'})
CREATE (SomethingsGottaGive:Movie {title:"Something's Gotta Give", released:2003})
CREATE (TheDevilsAdvocate:Movie {title:"The Devil's Advocate", released:1997, tagline:'Evil has its winning ways'})

CREATE (YouveGotMail:Movie {title:"You've Got Mail", released:1998, tagline:'At odds in life... in love on-line.'})
CREATE (SleeplessInSeattle:Movie {title:'Sleepless in Seattle', released:1993, tagline:'What if someone you never met, someone you never saw, someone you never knew was the only someone for you?'})
CREATE (ThatThingYouDo:Movie {title:'That Thing You Do', released:1996, tagline:'In every life there comes a time when that thing you dream becomes that thing you do'})
CREATE (CloudAtlas:Movie {title:'Cloud Atlas', released:2012, tagline:'Everything is connected'})

CREATE (Keanu)-[:ACTED_IN {roles:['Neo']}]->(TheMatrix)
CREATE (Keanu)-[:ACTED_IN {roles:['Neo']}]->(TheMatrixReloaded)
CREATE (Keanu)-[:ACTED_IN {roles:['Neo']}]->(TheMatrixRevolutions)
CREATE (Keanu)-[:ACTED_IN {roles:['Julian Mercer']}]->(SomethingsGottaGive)
CREATE (Keanu)-[:ACTED_IN {roles:['Kevin Lomax']}]->(TheDevilsAdvocate)

CREATE (TomH)-[:ACTED_IN {roles:['Joe Fox']}]->(YouveGotMail)
CREATE (TomH)-[:ACTED_IN {roles:['Sam Baldwin']}]->(SleeplessInSeattle)
CREATE (TomH)-[:ACTED_IN {roles:['Mr. White']}]->(ThatThingYouDo)
CREATE (TomH)-[:ACTED_IN {roles:['Zachry', 'Dr. Henry Goose', 'Isaac Sachs', 'Dermot Hoggins']}]->(CloudAtlas);
----

[source,cypher]
----
CALL apoc.meta.data();
----

.Results
[opts="header"]
|===
| label      | property   | count | unique | index | existence | type           | array | sample | leftCount | rightCount | left | right | other     | otherLabels | elementType
| "ACTED_IN" | "Person"   | 9     | FALSE  | FALSE | FALSE     | "RELATIONSHIP" | TRUE  | NULL   | 41        | 9          | 4    | 1     | ["Movie"] | []          | "relationship"
| "ACTED_IN" | "roles"    | 0     | FALSE  | FALSE | FALSE     | "LIST"         | TRUE  | NULL   | 0         | 0          | 0    | 0     | []        | []          | "relationship"
| "Person"   | "ACTED_IN" | 9     | FALSE  | FALSE | FALSE     | "RELATIONSHIP" | TRUE  | NULL   | 41        | 9          | 4    | 1     | ["Movie"] | []          | "node"
| "Person"   | "name"     | 0     | FALSE  | FALSE | FALSE     | "STRING"       | FALSE | NULL   | 0         | 0          | 0    | 0     | []        | []          | "node"
| "Person"   | "born"     | 0     | FALSE  | FALSE | FALSE     | "INTEGER"      | FALSE | NULL   | 0         | 0          | 0    | 0     | []        | []          | "node"
| "Movie"    | "title"    | 0     | FALSE  | FALSE | FALSE     | "STRING"       | FALSE | NULL   | 0         | 0          | 0    | 0     | []        | []          | "node"
| "Movie"    | "tagline"  | 0     | FALSE  | FALSE | FALSE     | "STRING"       | FALSE | NULL   | 0         | 0          | 0    | 0     | []        | []          | "node"
| "Movie"    | "released" | 0     | FALSE  | FALSE | FALSE     | "INTEGER"      | FALSE | NULL   | 0         | 0          | 0    | 0     | []        | []          | "node"
|===

The `unique` column shows if there is an unique constraint in that specific label and property.
Similarly, the `index` column show if there is an index or not, while the `existence` looks for an existence constraint.

The `array` column check if the row is of type array and, in case `type` columns is `"RELATIONSHIP"`,
the result will be `true` if there is at least one node with 2 outgoing relationships with the type of relation given by `label` or `property` column, 
so `ACTED_IN` in the example above.

The `leftCount`, `rightCount`, `left` and `right` columns regard only rows with column `type` equals to `"RELATIONSHIP"` (otherwise they are equal to `0`)
In particular, `leftCount`, `rightCount` are "weighted" counts of respectively outgoing and incoming relationships,
which for each node it will increase the count with the number of outgoing relations of that type for itself.
That is, if the node has 1 outgoing relationship with the provided type, the count will be increased by 1,
if it has 2 outgoing relationships, increased by 3, with 3 relationships, increased by 9, and so on.
Same thing for `rightCount`, but with incoming relationships instead.
So, with the above dataset, `(Person {name:'Keanu Reeves'})` has 5 relationships, so the count is 25,
and `(:Person {name:'Tom Hanks'})` has 4 relationships, so the count is 16, this explain the total of 41.
Vice versa, every `(:Movie)` ha a single relationship, so the total il 9, like `count` result.

The `right` and `left` results are the ratio (rounded down) of respectively `rightCount` and `leftCount` to `count`.