`map.json` contains a JSON document representing a person and their children.

.map.json
[source,json]
----
{
  "foo":[1,2,3]
}
----

We'll place this file into the `import` directory of our Neo4j instance.
Let's now write a query using the `apoc.load.jsonArray` procedure to explore this file.

The following query processes `map.json` and returns the content as Cypher data structures

[source,cypher]
----
CALL apoc.load.jsonArray("file:///map.json", "$.foo");
----

.Results
[options="header"]
|===
| value
| [1, 2, 3]
|===


Moreover, we can customize the Json path options, adding the config {pathOptions: `LIST OF STRINGS`},
where the strings are based on https://javadoc.io/doc/com.jayway.jsonpath/json-path/2.4.0/com/jayway/jsonpath/Option.html[Enum<Option>].
The default value is `["SUPPRESS_EXCEPTIONS", "DEFAULT_PATH_LEAF_TO_NULL"]`. Note that we can also insert `[]`, that is "without options".
So with the following json:

[source,json]
----
{ "columns": {
      "col2": {
        "_id": "772col2"
      }
    }
}
----

we can execute (with default `pathOptions`):

[source, cypher]
----
CALL apoc.load.jsonArray($url, '$..columns');
----

.Results
[opts="header"]
|===
| value
| [ {"col2": { "_id": "772col2" }}, null, null ]
|===

or, with custom path options:

[source, cypher]
----
CALL apoc.load.jsonArray($url, '$..columns', ['ALWAYS_RETURN_LIST']);
----

.Results
[opts="header"]
|===
| value
| [ {"col2": { "_id": "772col2" }} ]
|===