////
This file is generated by DocsTest, so don't change it!
////

= apoc.schema.assert
:description: This section contains reference documentation for the apoc.schema.assert procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.schema.assert({indexLabel:[[indexKeys]], ...}, {constraintLabel:[constraintKeys], ...}, dropExisting : true) yield label, key, keys, unique, action - drops all other existing indexes and constraints when `dropExisting` is `true` (default is `true`), and asserts that at the end of the operation the given indexes and unique constraints are there, each label:key pair is considered one constraint/label. Non-constraint indexes can define compound indexes with label:[key1,key2...] pairings.

== Signature

[source]
----
apoc.schema.assert(indexes :: MAP?, constraints :: MAP?, dropExisting = true :: BOOLEAN?) :: (label :: ANY?, key :: STRING?, keys :: LIST? OF STRING?, unique :: BOOLEAN?, action :: STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|indexes|MAP?|null
|constraints|MAP?|null
|dropExisting|BOOLEAN?|true
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|label|ANY?
|key|STRING?
|keys|LIST? OF STRING?
|unique|BOOLEAN?
|action|STRING?
|===

[[usage-apoc.schema.assert]]
== Usage Examples
include::partial$usage/apoc.schema.assert.adoc[]

xref::indexes/schema-index-operations.adoc[More documentation of apoc.schema.assert,role=more information]

