////
This file is generated by DocsTest, so don't change it!
////

= apoc.schema
:description: This section contains reference documentation for the apoc.schema procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.schema/apoc.schema.assert.adoc[apoc.schema.assert icon:book[]]

apoc.schema.assert({indexLabel:[[indexKeys]], ...}, {constraintLabel:[constraintKeys], ...}, dropExisting : true) yield label, key, keys, unique, action - drops all other existing indexes and constraints when `dropExisting` is `true` (default is `true`), and asserts that at the end of the operation the given indexes and unique constraints are there, each label:key pair is considered one constraint/label. Non-constraint indexes can define compound indexes with label:[key1,key2...] pairings.
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.schema/apoc.schema.nodes.adoc[apoc.schema.nodes icon:book[]]

CALL apoc.schema.nodes([config]) yield name, label, properties, status, type
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.schema/apoc.schema.properties.distinct.adoc[apoc.schema.properties.distinct icon:book[]]

apoc.schema.properties.distinct(label, key) - quickly returns all distinct values for a given key
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.schema/apoc.schema.properties.distinctCount.adoc[apoc.schema.properties.distinctCount icon:book[]]

apoc.schema.properties.distinctCount([label], [key]) YIELD label, key, value, count - quickly returns all distinct values and counts for a given key
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.schema/apoc.schema.relationships.adoc[apoc.schema.relationships icon:book[]]

CALL apoc.schema.relationships([config]) yield name, startLabel, type, endLabel, properties, status
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.schema/apoc.schema.node.constraintExists.adoc[apoc.schema.node.constraintExists icon:book[]]

RETURN apoc.schema.node.constraintExists(labelName, propertyNames)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.schema/apoc.schema.node.indexExists.adoc[apoc.schema.node.indexExists icon:book[]]

RETURN apoc.schema.node.indexExists(labelName, propertyNames)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.schema/apoc.schema.relationship.constraintExists.adoc[apoc.schema.relationship.constraintExists icon:book[]]

RETURN apoc.schema.relationship.constraintExists(type, propertyNames)
|label:function[]
|label:apoc-core[]
|===

