[[ttl]]
= Time To Live (TTL) - Expire Nodes

[abstract]
--
This section describes procedures that can be used to remove nodes from the database once a time limit has been reached.
--

Some nodes are not meant to live forever.
That's why with APOC you can specify a time by when they are removed from the database, by utilizing a schema index and an additional label.
A few convenience procedures help with that.

ifdef::backend-html5[]
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/e9aoQ9xOmoU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++
endif::[]

Enable TTL with setting in `apoc.conf` : `apoc.ttl.enabled=true`

There are some convenience procedures to expire nodes.

You can also do it yourself by running

[source,cypher]
----
SET n:TTL
SET n.ttl = timestamp() + 3600
----

[cols="1m,5"]
|===
| CALL apoc.date.expire.in(node,time,'time-unit') | expire node in given time-delta by setting :TTL label and `ttl` property
| CALL apoc.date.expire(node,time,'time-unit') | expire node at given time by setting :TTL label and `ttl` property
|===

Optionally set `apoc.ttl.schedule=5` as repeat frequency.

== Process

30s after startup an index is created:

[source,cypher]
----
CREATE INDEX ON :TTL(ttl)
----

At startup a statement is scheduled to run every 60s (or configure in `apoc.conf` -  `apoc.ttl.schedule=120`)

[source,cypher]
----
MATCH (t:TTL) where t.ttl < timestamp() WITH t LIMIT 1000 DETACH DELETE t
----

The `ttl` property holds the *time when the node is expired in milliseconds since epoch*.

You can expire your nodes by setting the :TTL label and the ttl property:


[source,cypher]
----
MATCH (n:Foo) WHERE n.bar SET n:TTL, n.ttl = timestamp() + 10000;
----

There is also a procedure that does the same:

[source,cypher]
----
CALL apoc.date.expire(node,time,'time-unit');
CALL apoc.date.expire(n,100,'s');
----
