[[cypher-based-procedures-functions]]
= Custom, Cypher Based Procedures and Functions
:description: This section describes how to register custom Cypher statements as procedures and functions




I wanted for a long time to be able to register Cypher statements as proper procedures and functions, so that they become callable in a standalone way.

You can achieve that with the `apoc.custom.declareProcedure` and `apoc.custom.declareFunction` procedure calls.
Those register a given Cypher statement, prefixed with the `custom.*` namespace, overriding potentially existing ones, so you can redefine them as needed.



The first parameter of the `apoc.custom.declareProcedure` and `apoc.custom.declareFunction` procedures,
is the signature of the procedure/function you want to create.
This looks similar to the `signature` results returned by the `SHOW PROCEDURES YIELD signature`, `SHOW FUNCTIONS YIELD signature` cypher commands, or by the `CALL apoc.help('<fun_or_procedure_name>') YIELD signature` procedure, just without the `?`.
That is:
- for a procedure: `nameProcedure(firstParam = defaultValue :: typeParam , secondParam = defaultValue :: typeParam, ....) :: (firstResult :: typeResult, secondResult :: typeResult, ... )`
- for a function: `nameFunction(firstParam = defaultValue :: typeParam , secondParam = defaultValue :: typeParam, ....) :: typeResult`

Note that, for both procedures and functions, the `= defaultValue` are optionals.
The default values are parsed as JSON.

NOTE: If you want to create a procedure/function with a default `String` parameter with whitespaces, quotes (for example: `"my text ' with ' quote"`) or `"null"` (as a string),
you have to quote the result, e.g `CALL apoc.custom.declareProcedure("procWithNullString(param='null'::STRING)::(output::STRING)", 'return $param as output')`

.Type Names
The `typeParam` and `typeResult` in the signature parameter can be one of the following values:
* FLOAT, DOUBLE, INT, INTEGER, NUMBER, LONG
* TEXT, STRING
* BOOL, BOOLEAN
* POINT, GEO, GEOMETRY
* DATE, DATETIME, LOCALDATETIME, TIME, LOCALTIME, DURATION
* NODE, REL, RELATIONSHIP, EDGE, PATH
* MAP
* LIST TYPE, LIST OF TYPE (where `TYPE` can be one of the previous values)
* ANY


NOTE: If you override procedures or functions you might need to call `call db.clearQueryCaches()` as lookups to internal id's are kept in compiled query plans.

[NOTE]
====
Starting from version 5.11, if we execute a `CALL apoc.custom.declareFunction('nameFun(....)')`, or a `CALL apoc.custom.declareProcedure('nameProc(....)')`,
we cannot execute respectively a `RETURN custom.nameFun(..)` or a `CALL custom.nameProc()` within the same transaction, an error will be thrown.

So we must necessarily open a new transaction to execute the custom procedures / functions declared.
====


== Custom Procedures with `apoc.custom.declareProcedure`

include::partial$usage/apoc.custom.declareProcedure.adoc[]

== Custom Functions with `apoc.custom.declareFunction`

include::partial$usage/apoc.custom.declareFunction.adoc[]


== List of registered procedures/function with `apoc.custom.list`

The procedure `apoc.custom.list` provide a list of all registered procedures/function via
`apoc.custom.declareProcedure` and `apoc.custom.declareFunction`

Given the this call:

[source,cypher]
----
CALL apoc.custom.list
----

The output will look like the following table:

[%autowidth,opts=header]
|===
| type | name | description | mode | statement | inputs | outputs | forceSingle
| "function"  | "answer" | <null> | <null> | "RETURN $input as answer" | [["input","number"]] | "long" | false
| "procedure" | "answer" | "Procedure that answer to the Ultimate Question of Life, the Universe, and Everything" | "read" | "RETURN $input as answer" | [["input","int","42"]] | [["answer","number"]] | <null>
|===


== Remove a procedure `apoc.custom.removeProcedure`

The procedure `apoc.custom.removeProcedure` allows to delete the targeted custom procedure.


Given the this call:

[source,cypher]
----
CALL apoc.custom.removeProcedure(<name>)
----

Fields:

[%autowidth,opts=header]
|===
| argument | description
| name  | the procedure name
|===


== Remove a procedure `apoc.custom.removeFunction`

The procedure `apoc.custom.removeFunction` allows to delete the targeted custom function.


Given the this call:

[source,cypher]
----
CALL apoc.custom.removeFunction(<name>)
----

Fields:

[%autowidth,opts=header]
|===
| argument | description
| name  | the function name
|===


== How to manage procedure/function replication in a Causal Cluster

In order to replicate the procedure/function in a cluster environment you can tune the following parameters:

[%autowidth,opts=header]
|===
| name | type | description
| `apoc.custom.procedures.refresh` | long (default `60000`) | the refresh time that allows replicating the procedure/function
changes to each cluster member
|===

=== Export metadata

[NOTE]
====
To import custom procedures in another database (for example after a `./neo4j-admin backup` and `/neo4j-admin restore`),
please see the xref::overview/apoc.systemdb/apoc.systemdb.export.metadata.adoc[apoc.systemdb.export.metadata] procedure.
====
