[[cypher-based-procedures-functions]]
= Custom, Cypher Based Procedures and Functions
:description: This section describes how to register custom Cypher statements as procedures and functions




include::partial$systemdbonly.note.adoc[]

[WARNING]
====
Installing, updating or removing a custom Cypher statement is an eventually consistent operation.
Therefore, they are not immediately added/updated/removed,
but they have a refresh rate handled by the Apoc configuration `apoc.custom.procedures.refresh=<MILLISECONDS>`.

In case of a cluster environment,
the `apoc.custom.procedures.refresh` also replicate the procedures/functions to each cluster member.
====

.Available procedures
[separator=¦,opts=header,cols="5,1m,1m"]
|===
¦Qualified Name¦Type¦Release
include::example$generated-documentation/apoc.custom.dropAll.adoc[]
include::example$generated-documentation/apoc.custom.dropFunction.adoc[]
include::example$generated-documentation/apoc.custom.dropProcedure.adoc[]
include::example$generated-documentation/apoc.custom.installFunction.adoc[]
include::example$generated-documentation/apoc.custom.installProcedure.adoc[]
include::example$generated-documentation/apoc.custom.list.adoc[]
include::example$generated-documentation/apoc.custom.show.adoc[]
|===


== Overview

I wanted for a long time to be able to register Cypher statements as proper procedures and functions, so that they become callable in a standalone way.

You can achieve that with the `apoc.custom.installProcedure` and `apoc.custom.installFunction` procedure calls.
Those register a given Cypher statement, prefixed with the `custom.*` namespace, overriding potentially existing ones, so you can redefine them as needed.

The first parameter of the `apoc.custom.installProcedure` and `apoc.custom.installFunction` procedures,
is the signature of the procedure/function you want to create.

This looks similar to the `signature` results returned by the `SHOW PROCEDURES YIELD signature`, `SHOW FUNCTIONS YIELD signature` cypher commands, or by the `CALL apoc.help('<fun_or_procedure_name>') YIELD signature` procedure, just without the `?`.
That is:
- for a procedure: `nameProcedure(firstParam = defaultValue :: typeParam , secondParam = defaultValue :: typeParam, ....) :: (firstResult :: typeResult, secondResult :: typeResult, ... )`
- for a function: `nameFunction(firstParam = defaultValue :: typeParam , secondParam = defaultValue :: typeParam, ....) :: typeResult`

Note that, for both procedures and functions, the `= defaultValue` are optionals.


NOTE: If you want to create a procedure/function with a default `String` parameter with whitespaces, quotes (for example: `"my text ' with ' quote"`) or `"null"` (as a string) you have to quote the result, e.g `CALL apoc.custom.declareProcedure("procWithNullString(param='null'::STRING)::(output::STRING)", 'return $param as output')`

== Custom Procedures with `apoc.custom.asProcedure`

Given statement will be registered as a procedure, the results will be turned into a stream of records.

.Parameters
[%autowidth,opts=header,cols="m,m,a"]
|===
| name
| default
| description

| name | none | dot-separated name, will be prefixed with `custom`
| statement | none | cypher statement to run, can use $parameters
| mode | read | execution mode of the procedure: read, write, or schema
| outputs | [["row","MAP"]] | List of pairs of name-type to be used as output columns, need to be in-order with the cypher statement, the default is a special case, that will collect all columns of the statement result into a map
| inputs | [["params","MAP","{}"]] | Pairs or triples of name-type-default, to be used as input parameters. The default just takes an optional map, otherwise they will become proper paramters in order
| description | "" | A general description about the business rules implemented into the procedure
|===

The type names are what you would expect and see in outputs of `dbms.procedures` or `apoc.help` just without the `?`.
The default values are parsed as JSON.

.Type Names
The `typeParam` and `typeResult` in the signature parameter can be one of the following values:

* FLOAT, DOUBLE, INT, INTEGER, INTEGER | FLOAT, NUMBER, LONG
* TEXT, STRING
* BOOL, BOOLEAN
* POINT, GEO, GEOMETRY
* DATE, DATETIME, LOCALDATETIME, TIME, LOCALTIME, DURATION
* NODE, REL, RELATIONSHIP, EDGE, PATH
* MAP
* MAPRESULT (valid for declareFunction, does not wrap the result in a further map. see here: <<map-vs-map-result>>)
* LIST TYPE, LIST OF TYPE (where `TYPE` can be one of the previous values)
* ANY


NOTE: If you override procedures or functions you might need to call `call db.clearQueryCaches()` as lookups to internal id's are kept in compiled query plans.


The following examples assume that we are on the `neo4j` database,
and we want to create the custom procedures/function in that database.

== Custom Procedures with `apoc.custom.installProcedure`

include::partial$usage/apoc.custom.installProcedure.adoc[]

== Custom Functions with `apoc.custom.installFunction`

include::partial$usage/apoc.custom.installFunction.adoc[]


== List of registered procedures/function with `apoc.custom.list`

The procedure `apoc.custom.list` provide a list of all registered procedures/function via
`apoc.custom.installProcedure` and `apoc.custom.installFunction`

Given this call:

[source,cypher]
----
CALL apoc.custom.list
----

The output will look like the following table:

[%autowidth,opts=header]
|===
| type | name | description | mode | statement | inputs | outputs | forceSingle
| "function"  | "answer" | <null> | <null> | "RETURN $input as answer" | [["input","integer \| float"]] | "long" | false
| "procedure" | "answer" | "Procedure that answer to the Ultimate Question of Life, the Universe, and Everything" | "read" | "RETURN $input as answer" | [["input","int","42"]] | [["answer","integer \| float"]] | <null>
|===


== Remove a procedure `apoc.custom.dropProcedure`

The procedure `apoc.custom.dropProcedure` allows to delete the targeted custom procedure, from a specific database (with `neo4j` as a default),
*after a time defined by the configuration `apoc.custom.procedures.refresh`*.


Given this call:

[source,cypher]
----
CALL apoc.custom.dropProcedure(<name>, <databaseName>)
----

Fields:

[%autowidth,opts=header]
|===
| argument | description
| name  | the procedure name
| databaseName  | the database name (default: `neo4j`)
|===


== Remove a procedure `apoc.custom.dropFunction`

The procedure `apoc.custom.dropFunction` allows to delete the targeted custom function, from a specific database (with `neo4j` as a default),
*after a time defined by the configuration `apoc.custom.procedures.refresh`*.


Given this call:

[source,cypher]
----
CALL apoc.custom.dropFunction(<name>)
----

Fields:

[%autowidth,opts=header]
|===
| argument | description
| name  | the function name
| databaseName  | the database name (default: `neo4j`)
|===



=== Export metadata

[NOTE]
====
To import custom procedures in another database (for example after a `./neo4j-admin backup` and `/neo4j-admin restore`),
please see the xref::overview/apoc.systemdb/apoc.systemdb.export.metadata.adoc[apoc.systemdb.export.metadata] procedure.
====


