////
This file is generated by DocsTest, so don't change it!
////

= apoc.log
:description: This section contains reference documentation for the apoc.log procedures.

[.procedures, opts=header, cols='5a,1a']
|===
| Qualified Name | Type
|xref::overview/apoc.log/apoc.log.debug.adoc[apoc.log.debug icon:book[]]

apoc.log.debug(message, params) - logs debug message
|label:procedure[]
|xref::overview/apoc.log/apoc.log.error.adoc[apoc.log.error icon:book[]]

apoc.log.error(message, params) - logs error message
|label:procedure[]
|xref::overview/apoc.log/apoc.log.info.adoc[apoc.log.info icon:book[]]

apoc.log.info(message, params) - logs info message
|label:procedure[]
|xref::overview/apoc.log/apoc.log.warn.adoc[apoc.log.warn icon:book[]]

apoc.log.warn(message, params) - logs warn message
|label:procedure[]

|xref::overview/apoc.log/apoc.log.stream.adoc[apoc.log.stream icon:book[]]

`apoc.log.stream(path STRING, config MAP<STRING, ANY>)` - returns the file contents from the given log, optionally returning only the last n lines.
This procedure requires users to have an admin role.
|label:procedure[]
|===

