////
This file is generated by DocsTest, so don't change it!
////

= apoc.cypher
:description: This section contains reference documentation for the apoc.cypher procedures.

[.procedures, opts=header, cols='5a,1a']
|===
| Qualified Name | Type
|xref::overview/apoc.cypher/apoc.cypher.mapParallel.adoc[apoc.cypher.mapParallel icon:book[]]

apoc.cypher.mapParallel(fragment, params, list-to-parallelize) yield value - executes fragment in parallel batches with the list segments being assigned to _
|label:procedure[]
|xref::overview/apoc.cypher/apoc.cypher.mapParallel2.adoc[apoc.cypher.mapParallel2 icon:book[]]

apoc.cypher.mapParallel2(fragment, params, list-to-parallelize) yield value - executes fragment in parallel batches with the list segments being assigned to _
|label:procedure[]
|xref::overview/apoc.cypher/apoc.cypher.parallel.adoc[apoc.cypher.parallel icon:book[]]

apoc.cypher.parallel(fragment, `paramMap`, `keyList`) yield value - executes fragments in parallel through a list defined in `paramMap` with a key `keyList`
|label:procedure[]
|xref::overview/apoc.cypher/apoc.cypher.parallel2.adoc[apoc.cypher.parallel2 icon:book[]]

apoc.cypher.parallel2(fragment, `paramMap`, `keyList`) yield value - executes fragments in parallel batches through a list defined in `paramMap` with a key `keyList`
|label:procedure[]
|xref::overview/apoc.cypher/apoc.cypher.runFile.adoc[apoc.cypher.runFile icon:book[]]

apoc.cypher.runFile(file or url,[{statistics:true,timeout:10,parameters:{}}]) - runs each statement in the file, all semicolon separated - currently no schema operations
|label:procedure[]
|xref::overview/apoc.cypher/apoc.cypher.runFiles.adoc[apoc.cypher.runFiles icon:book[]]

apoc.cypher.runFiles([files or urls],[{statistics:true,timeout:10,parameters:{}}])) - runs each statement in the files, all semicolon separated
|label:procedure[]
|xref::overview/apoc.cypher/apoc.cypher.runSchemaFile.adoc[apoc.cypher.runSchemaFile icon:book[]]

apoc.cypher.runSchemaFile(file or url,[{statistics:true,timeout:10}]) - allows only schema operations, runs each schema statement in the file, all semicolon separated
|label:procedure[]
|xref::overview/apoc.cypher/apoc.cypher.runSchemaFiles.adoc[apoc.cypher.runSchemaFiles icon:book[]]

apoc.cypher.runSchemaFiles([files or urls],{statistics:true,timeout:10}) - allows only schema operations, runs each schema statement in the files, all semicolon separated
|label:procedure[]
|===

