////
This file is generated by DocsTest, so don't change it!
////

= apoc.meta.data.of
:description: This section contains reference documentation for the apoc.meta.data.of procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.meta.data.of(\{graph}, \{config})  - examines a subset of the graph to provide a tabular meta information

== Signature

[source]
----
apoc.meta.data.of(graph :: ANY?, config = {} :: MAP?) :: (label :: STRING?, property :: STRING?, count :: INTEGER?, unique :: BOOLEAN?, index :: BOOLEAN?, existence :: BOOLEAN?, type :: STRING?, array :: BOOLEAN?, sample :: LIST? OF ANY?, left :: INTEGER?, right :: INTEGER?, other :: LIST? OF STRING?, otherLabels :: LIST? OF STRING?, elementType :: STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|graph|ANY?|null
|config|MAP?|{}
|===

== Config Parameters
This procedure supports the following config parameters:

.Config parameters
[opts=header]
|===
| Name | Type | Default | Description
| sample | Long | 1000 | Number of nodes to skip, e.g. a sample of 1000 will read every 1000th node.
|===


== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|label|STRING?
|property|STRING?
|count|INTEGER?
|unique|BOOLEAN?
|index|BOOLEAN?
|existence|BOOLEAN?
|type|STRING?
|array|BOOLEAN?
|sample|LIST? OF ANY?
|left|INTEGER?
|right|INTEGER?
|other|LIST? OF STRING?
|otherLabels|LIST? OF STRING?
|elementType|STRING?
|===

[[usage-apoc.meta.data.of]]
== Usage Examples
include::partial$usage/apoc.meta.data.of.adoc[]

