////
This file is generated by DocsTest, so don't change it!
////

= apoc.meta
:description: This section contains reference documentation for the apoc.meta procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.meta/apoc.meta.data.adoc[apoc.meta.data icon:book[]]

apoc.meta.data(\{config})  - examines a subset of the graph to provide a tabular meta information
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.data.of.adoc[apoc.meta.data.of icon:book[]]

apoc.meta.data.of(\{graph}, \{config})  - examines a subset of the graph to provide a tabular meta information
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.graph.adoc[apoc.meta.graph icon:book[]]

apoc.meta.graph - examines the full graph to create the meta-graph
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.graph.of.adoc[apoc.meta.graph.of icon:book[]]

apoc.meta.graph.of(\{graph}, \{config})  - examines a subset of the graph to provide a graph meta information
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.graphSample.adoc[apoc.meta.graphSample icon:book[]]

apoc.meta.graphSample() - examines the database statistics to build the meta graph, very fast, might report extra relationships
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.nodeTypeProperties.adoc[apoc.meta.nodeTypeProperties icon:book[]]

apoc.meta.nodeTypeProperties()
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.relTypeProperties.adoc[apoc.meta.relTypeProperties icon:book[]]

apoc.meta.relTypeProperties()
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.schema.adoc[apoc.meta.schema icon:book[]]

apoc.meta.schema(\{config})  - examines a subset of the graph to provide a map-like meta information
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.stats.adoc[apoc.meta.stats icon:book[]]

apoc.meta.stats yield labelCount, relTypeCount, propertyKeyCount, nodeCount, relCount, labels, relTypes, stats \| returns the information stored in the transactional database statistics
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.subGraph.adoc[apoc.meta.subGraph icon:book[]]

apoc.meta.subGraph({labels:[labels],rels:[rel-types], excludes:[labels,rel-types]}) - examines a sample sub graph to create the meta-graph
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.cypher.isType.adoc[apoc.meta.cypher.isType icon:book[]]

apoc.meta.cypher.isType(value,type) - returns a row if type name matches none if not (INTEGER,FLOAT,STRING,BOOLEAN,RELATIONSHIP,NODE,PATH,NULL,MAP,LIST OF <TYPE>,POINT,DATE,DATE_TIME,LOCAL_TIME,LOCAL_DATE_TIME,TIME,DURATION)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.cypher.type.adoc[apoc.meta.cypher.type icon:book[]]

apoc.meta.cypher.type(value) - type name of a value (INTEGER,FLOAT,STRING,BOOLEAN,RELATIONSHIP,NODE,PATH,NULL,MAP,LIST OF <TYPE>,POINT,DATE,DATE_TIME,LOCAL_TIME,LOCAL_DATE_TIME,TIME,DURATION)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.cypher.types.adoc[apoc.meta.cypher.types icon:book[]]

apoc.meta.cypher.types(node-relationship-map)  - returns a map of keys to types
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.isType.adoc[apoc.meta.isType icon:book[]]

apoc.meta.isType(value,type) - returns a row if type name matches none if not (INTEGER,FLOAT,STRING,BOOLEAN,RELATIONSHIP,NODE,PATH,NULL,UNKNOWN,MAP,LIST)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.type.adoc[apoc.meta.type icon:book[]]

apoc.meta.type(value) - type name of a value (INTEGER,FLOAT,STRING,BOOLEAN,RELATIONSHIP,NODE,PATH,NULL,UNKNOWN,MAP,LIST)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.typeName.adoc[apoc.meta.typeName icon:book[]]

apoc.meta.typeName(value) - type name of a value (INTEGER,FLOAT,STRING,BOOLEAN,RELATIONSHIP,NODE,PATH,NULL,UNKNOWN,MAP,LIST)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.meta/apoc.meta.types.adoc[apoc.meta.types icon:book[]]

apoc.meta.types(node-relationship-map)  - returns a map of keys to types
|label:function[]
|label:apoc-core[]
|===

