[[export-csv]]
= Export to CSV

// tag::export.csv[]

`YIELD file, source, format, nodes, relationships, properties, time, rows, data`
[cols="1m,5"]
|===
| apoc.export.csv.query(query,file,config) | exports results from the Cypher statement as CSV to the provided file
| apoc.export.csv.all(file,config) | exports whole database as CSV to the provided file
| apoc.export.csv.data(nodes,rels,file,config) | exports given nodes and relationships as CSV to the provided file
| apoc.export.csv.graph(graph,file,config) | exports given graph object as CSV to the provided file
|===

If the file name is passed as `null` and the config `stream:true` the results are streamed back in the `data` column, e.g.

== Note:

For `apoc.export.csv.all/data/graph` nodes and relationships properties are ordered alphabetically, following this general structure:

`_id,_labels,<list_nodes_properties_naturally_sorted>,_start,_end,_type,<list_rel_properties_naturally_sorted>`, so for instance:

`_id,_labels,age,city,kids,male,name,street,_start,_end,_type,bar,foo`

The labels exported are ordered alphabetically.
The output of `labels()` function is not sorted, use it in combination with `apoc.coll.sort()`.

[source,cypher]
----
CALL apoc.export.csv.all(null, {stream:true,batchSize:100}) YIELD data RETURN data
----

// end::export.csv[]