////
This file is generated by DocsTest, so don't change it!
////

= apoc.graph
:description: This section contains reference documentation for the apoc.graph procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.graph/apoc.graph.from.adoc[apoc.graph.from icon:book[]]

apoc.graph.from(data,'name',\{properties}) \| creates a virtual graph object for later processing it tries its best to extract the graph information from the data you pass in
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.graph/apoc.graph.fromCypher.adoc[apoc.graph.fromCypher icon:book[]]

apoc.graph.fromCypher('kernelTransaction',\{params},'name',\{properties}) - creates a virtual graph object for later processing
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.graph/apoc.graph.fromDB.adoc[apoc.graph.fromDB icon:book[]]

apoc.graph.fromDB('name',\{properties}) - creates a virtual graph object for later processing
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.graph/apoc.graph.fromData.adoc[apoc.graph.fromData icon:book[]]

apoc.graph.fromData([nodes],[relationships],'name',\{properties}) \| creates a virtual graph object for later processing
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.graph/apoc.graph.fromDocument.adoc[apoc.graph.fromDocument icon:book[]]

apoc.graph.fromDocument(\{json}, \{config}) yield graph - transform JSON documents into graph structures
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.graph/apoc.graph.fromPath.adoc[apoc.graph.fromPath icon:book[]]

apoc.graph.fromPath(path,'name',\{properties}) - creates a virtual graph object for later processing
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.graph/apoc.graph.fromPaths.adoc[apoc.graph.fromPaths icon:book[]]

apoc.graph.fromPaths([paths],'name',\{properties}) - creates a virtual graph object for later processing
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.graph/apoc.graph.validateDocument.adoc[apoc.graph.validateDocument icon:book[]]

apoc.graph.validateDocument(\{json}, \{config}) yield row - validates the json, return the result of the validation
|label:procedure[]
|label:apoc-core[]
|===

