////
This file is generated by DocsTest, so don't change it!
////

= apoc.generate
:description: This section contains reference documentation for the apoc.generate procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.generate/apoc.generate.ba.adoc[apoc.generate.ba icon:book[]]

apoc.generate.ba(noNodes, edgesPerNode, label, type) - generates a random graph according to the Barabasi-Albert model
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.generate/apoc.generate.complete.adoc[apoc.generate.complete icon:book[]]

apoc.generate.complete(noNodes, label, type) - generates a random complete graph
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.generate/apoc.generate.er.adoc[apoc.generate.er icon:book[]]

apoc.generate.er(noNodes, noEdges, label, type) - generates a random graph according to the Erdos-Renyi model
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.generate/apoc.generate.simple.adoc[apoc.generate.simple icon:book[]]

apoc.generate.simple(degrees, label, type) - generates a simple random graph according to the given degree distribution
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.generate/apoc.generate.ws.adoc[apoc.generate.ws icon:book[]]

apoc.generate.ws(noNodes, degree, beta, label, type) - generates a random graph according to the Watts-Strogatz model
|label:procedure[]
|label:apoc-full[]
|===

