[[introduction]]
= Introduction
:description: This chapter provides an introduction to the APOC library, and instructions for installation and use.




ifdef::backend-html5[]
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/V1DTBjetIfk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
++++
endif::[]

Neo4j 3.x introduced the concept of user-defined procedures and functions.
Those are custom implementations of certain functionality, that can't be (easily) expressed in Cypher itself.
They are implemented in Java and can be easily deployed into your Neo4j instance, and then be called from Cypher directly.

The APOC library consists of a lot of procedures and functions to help with different tasks in areas like
data integration, graph algorithms or data conversion.

As of 5.0 APOC has been split into separate repositories, one being the main, officially supported, APOC Library. The
other belonging to APOC Extended. This documentation handles the extended part of APOC (around 150 procedures and functions).


[NOTE]
====
.APOC Name History

http://matrix.wikia.com/wiki/Apoc[Apoc^] was the technician and driver on board of the Nebuchadnezzar in the Matrix movie. He was killed by Cypher.

*APOC* was also the first bundled http://neo4j.com/blog/convenient-package-neo4j-apoc-0-1-released/[A Package Of Component^] for Neo4j in 2009.

*APOC* also stands for "Awesome Procedures On Cypher"
====

== APOC Editions - Core and Extended

Starting from Neo4j 4.1.1, there are two available versions of the APOC Library:

_APOC Core_ :: battle hardened procedures and functions that don't have external dependencies or require configuration. This is also the based of the functionality available in https://neo4j.com/aura[Neo4j AuraDB^] which lists the https://neo4j.com/docs/aura/current/getting-started/apoc/[available APOC surface in their docs^].
_APOC Extended_ :: contains additional procedures and functions, which is available when you self-host the database and add the apoc-extended jar.


A list of functions and procedures in _APOC Extended_ can be found in xref::overview/index.adoc[].

Starting from Neo4j 5.0.0, APOC core and extended are split into 2 separate repos, with only core being officially supported by Neo4j.