[[mongodb]]
= MongoDB
:description: This section describes procedures that can be used to interact with MongoDB.


[[mongodb-procedures]]
== Available Procedures

// tag::mongodb[]

[separator=¦,opts=header,cols="1,1m,1m,5"]
|===
include::example$generated-documentation/apoc.mongodb.csv[]
|===



[[mongodb-dependencies]]
== Install Dependencies

The `apoc.mongo.*` procedures have dependencies on a client library that is not included in the APOC Library.

To use them, copy these jars into the plugins directory:

* bson-3.4.2.jar
* mongo-java-driver-3.4.2.jar
* mongodb-driver-3.4.2.jar
* mongodb-driver-core-3.4.2.jar

You should be able to get them from https://mongodb.github.io/mongo-java-driver/[here], and https://mvnrepository.com/artifact/org.mongodb/bson/3.4.2[here (BSON)] (via Download)

Or you can get them locally from your gradle build of apoc.


[[mongodb-fields]]
== Field description

 - `uri`: TODO
 - `query`: query parameter map (only for `apoc.mongo.update` and `apoc.mongo.delete`)
 - `update`: update parameter map (only for `apoc.mongo.update`)
 - `documents`: the documents to insert (only for `apoc.mongo.insert`)
 - `config`: see below

[[mongodb-config]]
== Configuration parameters
The procedures support the following config parameters:

.Config parameters
[opts=header]
|===
| name | type | default | description
| minLevel | Long | -1 | the minimum number of hops in the traversal
|===


[[mongodb-examples]]
== Examples

[source,cypher]
----
CALL apoc.mongodb.first('mongodb://localhost:27017','test','test',{name:'testDocument'})
----

If you need automatic conversion of *unpackable* values then the cypher query will be:

[source,cypher]
----
CALL apoc.mongodb.first('mongodb://localhost:27017','test','test',{name:'testDocument'},true)
----

Following an example that could help to understand the behaviour of `extractReferences`, `compatibleValues` and `objectIdAsMap`:

Given the following collections:

```
// Product
...
{"_id": ObjectId("product1"), "name": "Product 1", "price": 100}
{"_id": ObjectId("product3"), "name": "Product 2", "price": 200}
{"_id": ObjectId("product3"), "name": "Product 3", "price": 300}
...
```

```
// Person
...
{"_id": ObjectId("person"), "name": "Andrea", "bought": [ObjectId("product1"), ObjectId("product3")]}
...
```

With the `extractReferences=true`, `compatibleValues=true` and `objectIdAsMap=false`:

```
{
  "_id": "person",
  "name": "Andrea",
  "bought": [
    {"_id": "product1", "name": "Product 1", "price": 100},
    {"_id": "product3", "name": "Product 3", "price": 300}
  ]
}
```

With the `extractReferences=true`, `compatibleValues=true` and `objectIdAsMap=true`:

```
{
  "_id": {
  	"timestamp": <...>,
	"machineIdentifier": <...>,
	"processIdentifier": <...>,
	"counter": <...>,
  },
  "name": "Andrea",
  "bought": [
    {
      "_id": {
	  	"timestamp": <...>,
		"machineIdentifier": <...>,
		"processIdentifier": <...>,
		"counter": <...>,
	  },
	  "name": "Product 1",
	  "price": 100
	},
    {
      "_id": {
	  	"timestamp": <...>,
		"machineIdentifier": <...>,
		"processIdentifier": <...>,
		"counter": <...>,
	  },
	  "name": "Product 3",
	  "price": 300
	},
  ]
}
```


With the `extractReferences=false`, `compatibleValues=false` and `objectIdAsMap=false`:

```
{
  "_id": "person",
  "name": "Andrea",
  "bought": ["product1", "product3"]
}
```


Given the following collection:

```
// Person
...
{"_id": ObjectId("person"), "name": ObjectId("97e193d7a9cc81b4027518b4"), "reg": BsonRegularExpression("foo*"), }
...
```

with the `extractReferences=false`, `compatibleValues=true` and `objectIdAsMap=false` and `useExtendedJson=true`,
and this query:

[source,cypher]
----
CALL apoc.mongodb.first('mongodb://localhost:27017','test','test',{name: {`$oid` : '97e193d7a9cc81b4027518b4' }}, true, false, false, true)
----

or this:

[source,cypher]
----
CALL apoc.mongodb.first('mongodb://localhost:27017','test','test',{reg: {`$regularExpression`:{`pattern`:'foo*',options:''}}}, true, false, false, true)
----

we receive the previous document.



== Dependencies

Copy these jars into the plugins directory:

* bson-3.4.2.jar
* mongo-java-driver-3.4.2.jar
* mongodb-driver-3.4.2.jar
* mongodb-driver-core-3.4.2.jar

You should be able to get them from https://mongodb.github.io/mongo-java-driver/[here], and https://mvnrepository.com/artifact/org.mongodb/bson/3.4.2[here (BSON)] (via Download)

Or you get them locally from your gradle build of apoc.

----
gradle copyRuntimeLibs
cp lib/mongodb*.jar lib/bson*.jar $NEO4J_HOME/plugins/
----



