[[mongodb]]
= MongoDB (Deprecated)
:description: This section describes procedures that can be used to interact with MongoDB.

[NOTE]
====
These procedures are deprecated in favor of xref::database-integration/mongo.adoc[apoc.mongo.* procedures] .
====


[[mongodb-procedures]]
== Available Procedures

// tag::mongodb[]

[separator=¦,opts=header,cols="5,1m,1m"]
|===
¦Qualified Name¦Type¦Release
include::example$generated-documentation/apoc.mongodb.count.adoc[]
include::example$generated-documentation/apoc.mongodb.delete.adoc[]
include::example$generated-documentation/apoc.mongodb.find.adoc[]
include::example$generated-documentation/apoc.mongodb.first.adoc[]
include::example$generated-documentation/apoc.mongodb.get.adoc[]
include::example$generated-documentation/apoc.mongodb.insert.adoc[]
include::example$generated-documentation/apoc.mongodb.update.adoc[]
|===


[[mongodb-dependencies]]
== Install Dependencies
include::partial$mongodb-dependencies.adoc[]

[[mongodb-fields]]
== Field description

 - `hostorkey`: the MongoDB host in the format `mongodb://<HOST_NAME>:<PORT>`
 or a url defined into the apoc config `apoc.mongodb.myInstance.url=mongodb://<HOST_NAME>:<PORT>`,
 which can be invoked by simply passing `myInstance`
 - `db`: the db name
 - `collection`: the collection name
 - `query`: query params
 - `projection`: projection params
 - `sort`: sort params
 - `compatibleValues` (false|true): converts MongoDB data types into Neo4j data types
 - `skip`: num of documents to skip
 - `limit`: num of documents to limit
 - `extractReferences` (false|true): if true and a field contains an `ObjectId` it will include the related document instead of the `ObjectId`
 - `objectIdAsMap` (true|false): extract the `ObjectId` as map
 - `documents`: the documents to insert
 - `update`: the updated params

[[mongodb-examples]]
== Examples

Following an example that could help to understand the behaviour of `extractReferences`, `compatibleValues` and `objectIdAsMap`:

Given the following collections:

```
// Product
...
{"_id": ObjectId("product1"), "name": "Product 1", "price": 100}
{"_id": ObjectId("product3"), "name": "Product 2", "price": 200}
{"_id": ObjectId("product3"), "name": "Product 3", "price": 300}
...
```

```
// Person
...
{"_id": ObjectId("person"), "name": "Andrea", "bought": [ObjectId("product1"), ObjectId("product3")]}
...
```

With the `extractReferences=true`, `compatibleValues=true` and `objectIdAsMap=false`:

```
{
  "_id": "person",
  "name": "Andrea",
  "bought": [
    {"_id": "product1", "name": "Product 1", "price": 100},
    {"_id": "product3", "name": "Product 3", "price": 300}
  ]
}
```

With the `extractReferences=true`, `compatibleValues=true` and `objectIdAsMap=true`:

```
{
  "_id": {
  	"timestamp": <...>,
	"machineIdentifier": <...>,
	"processIdentifier": <...>,
	"counter": <...>,
  },
  "name": "Andrea",
  "bought": [
    {
      "_id": {
	  	"timestamp": <...>,
		"machineIdentifier": <...>,
		"processIdentifier": <...>,
		"counter": <...>,
	  },
	  "name": "Product 1",
	  "price": 100
	},
    {
      "_id": {
	  	"timestamp": <...>,
		"machineIdentifier": <...>,
		"processIdentifier": <...>,
		"counter": <...>,
	  },
	  "name": "Product 3",
	  "price": 300
	},
  ]
}
```


With the `extractReferences=false`, `compatibleValues=false` and `objectIdAsMap=false`:

```
{
  "_id": "person",
  "name": "Andrea",
  "bought": ["product1", "product3"]
}
```




== Example

[source,cypher]
----
CALL apoc.mongodb.first('mongodb://localhost:27017','test','test',{name:'testDocument'})
----

If you need automatic conversion of *unpackable* values then the cypher query will be:

[source,cypher]
----
CALL apoc.mongodb.first('mongodb://localhost:27017','test','test',{name:'testDocument'},true)
----

// end::mongodb[]
