////
This file is generated by DocsTest, so don't change it!
////

= apoc.nodes
:description: This section contains reference documentation for the apoc.nodes procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.nodes/apoc.nodes.collapse.adoc[apoc.nodes.collapse icon:book[]]

apoc.nodes.collapse([nodes...],[{properties:'overwrite' or 'discard' or 'combine'}]) yield from, rel, to merge nodes onto first in list
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.nodes/apoc.nodes.delete.adoc[apoc.nodes.delete icon:book[]]

apoc.nodes.delete(node\|nodes\|id\|[ids]) - quickly delete all nodes with these ids
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.nodes/apoc.nodes.get.adoc[apoc.nodes.get icon:book[]]

apoc.nodes.get(node\|nodes\|id\|[ids]) - quickly returns all nodes with these ids
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.nodes/apoc.nodes.group.adoc[apoc.nodes.group icon:book[]]


|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.nodes/apoc.nodes.link.adoc[apoc.nodes.link icon:book[]]

apoc.nodes.link([nodes],'REL_TYPE', conf) - creates a linked list of nodes from first to last
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.nodes/apoc.nodes.rels.adoc[apoc.nodes.rels icon:book[]]

apoc.get.rels(rel\|id\|[ids]) - quickly returns all relationships with these ids
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.nodes/apoc.nodes.connected.adoc[apoc.nodes.connected icon:book[]]

apoc.nodes.connected(start, end, rel-direction-pattern) - returns true when the node is connected to the other node, optimized for dense nodes
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.nodes/apoc.nodes.isDense.adoc[apoc.nodes.isDense icon:book[]]

apoc.nodes.isDense(node) - returns true if it is a dense node
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.nodes/apoc.nodes.relationship.types.adoc[apoc.nodes.relationship.types icon:book[]]

apoc.nodes.relationship.types(node\|nodes\|id\|[ids], rel-direction-pattern) - returns a list of maps where each one has two fields: `node` which is the node subject of the analysis and `types` which is a list of distinct relationship types
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.nodes/apoc.nodes.relationships.exist.adoc[apoc.nodes.relationships.exist icon:book[]]

apoc.nodes.relationships.exist(node\|nodes\|id\|[ids], rel-direction-pattern) - returns a list of maps where each one has two fields: `node` which is the node subject of the analysis and `exists` which is a map with rel-pattern, boolean for the given relationship patterns
|label:function[]
|label:apoc-core[]
|===

