[[fingerprinting]]
= Fingerprinting
:description: This section describes procedures that can be used to create a hash over nodes, relationships or the whole graph.

The following functions calculate a hashsum over nodes, relationships or the entire graph.
It takes into account all properties, node labels and relationship types.

NOTE: The algorithm used for hashing may change between APOC versions.
It is therefore only possible to compare the hashing results of two entities/graphs from the same graph, or from different graphs using the *same* apoc version.

The hashsum of a graph first calculates the hashsum for each node.
The resulting hashsum list is ordered, and for each node the hashsum for all relationships and their end nodes are added.
Internal ids are not included in the hashsum.

It is also possible to supply a list of `propertyKeys` which should be ignored on all nodes.
This can be useful when storing properties, such as `created=timestamp()` that should be ignored.

[opts=header,cols="m,a"]
|===
| Function name | Description

| `apoc.hashing.fingerprint(object Any, excludedPropertyKeys [String])`
| Calculates a MD5 checksum over a node or a relationship (identical entities share the same checksum).
*Unsuitable for cryptographic use-cases.*

| `apoc.hashing.fingerprinting(object Any, config Map<String, Any>)`
| Calculates a MD5 checksum over a node or a relationship (identical entities share the same checksum).
Unlike `apoc.hashing.fingerprint()`, this function supports a number of config parameters.
*Unsuitable for cryptographic use-cases.*

| `apoc.hashing.fingerprintGraph(propertyExcludes [String])`
| Calculates a MD5 checksum over the full graph.
This function uses in-memory data structures.
*Unsuitable for cryptographic use-cases.*
|===

== Configuration parameters
include::partial$usage/config/apoc.hashing.fingerprinting.adoc[]

[NOTE]
====
It is not possible to define both allow and disallow lists for the same entity type.
Lists must consequently be either allowed or disallowed when setting the fingerprinting parameters for nodes, relationships, and maps.
====

== Fingerprinting strategy

In case the properties defined in the configuration are not present on the node and/or relationship, it is possible to define how the fingerprinting procedure proceeds:

* `EAGER`: includes all properties in the hashing if no allow/disallow lists are supplied.
* `LAZY`: excludes all properties in the hashing if no allow/disallow lists are supplied.