////
This file is generated by DocsTest, so don't change it!
////

= apoc.text
:description: This section contains reference documentation for the apoc.text procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.text/apoc.text.doubleMetaphone.adoc[apoc.text.doubleMetaphone icon:book[]]

apoc.text.doubleMetaphone(value) yield value - Compute the Double Metaphone phonetic encoding of all words of the text value which can be a single string or a list of strings
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.phonetic.adoc[apoc.text.phonetic icon:book[]]

apoc.text.phonetic(value) yield value - Compute the US_ENGLISH phonetic soundex encoding of all words of the text value which can be a single string or a list of strings
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.phoneticDelta.adoc[apoc.text.phoneticDelta icon:book[]]

apoc.text.phoneticDelta(text1, text2) yield phonetic1, phonetic2, delta - Compute the US_ENGLISH soundex character difference between two given strings
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.base64Decode.adoc[apoc.text.base64Decode icon:book[]]

apoc.text.base64Decode(text) YIELD value - Decode Base64 encoded string
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.base64Encode.adoc[apoc.text.base64Encode icon:book[]]

apoc.text.base64Encode(text) YIELD value - Encode a string with Base64
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.base64UrlDecode.adoc[apoc.text.base64UrlDecode icon:book[]]

apoc.text.base64UrlDecode(url) YIELD value - Decode Base64 encoded url
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.base64UrlEncode.adoc[apoc.text.base64UrlEncode icon:book[]]

apoc.text.base64UrlEncode(text) YIELD value - Encode a url with Base64
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.byteCount.adoc[apoc.text.byteCount icon:book[]]

apoc.text.byteCount(text,[charset]) - return size of text in bytes
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.bytes.adoc[apoc.text.bytes icon:book[]]

apoc.text.bytes(text,[charset]) - return bytes of the text
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.camelCase.adoc[apoc.text.camelCase icon:book[]]

apoc.text.camelCase(text) YIELD value - Convert a string to camelCase
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.capitalize.adoc[apoc.text.capitalize icon:book[]]

apoc.text.capitalize(text) YIELD value - capitalise the first letter of the word
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.capitalizeAll.adoc[apoc.text.capitalizeAll icon:book[]]

apoc.text.capitalizeAll(text) YIELD value - capitalise the first letter of every word in the text
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.charAt.adoc[apoc.text.charAt icon:book[]]

apoc.text.charAt(text, index) - the decimal value of the character at the given index
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.clean.adoc[apoc.text.clean icon:book[]]

apoc.text.clean(text) - strip the given string of everything except alpha numeric characters and convert it to lower case.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.code.adoc[apoc.text.code icon:book[]]

apoc.text.code(codepoint) - Returns the unicode character of the given codepoint
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.compareCleaned.adoc[apoc.text.compareCleaned icon:book[]]

apoc.text.compareCleaned(text1, text2) - compare the given strings stripped of everything except alpha numeric characters converted to lower case.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.decapitalize.adoc[apoc.text.decapitalize icon:book[]]

apoc.text.decapitalize(text) YIELD value - decapitalize the first letter of the word
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.decapitalizeAll.adoc[apoc.text.decapitalizeAll icon:book[]]

apoc.text.decapitalizeAll(text) YIELD value - decapitalize the first letter of all words
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.distance.adoc[apoc.text.distance icon:book[]]

apoc.text.distance(text1, text2) - compare the given strings with the Levenshtein distance algorithm.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.doubleMetaphone.adoc[apoc.text.doubleMetaphone icon:book[]]

apoc.text.doubleMetaphone(value) yield value - Compute the Double Metaphone phonetic encoding of all words of the text value
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.format.adoc[apoc.text.format icon:book[]]

apoc.text.format(text,[params],language) - sprintf format the string with the params given
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.fuzzyMatch.adoc[apoc.text.fuzzyMatch icon:book[]]

apoc.text.fuzzyMatch(text1, text2) - check if 2 words can be matched in a fuzzy way. Depending on the length of the String it will allow more characters that needs to be edited to match the second String.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.hammingDistance.adoc[apoc.text.hammingDistance icon:book[]]

apoc.text.hammingDistance(text1, text2) - compare the given strings with the Hamming distance algorithm.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.hexCharAt.adoc[apoc.text.hexCharAt icon:book[]]

apoc.text.hexCharAt(text, index) - the hex value string of the character at the given index
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.hexValue.adoc[apoc.text.hexValue icon:book[]]

apoc.text.hexValue(value) - the hex value string of the given number
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.indexOf.adoc[apoc.text.indexOf icon:book[]]

apoc.text.indexOf(text, lookup, from=0, to=-1==len) - find the first occurence of the lookup string in the text, from inclusive, to exclusive, -1 if not found, null if text is null.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.indexesOf.adoc[apoc.text.indexesOf icon:book[]]

apoc.text.indexesOf(text, lookup, from=0, to=-1==len) - finds all occurences of the lookup string in the text, return list, from inclusive, to exclusive, empty list if not found, null if text is null.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.jaroWinklerDistance.adoc[apoc.text.jaroWinklerDistance icon:book[]]

apoc.text.jaroWinklerDistance(text1, text2) - compare the given strings with the Jaro-Winkler distance algorithm.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.join.adoc[apoc.text.join icon:book[]]

apoc.text.join(['text1','text2',...], delimiter) - join the given strings with the given delimiter.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.levenshteinDistance.adoc[apoc.text.levenshteinDistance icon:book[]]

apoc.text.levenshteinDistance(text1, text2) - compare the given strings with the Levenshtein distance algorithm.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.levenshteinSimilarity.adoc[apoc.text.levenshteinSimilarity icon:book[]]

apoc.text.levenshteinSimilarity(text1, text2) - calculate the similarity (a value within 0 and 1) between two texts.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.lpad.adoc[apoc.text.lpad icon:book[]]

apoc.text.lpad(text,count,delim) YIELD value - left pad the string to the given width
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.phonetic.adoc[apoc.text.phonetic icon:book[]]

apoc.text.phonetic(text) yield value - Compute the US_ENGLISH phonetic soundex encoding of all words of the text
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.random.adoc[apoc.text.random icon:book[]]

apoc.text.random(length, valid) YIELD value - generate a random string
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.regexGroups.adoc[apoc.text.regexGroups icon:book[]]

apoc.text.regexGroups(text, regex) - return all matching groups of the regex on the given text.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.regreplace.adoc[apoc.text.regreplace icon:book[]]

apoc.text.regreplace(text, regex, replacement) - replace each substring of the given string that matches the given regular expression with the given replacement.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.repeat.adoc[apoc.text.repeat icon:book[]]

apoc.text.repeat(item, count) - string multiplication
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.replace.adoc[apoc.text.replace icon:book[]]

apoc.text.replace(text, regex, replacement) - replace each substring of the given string that matches the given regular expression with the given replacement.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.rpad.adoc[apoc.text.rpad icon:book[]]

apoc.text.rpad(text,count,delim) YIELD value - right pad the string to the given width
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.slug.adoc[apoc.text.slug icon:book[]]

apoc.text.slug(text, delim) - slug the text with the given delimiter
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.snakeCase.adoc[apoc.text.snakeCase icon:book[]]

apoc.text.snakeCase(text) YIELD value - Convert a string to snake-case
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.sorensenDiceSimilarity.adoc[apoc.text.sorensenDiceSimilarity icon:book[]]

apoc.text.sorensenDiceSimilarityWithLanguage(text1, text2, languageTag) - compare the given strings with the Sørensen–Dice coefficient formula, with the provided IETF language tag
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.split.adoc[apoc.text.split icon:book[]]

apoc.text.split(text, regex, limit) - splits the given text around matches of the given regex.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.swapCase.adoc[apoc.text.swapCase icon:book[]]

apoc.text.swapCase(text) YIELD value - Swap the case of a string
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.toCypher.adoc[apoc.text.toCypher icon:book[]]

apoc.text.toCypher(value, {skipKeys,keepKeys,skipValues,keepValues,skipNull,node,relationship,start,end}) \| tries it's best to convert the value to a cypher-property-string
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.toUpperCase.adoc[apoc.text.toUpperCase icon:book[]]

apoc.text.toUpperCase(text) YIELD value - Convert a string to UPPER_CASE
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.upperCamelCase.adoc[apoc.text.upperCamelCase icon:book[]]

apoc.text.upperCamelCase(text) YIELD value - Convert a string to camelCase
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.urldecode.adoc[apoc.text.urldecode icon:book[]]

apoc.text.urldecode(text) - return the urldecoded text
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.text/apoc.text.urlencode.adoc[apoc.text.urlencode icon:book[]]

apoc.text.urlencode(text) - return the urlencoded text
|label:function[]
|label:apoc-core[]
|===

