////
This file is generated by DocsTest, so don't change it!
////

= apoc.path.expandConfig
:description: This section contains reference documentation for the apoc.path.expandConfig procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.path.expandConfig(startNode <id>|Node|list, {minLevel,maxLevel,uniqueness,relationshipFilter,labelFilter,uniqueness:'RELATIONSHIP_PATH',bfs:true, filterStartNode:false, limit:-1, optional:false, endNodes:[], terminatorNodes:[], sequence, beginSequenceAtStart:true}) yield path - expand from start node following the given relationships from min to max-level adhering to the label filters.

== Signature

[source]
----
apoc.path.expandConfig(start :: ANY?, config :: MAP?) :: (path :: PATH?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|start|ANY?|null
|config|MAP?|null
|===

== Config parameters
include::partial$usage/config/apoc.path.expandConfig.adoc[]

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|path|PATH?
|===

[[usage-apoc.path.expandConfig]]
== Usage Examples
include::partial$usage/apoc.path.expandConfig.adoc[]

xref::graph-querying/expand-paths-config.adoc[More documentation of apoc.path.expandConfig,role=more information]

