////
This file is generated by DocsTest, so don't change it!
////

= apoc.path.subgraphAll
:description: This section contains reference documentation for the apoc.path.subgraphAll procedure.

label:procedure[]

[.emphasis]
apoc.path.subgraphAll(startNode <id>|Node|list, {maxLevel,relationshipFilter,labelFilter,bfs:true, filterStartNode:false, limit:-1, endNodes:[], terminatorNodes:[], sequence, beginSequenceAtStart:true}) yield nodes, relationships - expand the subgraph reachable from start node following relationships to max-level adhering to the label filters, and also return all relationships within the subgraph

== Signature

[source]
----
apoc.path.subgraphAll(start :: ANY?, config :: MAP?) :: (nodes :: LIST? OF NODE?, relationships :: LIST? OF RELATIONSHIP?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|start|ANY?|null
|config|MAP?|null
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|nodes|LIST? OF NODE?
|relationships|LIST? OF RELATIONSHIP?
|===

xref::graph-querying/expand-subgraph.adoc[More documentation of apoc.path.subgraphAll,role=more information]

