////
This file is generated by DocsTest, so don't change it!
////

= apoc.path
:description: This section contains reference documentation for the apoc.path procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.path/apoc.path.expand.adoc[apoc.path.expand icon:book[]]

apoc.path.expand(startNode <id>\|Node\|list, 'TYPE\|TYPE_OUT>\|<TYPE_IN', '+YesLabel\|-NoLabel', minLevel, maxLevel ) yield path - expand from start node following the given relationships from min to max-level adhering to the label filters
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.path/apoc.path.expandConfig.adoc[apoc.path.expandConfig icon:book[]]

apoc.path.expandConfig(startNode <id>\|Node\|list, {minLevel,maxLevel,uniqueness,relationshipFilter,labelFilter,uniqueness:'RELATIONSHIP_PATH',bfs:true, filterStartNode:false, limit:-1, optional:false, endNodes:[], terminatorNodes:[], sequence, beginSequenceAtStart:true}) yield path - expand from start node following the given relationships from min to max-level adhering to the label filters. 
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.path/apoc.path.spanningTree.adoc[apoc.path.spanningTree icon:book[]]

apoc.path.spanningTree(startNode <id>\|Node\|list, {maxLevel,relationshipFilter,labelFilter,bfs:true, filterStartNode:false, limit:-1, optional:false, endNodes:[], terminatorNodes:[], sequence, beginSequenceAtStart:true}) yield path - expand a spanning tree reachable from start node following relationships to max-level adhering to the label filters
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.path/apoc.path.subgraphAll.adoc[apoc.path.subgraphAll icon:book[]]

apoc.path.subgraphAll(startNode <id>\|Node\|list, {maxLevel,relationshipFilter,labelFilter,bfs:true, filterStartNode:false, limit:-1, endNodes:[], terminatorNodes:[], sequence, beginSequenceAtStart:true}) yield nodes, relationships - expand the subgraph reachable from start node following relationships to max-level adhering to the label filters, and also return all relationships within the subgraph
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.path/apoc.path.subgraphNodes.adoc[apoc.path.subgraphNodes icon:book[]]

apoc.path.subgraphNodes(startNode <id>\|Node\|list, {maxLevel,relationshipFilter,labelFilter,bfs:true, filterStartNode:false, limit:-1, optional:false, endNodes:[], terminatorNodes:[], sequence, beginSequenceAtStart:true}) yield node - expand the subgraph nodes reachable from start node following relationships to max-level adhering to the label filters
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.path/apoc.path.combine.adoc[apoc.path.combine icon:book[]]

apoc.path.combine(path1, path2) - combines the paths into one if the connecting node matches
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.path/apoc.path.create.adoc[apoc.path.create icon:book[]]

apoc.path.create(startNode,[rels]) - creates a path instance of the given elements
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.path/apoc.path.elements.adoc[apoc.path.elements icon:book[]]

apoc.path.elements(path) - returns a list of node-relationship-node-...
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.path/apoc.path.slice.adoc[apoc.path.slice icon:book[]]

apoc.path.slice(path, [offset], [length]) - creates a sub-path with the given offset and length
|label:function[]
|label:apoc-core[]
|===

