////
This file is generated by DocsTest, so don't change it!
////

= apoc.algo.dijkstraWithDefaultWeight
:description: This section contains reference documentation for the apoc.algo.dijkstraWithDefaultWeight procedure.

label:procedure[] label:apoc-core[] label:deprecated[]

[.emphasis]
apoc.algo.dijkstraWithDefaultWeight(startNode, endNode, 'KNOWS|<WORKS_WITH|IS_MANAGER_OF>', 'distance', 10) YIELD path, weight - run dijkstra with relationship property name as cost function and a default weight if the property does not exist

== Signature

[source]
----
apoc.algo.dijkstraWithDefaultWeight(startNode :: NODE?, endNode :: NODE?, relationshipTypesAndDirections :: STRING?, weightPropertyName :: STRING?, defaultWeight :: FLOAT?) :: (path :: PATH?, weight :: FLOAT?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|startNode|NODE?|null
|endNode|NODE?|null
|relationshipTypesAndDirections|STRING?|null
|weightPropertyName|STRING?|null
|defaultWeight|FLOAT?|null
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|path|PATH?
|weight|FLOAT?
|===

xref::algorithms/path-finding-procedures.adoc[More documentation of apoc.algo.dijkstraWithDefaultWeight,role=more information]

