////
This file is generated by DocsTest, so don't change it!
////

= apoc.create
:description: This section contains reference documentation for the apoc.create procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.create/apoc.create.addLabels.adoc[apoc.create.addLabels icon:book[]]

apoc.create.addLabels( [node,id,ids,nodes], ['Label',...]) - adds the given labels to the node or nodes
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.node.adoc[apoc.create.node icon:book[]]

apoc.create.node(['Label'], {key:value,...}) - create node with dynamic labels
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.nodes.adoc[apoc.create.nodes icon:book[]]

apoc.create.nodes(['Label'], [{key:value,...}]) create multiple nodes with dynamic labels
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.relationship.adoc[apoc.create.relationship icon:book[]]

apoc.create.relationship(person1,'KNOWS',{key:value,...}, person2) create relationship with dynamic rel-type
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.removeLabels.adoc[apoc.create.removeLabels icon:book[]]

apoc.create.removeLabels( [node,id,ids,nodes], ['Label',...]) - removes the given labels from the node or nodes
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.removeProperties.adoc[apoc.create.removeProperties icon:book[]]

apoc.create.removeProperties( [node,id,ids,nodes], [keys]) - removes the given properties from the nodes(s)
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.removeRelProperties.adoc[apoc.create.removeRelProperties icon:book[]]

apoc.create.removeRelProperties( [rel,id,ids,rels], [keys]) - removes the given properties from the relationship(s)
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.setLabels.adoc[apoc.create.setLabels icon:book[]]

apoc.create.setLabels( [node,id,ids,nodes], ['Label',...]) - sets the given labels, non matching labels are removed on the node or nodes
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.setProperties.adoc[apoc.create.setProperties icon:book[]]

apoc.create.setProperties( [node,id,ids,nodes], [keys], [values]) - sets the given properties on the nodes(s)
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.setProperty.adoc[apoc.create.setProperty icon:book[]]

apoc.create.setProperty( [node,id,ids,nodes], key, value) - sets the given property on the node(s)
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.setRelProperties.adoc[apoc.create.setRelProperties icon:book[]]

apoc.create.setRelProperties( [rel,id,ids,rels], [keys], [values]) - sets the given properties on the relationship(s)
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.setRelProperty.adoc[apoc.create.setRelProperty icon:book[]]

apoc.create.setRelProperty( [rel,id,ids,rels], key, value) - sets the given property on the relationship(s)
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.uuids.adoc[apoc.create.uuids icon:book[]]

apoc.create.uuids(count) yield uuid - creates 'count' UUIDs 
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.vNode.adoc[apoc.create.vNode icon:book[]]

apoc.create.vNode(['Label'], {key:value,...}) returns a virtual node
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.vNodes.adoc[apoc.create.vNodes icon:book[]]

apoc.create.vNodes(['Label'], [{key:value,...}]) returns virtual nodes
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.vPath.adoc[apoc.create.vPath icon:book[]]

apoc.create.vPath
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.vPaths.adoc[apoc.create.vPaths icon:book[]]

apoc.create.vPaths
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.vPattern.adoc[apoc.create.vPattern icon:book[]]

apoc.create.vPattern({_labels:['LabelA'],key:value},'KNOWS',{key:value,...}, {_labels:['LabelB'],key:value}) returns a virtual pattern
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.vPatternFull.adoc[apoc.create.vPatternFull icon:book[]]

apoc.create.vPatternFull(['LabelA'],{key:value},'KNOWS',{key:value,...},['LabelB'],{key:value}) returns a virtual pattern
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.vRelationship.adoc[apoc.create.vRelationship icon:book[]]

apoc.create.vRelationship(nodeFrom,'KNOWS',{key:value,...}, nodeTo) returns a virtual relationship
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.virtualPath.adoc[apoc.create.virtualPath icon:book[]]

apoc.create.virtualPath(['LabelA'],{key:value},'KNOWS',{key:value,...},['LabelB'],{key:value}) returns a virtual path of nodes joined by a relationship and the associated properties
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.uuid.adoc[apoc.create.uuid icon:book[]]

apoc.create.uuid() - creates an UUID
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.vNode.adoc[apoc.create.vNode icon:book[]]

apoc.create.vNode(['Label'], {key:value,...}) returns a virtual node
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.vRelationship.adoc[apoc.create.vRelationship icon:book[]]

apoc.create.vRelationship(nodeFrom,'KNOWS',{key:value,...}, nodeTo) returns a virtual relationship
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.create/apoc.create.virtual.fromNode.adoc[apoc.create.virtual.fromNode icon:book[]]

apoc.create.virtual.fromNode(node, [propertyNames]) returns a virtual node built from an existing node with only the requested properties
|label:function[]
|label:apoc-core[]
|===

