////
This file is generated by DocsTest, so don't change it!
////

= apoc.util
:description: This section contains reference documentation for the apoc.util procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.util/apoc.util.sleep.adoc[apoc.util.sleep icon:book[]]

apoc.util.sleep(<duration>) \| sleeps for <duration> millis, transaction termination is honored
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.util/apoc.util.validate.adoc[apoc.util.validate icon:book[]]

apoc.util.validate(predicate, message, params) \| if the predicate yields to true raise an exception
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.util/apoc.util.compress.adoc[apoc.util.compress icon:book[]]

apoc.util.compress(string, \{config}) \| return a compressed byte[] in various format from a string
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.util/apoc.util.decompress.adoc[apoc.util.decompress icon:book[]]

apoc.util.decompress(compressed, \{config}) \| return a string from a compressed byte[] in various format
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.util/apoc.util.md5.adoc[apoc.util.md5 icon:book[]]

apoc.util.md5([values]) \| computes the md5 of the concatenation of all string values of the list
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.util/apoc.util.sha1.adoc[apoc.util.sha1 icon:book[]]

apoc.util.sha1([values]) \| computes the sha1 of the concatenation of all string values of the list
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.util/apoc.util.sha256.adoc[apoc.util.sha256 icon:book[]]

apoc.util.sha256([values]) \| computes the sha256 of the concatenation of all string values of the list
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.util/apoc.util.sha384.adoc[apoc.util.sha384 icon:book[]]

apoc.util.sha384([values]) \| computes the sha384 of the concatenation of all string values of the list
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.util/apoc.util.sha512.adoc[apoc.util.sha512 icon:book[]]

apoc.util.sha512([values]) \| computes the sha512 of the concatenation of all string values of the list
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.util/apoc.util.validatePredicate.adoc[apoc.util.validatePredicate icon:book[]]

apoc.util.validatePredicate(predicate, message, params) \| if the predicate yields to true raise an exception else returns true, for use inside WHERE subclauses
|label:function[]
|label:apoc-core[]
|===

