////
This file is generated by DocsTest, so don't change it!
////

= apoc.search
:description: This section contains reference documentation for the apoc.search procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.search/apoc.search.multiSearchReduced.adoc[apoc.search.multiSearchReduced icon:book[]]

Do a parallel search over multiple indexes returning a reduced representation of the nodes found: node id, labels and the searched properties. apoc.search.multiSearchReduced( map of label and properties which will be searched upon, operator: EXACT \| CONTAINS \| STARTS WITH \| ENDS WITH, searchValue ). Multiple search results for the same node are merged into one record.
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.search/apoc.search.node.adoc[apoc.search.node icon:book[]]

Do a parallel search over multiple indexes returning nodes. usage apoc.search.node( map of label and properties which will be searched upon, operator: EXACT \| CONTAINS \| STARTS WITH \| ENDS WITH, searchValue ) returns all the DISTINCT Nodes found in the different searches.
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.search/apoc.search.nodeAll.adoc[apoc.search.nodeAll icon:book[]]

Do a parallel search over multiple indexes returning nodes. usage apoc.search.nodeAll( map of label and properties which will be searched upon, operator: EXACT \| CONTAINS \| STARTS WITH \| ENDS WITH, searchValue ) returns all the Nodes found in the different searches.
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.search/apoc.search.nodeAllReduced.adoc[apoc.search.nodeAllReduced icon:book[]]

Do a parallel search over multiple indexes returning a reduced representation of the nodes found: node id, labels and the searched property. apoc.search.nodeShortAll( map of label and properties which will be searched upon, operator: EXACT / CONTAINS / STARTS WITH \| ENDS WITH / = / <> / < / > ..., value ). All 'hits' are returned.
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.search/apoc.search.nodeReduced.adoc[apoc.search.nodeReduced icon:book[]]

Do a parallel search over multiple indexes returning a reduced representation of the nodes found: node id, labels and the searched properties. apoc.search.nodeReduced( map of label and properties which will be searched upon, operator: EXACT \| CONTAINS \| STARTS WITH \| ENDS WITH, searchValue ). Multiple search results for the same node are merged into one record.
|label:procedure[]
|label:apoc-core[]
|===

