////
This file is generated by DocsTest, so don't change it!
////

= apoc.load.directory.async.add
:description: This section contains reference documentation for the apoc.load.directory.async.add procedure.

label:procedure[] label:apoc-full[]

[.emphasis]
This procedure adds or replaces a folder listener with a specific name and returns a list of all `apoc.load.directory.async` listeners defined.
The trigger will track any changes of the files matching the given pattern. When triggered, it executes the specified query.
It is possible to specify the event type in the config.

== Signature
[source]
----
apoc.load.directory.async.add(name :: STRING?, cypher :: STRING?, pattern = * :: STRING?, urlDir =  :: STRING?, config = {} :: MAP?) :: (name :: STRING?, status :: STRING?, pattern :: STRING?, cypher :: STRING?, urlDir :: STRING?, config :: MAP?, error :: STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Mandatory | Description
| name | STRING? | yes | The name assigned to the trigger. If the name already exists, the existing trigger will be overwritten.
| cypher | STRING?| yes | The Cypher query executed when the trigger is activated.
| pattern| STRING?| no | The pattern describing the files that should be considered by the trigger. The pattern supports '?' and '*' to represent single or multiple wildcard characters, see https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/filefilter/WildcardFileFilter.html[WildcardFileFilter - Apache Commons IO] for more information.
Default value: *
| urlDir| STRING? | no | The directory watched for changes. Default value: empty String, which will observe the `import` directory
| config| MAP? | no | Additional configuration. Default value: {}
|===

The Cypher query can have the following parameters giving additional trigger context:

* $fileName: the name of the file which triggered the event
* $filePath: the absolute path of the file which triggered the event if `apoc.import.file.use_neo4j_config=false`, otherwise the relative path starting from `$IMPORT_DIR`
* $fileDirectory: the absolute path directory of the file which triggered the event if `apoc.import.file.use_neo4j_config=false`, otherwise the relative path starting from `$IMPORT_DIR`
* $listenEventType: the triggered event ("CREATE", "DELETE" or "MODIFY"). The event "CREATE" happens when a file is inserted in the folder,
"DELETE" when a file is removed from the folder and "MODIFY" when a file in the folder is changed.


[NOTE]
If a file is renamed, it will trigger 2 events, first "DELETE" and then "CREATE".

== Config parameters
include::partial$usage/config/apoc.load.directory.async.add.adoc[]

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|name|STRING?
|status|STRING?
|pattern|STRING?
|cypher|STRING?
|urlDir|STRING?
|config|MAP?
|error|STRING?
|===

[[usage-apoc.load.directory.async.add]]
== Usage Examples
include::partial$usage/apoc.load.directory.async.adoc[]

