////
This file is generated by DocsTest, so don't change it!
////

= apoc.load
:description: This section contains reference documentation for the apoc.load procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.load/apoc.load.csv.adoc[apoc.load.csv icon:book[]]

apoc.load.csv('url',\{config}) YIELD lineNo, list, map - load CSV from URL as stream of values,
 config contains any of: {skip:1,limit:5,header:false,sep:'TAB',ignore:['tmp'],nullValues:['na'],arraySep:';',mapping:{years:{type:'int',arraySep:'-',array:false,name:'age',ignore:false}}
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.load/apoc.load.csvParams.adoc[apoc.load.csvParams icon:book[]]

apoc.load.csvParams('url', {httpHeader: value}, payload, \{config}) YIELD lineNo, list, map - load from CSV URL (e.g. web-api) while sending headers / payload to load CSV from URL as stream of values,
 config contains any of: {skip:1,limit:5,header:false,sep:'TAB',ignore:['tmp'],nullValues:['na'],arraySep:';',mapping:{years:{type:'int',arraySep:'-',array:false,name:'age',ignore:false}}
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.load/apoc.load.directory.adoc[apoc.load.directory icon:book[]]

apoc.load.directory('pattern', 'urlDir', \{config}) YIELD value - Loads list of all files in folder specified by urlDir or in import folder if urlDir string is empty or not specified
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.load/apoc.load.driver.adoc[apoc.load.driver icon:book[]]

apoc.load.driver('org.apache.derby.jdbc.EmbeddedDriver') register JDBC driver of source database
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.load/apoc.load.html.adoc[apoc.load.html icon:book[]]

apoc.load.html('url',{name: jquery, name2: jquery}, config) YIELD value - Load Html page and return the result as a Map
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.load/apoc.load.jdbc.adoc[apoc.load.jdbc icon:book[]]

apoc.load.jdbc('key or url','table or statement', params, config) YIELD row - load from relational database, from a full table or a sql statement
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.load/apoc.load.jdbcParams.adoc[apoc.load.jdbcParams icon:book[]]

deprecated - please use: apoc.load.jdbc('key or url','',[params]) YIELD row - load from relational database, from a sql statement with parameters
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.load/apoc.load.jdbcUpdate.adoc[apoc.load.jdbcUpdate icon:book[]]

apoc.load.jdbcUpdate('key or url','statement',[params],config) YIELD row - update relational database, from a SQL statement with optional parameters
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.load/apoc.load.json.adoc[apoc.load.json icon:book[]]

apoc.load.json('url',path, config) YIELD value -  import JSON as stream of values if the JSON was an array or a single value if it was a map
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.load/apoc.load.jsonArray.adoc[apoc.load.jsonArray icon:book[]]

apoc.load.jsonArray('url') YIELD value - load array from JSON URL (e.g. web-api) to import JSON as stream of values
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.load/apoc.load.jsonParams.adoc[apoc.load.jsonParams icon:book[]]

apoc.load.jsonParams('url',{header:value},payload, config) YIELD value - load from JSON URL (e.g. web-api) while sending headers / payload to import JSON as stream of values if the JSON was an array or a single value if it was a map
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.load/apoc.load.ldap.adoc[apoc.load.ldap icon:book[]]

apoc.load.ldap("key" or \{connectionMap},\{searchMap}) Load entries from an ldap source (yield entry)
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.load/apoc.load.xls.adoc[apoc.load.xls icon:book[]]

apoc.load.xls('url','selector',\{config}) YIELD lineNo, list, map - load XLS fom URL as stream of row values,
 config contains any of: {skip:1,limit:5,header:false,ignore:['tmp'],arraySep:';',mapping:{years:{type:'int',arraySep:'-',array:false,name:'age',ignore:false, dateFormat:'iso_date', dateParse:['dd-MM-yyyy']}}
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.load/apoc.load.xml.adoc[apoc.load.xml icon:book[]]

apoc.load.xml('http://example.com/test.xml', 'xPath',config, false) YIELD value as doc CREATE (p:Person) SET p.name = doc.name - load from XML URL (e.g. web-api) to import XML as single nested map with attributes and _type, _text and _childrenx fields.
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.load/apoc.load.xmlSimple.adoc[apoc.load.xmlSimple icon:book[]]

apoc.load.xmlSimple('http://example.com/test.xml') YIELD value as doc CREATE (p:Person) SET p.name = doc.name - load from XML URL (e.g. web-api) to import XML as single nested map with attributes and _type, _text and _children fields. This method does intentionally not work with XML mixed content.
|label:procedure[]
|label:apoc-core[]
|===

