////
This file is generated by DocsTest, so don't change it!
////

= apoc.load
:description: This section contains reference documentation for the apoc.load procedures.

[.procedures, opts=header, cols='5a,1a']
|===
| Qualified Name | Type
|xref::overview/apoc.load/apoc.load.csv.adoc[apoc.load.csv icon:book[]]

apoc.load.csv('urlOrBinary',\{config}) YIELD lineNo, list, map - load CSV from URL as stream of values,
 config contains any of: {skip:1,limit:5,header:false,sep:'TAB',ignore:['tmp'],nullValues:['na'],arraySep:';',mapping:{years:{type:'int',arraySep:'-',array:false,name:'age',ignore:false}}
|label:procedure[]
|xref::overview/apoc.load/apoc.load.csvParams.adoc[apoc.load.csvParams icon:book[]]

apoc.load.csvParams('urlOrBinary', {httpHeader: value}, payload, \{config}) YIELD lineNo, list, map - load from CSV URL (e.g. web-api) while sending headers / payload to load CSV from URL as stream of values,
 config contains any of: {skip:1,limit:5,header:false,sep:'TAB',ignore:['tmp'],nullValues:['na'],arraySep:';',mapping:{years:{type:'int',arraySep:'-',array:false,name:'age',ignore:false}}
|label:procedure[]
|xref::overview/apoc.load/apoc.load.directory.adoc[apoc.load.directory icon:book[]]

apoc.load.directory('pattern', 'urlDir', \{config}) YIELD value - Loads list of all files in the folder specified by the parameter urlDir satisfying the given pattern. If the parameter urlDir is not specified or empty, the files of the import folder are loaded instead.
|label:procedure[]
|xref::overview/apoc.load/apoc.load.directory.async.add.adoc[apoc.load.directory.async.add icon:book[]]

apoc.load.directory.async.add(name, cypher, pattern, urlDir, {}) YIELD name, status, pattern, cypher, urlDir, config, error - Adds or replaces a folder listener with a specific name, which is triggered for all files with the given pattern and executes the specified Cypher query when triggered. Returns a list of all listeners. It is possible to specify the event type in the config parameter.
|label:procedure[]
|xref::overview/apoc.load/apoc.load.directory.async.list.adoc[apoc.load.directory.async.list icon:book[]]

apoc.load.directory.async.list() YIELD name, status, pattern, cypher, urlDir, config, error - Lists all folder listeners
|label:procedure[]
|xref::overview/apoc.load/apoc.load.directory.async.remove.adoc[apoc.load.directory.async.remove icon:book[]]

apoc.load.directory.async.remove(name) YIELD name, status, pattern, cypher, urlDir, config, error - Removes a folder listener by name and returns all remaining listeners, if any
|label:procedure[]
|xref::overview/apoc.load/apoc.load.directory.async.removeAll.adoc[apoc.load.directory.async.removeAll icon:book[]]

apoc.load.directory.async.removeAll() - Removes all folder listeners
|label:procedure[]
|xref::overview/apoc.load/apoc.load.driver.adoc[apoc.load.driver icon:book[]]

apoc.load.driver('org.apache.derby.jdbc.EmbeddedDriver') register JDBC driver of source database
|label:procedure[]
|xref::overview/apoc.load/apoc.load.html.adoc[apoc.load.html icon:book[]]

apoc.load.html('url',{name: jquery, name2: jquery}, config) YIELD value - Load Html page and return the result as a Map
|label:procedure[]
|xref::overview/apoc.load/apoc.load.htmlPlainText.adoc[apoc.load.htmlPlainText icon:book[]]

apoc.load.htmlPlainText('urlOrHtml',{name: jquery, name2: jquery}, config) YIELD value - Load Html page and return the result as a Map
|label:procedure[]
|xref::overview/apoc.load/apoc.load.jdbc.adoc[apoc.load.jdbc icon:book[]]

apoc.load.jdbc('key or url','table or statement', params, config) YIELD row - load from relational database, from a full table or a sql statement
|label:procedure[]
|xref::overview/apoc.load/apoc.load.jdbcParams.adoc[apoc.load.jdbcParams icon:book[]]

deprecated - please use: apoc.load.jdbc('key or url','',[params]) YIELD row - load from relational database, from a sql statement with parameters
|label:procedure[]
|xref::overview/apoc.load/apoc.load.jdbcUpdate.adoc[apoc.load.jdbcUpdate icon:book[]]

apoc.load.jdbcUpdate('key or url','statement',[params],config) YIELD row - update relational database, from a SQL statement with optional parameters
|label:procedure[]
|xref::overview/apoc.load/apoc.load.ldap.adoc[apoc.load.ldap icon:book[]]

apoc.load.ldap("key" or \{connectionMap},\{searchMap}) Load entries from an ldap source (yield entry)
|label:procedure[]
|xref::overview/apoc.load/apoc.load.xls.adoc[apoc.load.xls icon:book[]]

apoc.load.xls('url','selector',\{config}) YIELD lineNo, list, map - load XLS fom URL as stream of row values,
 config contains any of: {skip:1,limit:5,header:false,ignore:['tmp'],arraySep:';',mapping:{years:{type:'int',arraySep:'-',array:false,name:'age',ignore:false, dateFormat:'iso_date', dateParse:['dd-MM-yyyy']}}
|label:procedure[]
|===

