////
This file is generated by DocsTest, so don't change it!
////

= apoc.export.cypherData
:description: This section contains reference documentation for the apoc.export.cypherData procedure.

label:procedure[] label:apoc-core[] label:deprecated[]

[.emphasis]
apoc.export.cypherData(nodes,rels,file,config) - exports given nodes and relationships incl. indexes as cypher statements to the provided file

== Signature

[source]
----
apoc.export.cypherData(nodes :: LIST? OF NODE?, rels :: LIST? OF RELATIONSHIP?, file :: STRING?, config :: MAP?) :: (file :: STRING?, batches :: INTEGER?, source :: STRING?, format :: STRING?, nodes :: INTEGER?, relationships :: INTEGER?, properties :: INTEGER?, time :: INTEGER?, rows :: INTEGER?, batchSize :: INTEGER?, cypherStatements :: STRING?, nodeStatements :: STRING?, relationshipStatements :: STRING?, schemaStatements :: STRING?, cleanupStatements :: STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|nodes|LIST? OF NODE?|null
|rels|LIST? OF RELATIONSHIP?|null
|file|STRING?|null
|config|MAP?|null
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|file|STRING?
|batches|INTEGER?
|source|STRING?
|format|STRING?
|nodes|INTEGER?
|relationships|INTEGER?
|properties|INTEGER?
|time|INTEGER?
|rows|INTEGER?
|batchSize|INTEGER?
|cypherStatements|STRING?
|nodeStatements|STRING?
|relationshipStatements|STRING?
|schemaStatements|STRING?
|cleanupStatements|STRING?
|===

xref::export/cypher.adoc[More documentation of apoc.export.cypherData,role=more information]

