////
This file is generated by DocsTest, so don't change it!
////

= apoc.export.cypherQuery
:description: This section contains reference documentation for the apoc.export.cypherQuery procedure.

label:procedure[] label:apoc-core[] label:deprecated[]

[.emphasis]
apoc.export.cypherQuery(query,file,config) - exports nodes and relationships from the cypher kernelTransaction incl. indexes as cypher statements to the provided file

== Signature

[source]
----
apoc.export.cypherQuery(query :: STRING?, file :: STRING?, config :: MAP?) :: (file :: STRING?, batches :: INTEGER?, source :: STRING?, format :: STRING?, nodes :: INTEGER?, relationships :: INTEGER?, properties :: INTEGER?, time :: INTEGER?, rows :: INTEGER?, batchSize :: INTEGER?, cypherStatements :: STRING?, nodeStatements :: STRING?, relationshipStatements :: STRING?, schemaStatements :: STRING?, cleanupStatements :: STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|query|STRING?|null
|file|STRING?|null
|config|MAP?|null
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|file|STRING?
|batches|INTEGER?
|source|STRING?
|format|STRING?
|nodes|INTEGER?
|relationships|INTEGER?
|properties|INTEGER?
|time|INTEGER?
|rows|INTEGER?
|batchSize|INTEGER?
|cypherStatements|STRING?
|nodeStatements|STRING?
|relationshipStatements|STRING?
|schemaStatements|STRING?
|cleanupStatements|STRING?
|===

xref::export/cypher.adoc[More documentation of apoc.export.cypherQuery,role=more information]

