= apoc.export.arrow.all
:description: This section contains reference documentation for the apoc.export.arrow.all procedure.

label:procedure[]

[.emphasis]
`apoc.export.arrow.all(file STRING, config MAP<STRING, ANY>)` - exports the full database as an arrow file.

[NOTE]
====
:page-custom-canonical: https://neo4j.com/docs/apoc/current/overview/apoc.export/apoc.export.arrow.all/
It is considered unsafe to run this procedure using multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

== Signature

[source]
----
apoc.export.arrow.all(file :: STRING, config = {} :: MAP) :: (file :: STRING, source :: STRING, format :: STRING, nodes :: INTEGER, relationships :: INTEGER, properties :: INTEGER, time :: INTEGER, rows :: INTEGER, batchSize :: INTEGER, batches :: INTEGER, done :: BOOLEAN, data :: ANY)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default
|file|STRING|null
|config|MAP|null
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type
|file|STRING
|source|STRING
|format|STRING
|nodes|INTEGER
|relationships|INTEGER
|properties|INTEGER
|time|INTEGER
|rows|INTEGER
|batchSize|INTEGER
|batches|INTEGER
|done|BOOLEAN
|data|STRING
|===

== Config parameters
include::partial$usage/config/apoc.export.arrow.all.adoc[]

[[usage-apoc.export.arrow.all]]
== Usage Examples
include::partial$usage/apoc.export.arrow.all.adoc[]

xref::export/arrow.adoc[More documentation of apoc.export.arrow.all,role=more information]