////
This file is generated by DocsTest, so don't change it!
////

= apoc.export.cypher.query
:description: This section contains reference documentation for the apoc.export.cypher.query procedure.

[abstract]
--
{description}
--

++++
<div style='display:flex'>
<div class='paragraph type procedure'><p>Procedure</p></div>
<div class='paragraph release core' style='margin-left:10px;'><p>APOC Core</p></div>
</div>
++++

apoc.export.cypher.query(query,file,config) - exports nodes and relationships from the cypher statement incl. indexes as cypher statements to the provided file

== Signature

[source]
----
apoc.export.cypher.query(query :: STRING?, file =  :: STRING?, config = {} :: MAP?) :: (file :: STRING?, batches :: INTEGER?, source :: STRING?, format :: STRING?, nodes :: INTEGER?, relationships :: INTEGER?, properties :: INTEGER?, time :: INTEGER?, rows :: INTEGER?, batchSize :: INTEGER?, cypherStatements :: STRING?, nodeStatements :: STRING?, relationshipStatements :: STRING?, schemaStatements :: STRING?, cleanupStatements :: STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|query|STRING?|null
|file|STRING?|
|config|MAP?|{}
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|file|STRING?
|batches|INTEGER?
|source|STRING?
|format|STRING?
|nodes|INTEGER?
|relationships|INTEGER?
|properties|INTEGER?
|time|INTEGER?
|rows|INTEGER?
|batchSize|INTEGER?
|cypherStatements|STRING?
|nodeStatements|STRING?
|relationshipStatements|STRING?
|schemaStatements|STRING?
|cleanupStatements|STRING?
|===

xref::export/cypher.adoc[More documentation of apoc.export.cypher.query,role=more information]

