////
This file is generated by DocsTest, so don't change it!
////

= apoc.export.cypher.graph
:description: This section contains reference documentation for the apoc.export.cypher.graph procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.export.cypher.graph(graph,file,config) - exports given graph object incl. indexes as cypher statements to the provided file

== Signature

[source]
----
apoc.export.cypher.graph(graph :: MAP?, file =  :: STRING?, config = {} :: MAP?) :: (file :: STRING?, batches :: INTEGER?, source :: STRING?, format :: STRING?, nodes :: INTEGER?, relationships :: INTEGER?, properties :: INTEGER?, time :: INTEGER?, rows :: INTEGER?, batchSize :: INTEGER?, cypherStatements :: STRING?, nodeStatements :: STRING?, relationshipStatements :: STRING?, schemaStatements :: STRING?, cleanupStatements :: STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|graph|MAP?|null
|file|STRING?|
|config|MAP?|{}
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|file|STRING?
|batches|INTEGER?
|source|STRING?
|format|STRING?
|nodes|INTEGER?
|relationships|INTEGER?
|properties|INTEGER?
|time|INTEGER?
|rows|INTEGER?
|batchSize|INTEGER?
|cypherStatements|STRING?
|nodeStatements|STRING?
|relationshipStatements|STRING?
|schemaStatements|STRING?
|cleanupStatements|STRING?
|===

[[usage-apoc.export.cypher.graph]]
== Usage Examples
include::partial$usage/apoc.export.cypher.graph.adoc[]

xref::export/cypher.adoc[More documentation of apoc.export.cypher.graph,role=more information]

