////
This file is generated by DocsTest, so don't change it!
////

= apoc.export
:description: This section contains reference documentation for the apoc.export procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.export/apoc.export.cypherAll.adoc[apoc.export.cypherAll icon:book[]]

apoc.export.cypherAll(file,config) - exports whole database incl. indexes as cypher statements to the provided file|label:procedure[]
|label:apoc-core[]

|xref::overview/apoc.export/apoc.export.cypherData.adoc[apoc.export.cypherData icon:book[]]

apoc.export.cypherData(nodes,rels,file,config) - exports given nodes and relationships incl. indexes as cypher statements to the provided file|label:procedure[]
|label:apoc-core[]

|xref::overview/apoc.export/apoc.export.cypherGraph.adoc[apoc.export.cypherGraph icon:book[]]

apoc.export.cypherGraph(graph,file,config) - exports given graph object incl. indexes as cypher statements to the provided file|label:procedure[]
|label:apoc-core[]

|xref::overview/apoc.export/apoc.export.cypherQuery.adoc[apoc.export.cypherQuery icon:book[]]

apoc.export.cypherQuery(query,file,config) - exports nodes and relationships from the cypher kernelTransaction incl. indexes as cypher statements to the provided file|label:procedure[]
|label:apoc-core[]

|===

