[[map-functions]]
= Map Functions

[abstract]
--
This section describes functions for working with maps.
--

ifdef::backend-html5[]
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/_Qdhouvx-Qw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
++++
endif::[]

[cols="1m,5"]
|===
| apoc.map.fromNodes(label, property) | creates map from nodes with this label grouped by property
| apoc.map.fromPairs([[key,value],[key2,value2],...]) | creates map from list with key-value pairs
| apoc.map.fromLists([keys],[values]) | creates map from a keys and a values list
| apoc.map.fromValues([key,value,key1,value1]) | creates map from alternating keys and values in a list
| apoc.map.merge({first},{second}) yield value | creates map from merging the two source maps
| apoc.map.mergeList([{maps}]) yield value | merges all maps in the list into one
| apoc.map.setKey(map,key,value) | returns the map with the value for this key added or replaced
| apoc.map.removeKey(map,key) | returns the map with the key removed
| apoc.map.removeKeys(map,[keys]) | returns the map with the keys removed
| apoc.map.clean(map,[keys],[values]) yield value | removes the keys and values (e.g. null-placeholders) contained in those lists, good for data cleaning from CSV/JSON
| apoc.map.groupBy([maps/nodes/relationships],'key') yield value | creates a map of the list keyed by the given property, with single values
| apoc.map.groupByMulti([maps/nodes/relationships],'key') yield value | creates a map of the list keyed by the given property, with list values
| apoc.map.sortedProperties(map, ignoreCase:true) | returns a list of key/value list pairs, with pairs sorted by keys alphabetically, with optional case sensitivity
| apoc.map.updateTree(tree,key,[[value,{data}]]) | returns map - adds the {data} map on each level of the nested tree, where the key-value pairs match
| apoc.map.values(map, [key1,key2,key3,...],[addNullsForMissing]) | returns list of values indicated by the keys
| apoc.map.submap(map,keys,[[defaults]],[fail=true]) | returns submap for keys or throws exception if one of the key doesn't exist and no default value given at that position
| apoc.map.mget(map,keys,[[defaults]],[fail=true]) | returns list of values for keys or throws exception if one of the key doesn't exist and no default value given at that position
| apoc.map.get(map,key,[default],[fail=true]) | returns value for key or throws exception if key doesn't exist and no default given
|===


.Create map from list of key-value pairs:
[source,cypher]
----
RETURN apoc.map.fromPairs([
    ["name", "Cristiano Ronaldo"],
    ["age", date("1985-02-05")]
]) AS output
----

.Results
[opts="header",cols="1"]
|===
| Output
a|
[source,json]
----
{"name":"Cristiano Ronaldo","dob":"1985-02-06"}
----
|===

.Create map from alternating keys and values in a list:
[source,cypher]
----
RETURN apoc.map.fromValues([
    "name", "Cristiano Ronaldo",
    "age", date("1985-02-05")
]) AS output
----

.Results
[opts="header",cols="1"]
|===
| Output
a|

[source,json]
----
{"name":"Cristiano Ronaldo","dob":"1985-02-06"}
----
|===

.Create map from keys and values lists:
[source,cypher]
----
RETURN apoc.map.fromLists(
    ["name", "dob"],
    ["Cristiano Ronaldo", date("1985-02-05")]
) AS output
----

.Results
[opts="header",cols="1"]
|===
| Output
a|

[source,json]
----
{"name":"Cristiano Ronaldo","dob":"1985-02-06"}
----

|===


.Merges two maps:
[source,cypher]
----
RETURN apoc.map.merge(
    {name: "Cristiano Ronaldo", dob: date("1985-02-05")},
    {country: "Portugal"}
) AS output
----

.Results
[opts="header",cols="1"]
|===
| Output
a|
[source,json]
----
{"name":"Cristiano Ronaldo","country":"Portugal","dob":"1985-02-06"}
----
|===

.Merges multiple maps:
[source,cypher]
----
RETURN apoc.map.mergeList([
    {name: "Cristiano Ronaldo"},
    {dob: date("1985-02-05")},
    {country: "Portugal"}
]) AS output
----

.Results
[opts="header",cols="1"]
|===
| Output
a|

[source,json]
----
{"name":"Cristiano Ronaldo","country":"Portugal","dob":"1985-02-06"}
----
|===

.Updates a key in a map:
[source,cypher]
----
RETURN apoc.map.setKey(
    {name:"Cristiano Ronaldo",country:"Portugal",dob:date("1985-02-05")},
    "dob",
    date("1986-02-06")
) AS output
----

.Results
[opts="header",cols="1"]
|===
| Output
a|
[source,json]
----
{"name":"Cristiano Ronaldo","country":"Portugal","dob":"1986-02-06"}
----

|===

.Remove a key from a map:
[source,cypher]
----
RETURN apoc.map.removeKey(
    {name:"Cristiano Ronaldo",country:"Portugal",dob:date("1985-02-05")},
    "dob"
) AS output
----

.Results
[opts="header",cols="1"]
|===
| Output
a|
[source,json]
----
{"name":"Cristiano Ronaldo","country":"Portugal"}
----
|===

.Remove keys from a map:
[source,cypher]
----
RETURN apoc.map.removeKeys(
    {name:"Cristiano Ronaldo",country:"Portugal",dob:date("1985-02-05")},
    ["dob", "country"]
) AS output
----

.Results
[opts="header",cols="1"]
|===
| Output
a|

[source,json]
----
{"name":"Cristiano Ronaldo"}}
----
|===

.Remove empty string values from a map:
[source,cypher]
----
RETURN apoc.map.clean({name: "Cristiano Ronaldo", club: ""}, [], [""]) AS output
----

.Results
[opts="header",cols="1"]
|===
| Output
a|
[source,json]
----
{"name":"Cristiano Ronaldo"}}
----
|===

.Remove empty string values and the keys `dob` and `country` from a map:
[source,cypher]
----
RETURN apoc.map.clean(
    {name:"Cristiano Ronaldo",country:"Portugal",dob:date("1985-02-05"), club: ""},
    ["dob", "country"],
    [""]
) AS output
----

.Results
[opts="header",cols="1"]
|===
| Output
a|
[source,json]
----
{"name":"Cristiano Ronaldo"}
----
|===

.Create a map of the list keyed by `club`, with list values
[source,cypher]
----
RETURN apoc.map.groupByMulti([
	{name: "Cristiano Ronaldo", club: "Juventus"},
    {name: "Lionel Messi", club: "Barcelona"},
    {name: "Aaron Ramsey", club: "Juventus"},
    {name: "Luiz Suarez", club: "Barcelona"}
], "club") AS output
----

.Results
[opts="header",cols="a"]
|===
| Output
|
[source,json]
----
{
    "Juventus": [
      {
        "name": "Cristiano Ronaldo",
        "club": "Juventus"
      },
      {
        "name": "Aaron Ramsey",
        "club": "Juventus"
      }
    ],
    "Barcelona": [
      {
        "name": "Lionel Messi",
        "club": "Barcelona"
      },
      {
        "name": "Luiz Suarez",
        "club": "Barcelona"
      }
    ]
  }
----
|===
