////
This file is generated by DocsTest, so don't change it!
////

= apoc.number
:description: This section contains reference documentation for the apoc.number procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.number/apoc.number.arabicToRoman.adoc[apoc.number.arabicToRoman icon:book[]]

apoc.number.arabicToRoman(number)  \| convert arabic numbers to roman
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.exact.add.adoc[apoc.number.exact.add icon:book[]]

apoc.number.exact.add(stringA,stringB) - return the sum's result of two large numbers
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.exact.div.adoc[apoc.number.exact.div icon:book[]]

apoc.number.exact.div(stringA,stringB,[prec],[roundingModel]) - return the division's result of two large numbers
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.exact.mul.adoc[apoc.number.exact.mul icon:book[]]

apoc.number.exact.mul(stringA,stringB,[prec],[roundingModel]) - return the multiplication's result of two large numbers 
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.exact.sub.adoc[apoc.number.exact.sub icon:book[]]

apoc.number.exact.sub(stringA,stringB) - return the substraction's of two large numbers
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.exact.toExact.adoc[apoc.number.exact.toExact icon:book[]]

apoc.number.exact.toExact(number) - return the exact value
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.exact.toFloat.adoc[apoc.number.exact.toFloat icon:book[]]

apoc.number.exact.toFloat(string,[prec],[roundingMode]) - return the Float value of a large number
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.exact.toInteger.adoc[apoc.number.exact.toInteger icon:book[]]

apoc.number.exact.toInteger(string,[prec],[roundingMode]) - return the Integer value of a large number
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.format.adoc[apoc.number.format icon:book[]]

apoc.number.format(number)  \| format a long or double using the default system pattern and language to produce a string
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.parseFloat.adoc[apoc.number.parseFloat icon:book[]]

apoc.number.parseFloat(text)  \| parse a text using the default system pattern and language to produce a double
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.parseInt.adoc[apoc.number.parseInt icon:book[]]

apoc.number.parseInt(text)  \| parse a text using the default system pattern and language to produce a long
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.number/apoc.number.romanToArabic.adoc[apoc.number.romanToArabic icon:book[]]

apoc.number.romanToArabic(romanNumber)  \| convert roman numbers to arabic
|label:function[]
|label:apoc-core[]
|===

