////
This file is generated by DocsTest, so don't change it!
////

= apoc.number
:description: This section contains reference documentation for the apoc.number procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.number/apoc.number.arabicToRoman.adoc[apoc.number.arabicToRoman icon:book[]]

apoc.number.arabicToRoman(number)  \| convert arabic numbers to roman|label:function[]
|label:apoc-core[]

|xref::overview/apoc.number/apoc.number.format.adoc[apoc.number.format icon:book[]]

apoc.number.format(number)  \| format a long or double using the default system pattern and language to produce a string|label:function[]
|label:apoc-core[]

|xref::overview/apoc.number/apoc.number.parseFloat.adoc[apoc.number.parseFloat icon:book[]]

apoc.number.parseFloat(text)  \| parse a text using the default system pattern and language to produce a double|label:function[]
|label:apoc-core[]

|xref::overview/apoc.number/apoc.number.parseInt.adoc[apoc.number.parseInt icon:book[]]

apoc.number.parseInt(text)  \| parse a text using the default system pattern and language to produce a long|label:function[]
|label:apoc-core[]

|xref::overview/apoc.number/apoc.number.romanToArabic.adoc[apoc.number.romanToArabic icon:book[]]

apoc.number.romanToArabic(romanNumber)  \| convert roman numbers to arabic|label:function[]
|label:apoc-core[]

|===

