////
This file is generated by DocsTest, so don't change it!
////

= apoc.refactor.cloneSubgraph
:description: This section contains reference documentation for the apoc.refactor.cloneSubgraph procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.refactor.cloneSubgraph([node1,node2,...], [rel1,rel2,...]:[], {standinNodes:[], skipProperties:[]}) YIELD input, output, error | clone nodes with their labels and properties (optionally skipping any properties in the skipProperties list via the config map), and clone the given relationships (will exist between cloned nodes only). If no relationships are provided, all relationships between the given nodes will be cloned. Relationships can be optionally redirected according to standinNodes node pairings (this is a list of list-pairs of nodes), so given a node in the original subgraph (first of the pair), an existing node (second of the pair) can act as a standin for it within the cloned subgraph. Cloned relationships will be redirected to the standin.

== Signature

[source]
----
apoc.refactor.cloneSubgraph(nodes :: LIST? OF NODE?, rels = [] :: LIST? OF RELATIONSHIP?, config = {} :: MAP?) :: (input :: INTEGER?, output :: NODE?, error :: STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|nodes|LIST? OF NODE?|null
|rels|LIST? OF RELATIONSHIP?|[]
|config|MAP?|{}
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|input|INTEGER?
|output|NODE?
|error|STRING?
|===

[[usage-apoc.refactor.cloneSubgraph]]
== Usage Examples
include::partial$usage/apoc.refactor.cloneSubgraph.adoc[]

