////
This file is generated by DocsTest, so don't change it!
////

= apoc.refactor.rename.label
:description: This section contains reference documentation for the apoc.refactor.rename.label procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.refactor.rename.label(oldLabel, newLabel, [nodes]) | rename a label from 'oldLabel' to 'newLabel' for all nodes. If 'nodes' is provided renaming is applied to this set only

== Signature

[source]
----
apoc.refactor.rename.label(oldLabel :: STRING?, newLabel :: STRING?, nodes = [] :: LIST? OF NODE?) :: (batches :: INTEGER?, total :: INTEGER?, timeTaken :: INTEGER?, committedOperations :: INTEGER?, failedOperations :: INTEGER?, failedBatches :: INTEGER?, retries :: INTEGER?, errorMessages :: MAP?, batch :: MAP?, operations :: MAP?, constraints :: LIST? OF STRING?, indexes :: LIST? OF STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|oldLabel|STRING?|null
|newLabel|STRING?|null
|nodes|LIST? OF NODE?|[]
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|batches|INTEGER?
|total|INTEGER?
|timeTaken|INTEGER?
|committedOperations|INTEGER?
|failedOperations|INTEGER?
|failedBatches|INTEGER?
|retries|INTEGER?
|errorMessages|MAP?
|batch|MAP?
|operations|MAP?
|constraints|LIST? OF STRING?
|indexes|LIST? OF STRING?
|===

[[usage-apoc.refactor.rename.label]]
== Usage Examples
include::partial$usage/apoc.refactor.rename.label.adoc[]

xref::graph-updates/graph-refactoring/rename-label-type-property.adoc[More documentation of apoc.refactor.rename.label,role=more information]

