////
This file is generated by DocsTest, so don't change it!
////

= apoc.refactor.cloneSubgraphFromPaths
:description: This section contains reference documentation for the apoc.refactor.cloneSubgraphFromPaths procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.refactor.cloneSubgraphFromPaths([path1, path2, ...], {standinNodes:[], skipProperties:[]}) YIELD input, output, error | from the subgraph formed from the given paths, clone nodes with their labels and properties (optionally skipping any properties in the skipProperties list via the config map), and clone the relationships (will exist between cloned nodes only). Relationships can be optionally redirected according to standinNodes node pairings (this is a list of list-pairs of nodes), so given a node in the original subgraph (first of the pair), an existing node (second of the pair) can act as a standin for it within the cloned subgraph. Cloned relationships will be redirected to the standin.

== Signature

[source]
----
apoc.refactor.cloneSubgraphFromPaths(paths :: LIST? OF PATH?, config = {} :: MAP?) :: (input :: INTEGER?, output :: NODE?, error :: STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|paths|LIST? OF PATH?|null
|config|MAP?|{}
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|input|INTEGER?
|output|NODE?
|error|STRING?
|===

[[usage-apoc.refactor.cloneSubgraphFromPaths]]
== Usage Examples
include::partial$usage/apoc.refactor.cloneSubgraphFromPaths.adoc[]

