////
This file is generated by DocsTest, so don't change it!
////

= apoc.refactor.rename.typeProperty
:description: This section contains reference documentation for the apoc.refactor.rename.typeProperty procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.refactor.rename.typeProperty(oldName, newName, [rels], \{config}) | rename all relationship's property from 'oldName' to 'newName'. If 'rels' is provided renaming is applied to this set only

== Signature

[source]
----
apoc.refactor.rename.typeProperty(oldName :: STRING?, newName :: STRING?, rels = [] :: LIST? OF RELATIONSHIP?, config = {} :: MAP?) :: (batches :: INTEGER?, total :: INTEGER?, timeTaken :: INTEGER?, committedOperations :: INTEGER?, failedOperations :: INTEGER?, failedBatches :: INTEGER?, retries :: INTEGER?, errorMessages :: MAP?, batch :: MAP?, operations :: MAP?, constraints :: LIST? OF STRING?, indexes :: LIST? OF STRING?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|oldName|STRING?|null
|newName|STRING?|null
|rels|LIST? OF RELATIONSHIP?|[]
|config|MAP?|{}
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|batches|INTEGER?
|total|INTEGER?
|timeTaken|INTEGER?
|committedOperations|INTEGER?
|failedOperations|INTEGER?
|failedBatches|INTEGER?
|retries|INTEGER?
|errorMessages|MAP?
|batch|MAP?
|operations|MAP?
|constraints|LIST? OF STRING?
|indexes|LIST? OF STRING?
|===

[[usage-apoc.refactor.rename.typeProperty]]
== Usage Examples
include::partial$usage/apoc.refactor.rename.typeProperty.adoc[]

xref::graph-updates/graph-refactoring/rename-label-type-property.adoc[More documentation of apoc.refactor.rename.typeProperty,role=more information]

