////
This file is generated by DocsTest, so don't change it!
////

= apoc.warmup.run
:description: This section contains reference documentation for the apoc.warmup.run procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.warmup.run(loadProperties=false,loadDynamicProperties=false,loadIndexes=false) - quickly loads all nodes and rels into memory by skipping one page at a time

== Signature

[source]
----
apoc.warmup.run(loadProperties = false :: BOOLEAN?, loadDynamicProperties = false :: BOOLEAN?, loadIndexes = false :: BOOLEAN?) :: (pageSize :: INTEGER?, totalTime :: INTEGER?, transactionWasTerminated :: BOOLEAN?, nodesPerPage :: INTEGER?, nodesTotal :: INTEGER?, nodePages :: INTEGER?, nodesTime :: INTEGER?, relsPerPage :: INTEGER?, relsTotal :: INTEGER?, relPages :: INTEGER?, relsTime :: INTEGER?, relGroupsPerPage :: INTEGER?, relGroupsTotal :: INTEGER?, relGroupPages :: INTEGER?, relGroupsTime :: INTEGER?, propertiesLoaded :: BOOLEAN?, dynamicPropertiesLoaded :: BOOLEAN?, propsPerPage :: INTEGER?, propRecordsTotal :: INTEGER?, propPages :: INTEGER?, propsTime :: INTEGER?, stringPropsPerPage :: INTEGER?, stringPropRecordsTotal :: INTEGER?, stringPropPages :: INTEGER?, stringPropsTime :: INTEGER?, arrayPropsPerPage :: INTEGER?, arrayPropRecordsTotal :: INTEGER?, arrayPropPages :: INTEGER?, arrayPropsTime :: INTEGER?, indexesLoaded :: BOOLEAN?, indexPages :: INTEGER?, indexTime :: INTEGER?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|loadProperties|BOOLEAN?|false
|loadDynamicProperties|BOOLEAN?|false
|loadIndexes|BOOLEAN?|false
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|pageSize|INTEGER?
|totalTime|INTEGER?
|transactionWasTerminated|BOOLEAN?
|nodesPerPage|INTEGER?
|nodesTotal|INTEGER?
|nodePages|INTEGER?
|nodesTime|INTEGER?
|relsPerPage|INTEGER?
|relsTotal|INTEGER?
|relPages|INTEGER?
|relsTime|INTEGER?
|relGroupsPerPage|INTEGER?
|relGroupsTotal|INTEGER?
|relGroupPages|INTEGER?
|relGroupsTime|INTEGER?
|propertiesLoaded|BOOLEAN?
|dynamicPropertiesLoaded|BOOLEAN?
|propsPerPage|INTEGER?
|propRecordsTotal|INTEGER?
|propPages|INTEGER?
|propsTime|INTEGER?
|stringPropsPerPage|INTEGER?
|stringPropRecordsTotal|INTEGER?
|stringPropPages|INTEGER?
|stringPropsTime|INTEGER?
|arrayPropsPerPage|INTEGER?
|arrayPropRecordsTotal|INTEGER?
|arrayPropPages|INTEGER?
|arrayPropsTime|INTEGER?
|indexesLoaded|BOOLEAN?
|indexPages|INTEGER?
|indexTime|INTEGER?
|===

[[usage-apoc.warmup.run]]
== Usage Examples
include::partial$usage/apoc.warmup.run.adoc[]

