By default exporting to the file system is disabled.
We can enable it by setting the following property in `apoc.conf`:

.apoc.conf
[source,properties]
----
apoc.export.file.enabled=true
----

If we try to use any of the export procedures without having first set this property, we'll get the following error message:

|===
| Failed to invoke procedure: Caused by: java.lang.RuntimeException: Export to files not enabled, please set apoc.export.file.enabled=true in your apoc.conf.
Otherwise, if you are running in a cloud environment without filesystem access, use the `{stream:true}` config and null as a 'file' parameter to stream the export back to your client.
Note that the stream mode cannot be used with the apoc.export.xls.* procedures.
|===

Export files are written to the `import` directory, which is defined by the `server.directories.import` property.
This means that any file path that we provide is relative to this directory.
If we try to write to an absolute path, such as `/tmp/filename`, we'll get an error message similar to the following one:

|===
| Failed to invoke procedure: Caused by: java.io.FileNotFoundException: /path/to/neo4j/import/tmp/fileName (No such file or directory)
|===

We can enable writing to anywhere on the file system by setting the following property in `apoc.conf`:

.apoc.conf
[source,properties]
----
apoc.import.file.use_neo4j_config=false
----

[WARNING]
====
Neo4j will now be able to write anywhere on the file system, so be sure that this is your intention before setting this property.
====