[WARNING]
====
// tag::warnings[]
The Extended APOC library contains over 150 functions and procedures.

It is *not* recommended to load all of these into the dbms, but instead use the principle of least privilege.
This principle dictates that you only load the functions and procedures necessary to execute your queries.

The procedures and functions that should be loaded can be specified using the Neo4j configuration setting `+dbms.security.procedures.allowlist+` in `$NEO4J_HOME/conf/neo4j.conf`.
For example, to load `apoc.load.csv` and all functions in the `apoc.cypher` package, use `+dbms.security.procedures.allowlist=apoc.load.csv,apoc.cypher.*+`.


Please note that using e.g. `apoc.cypher.*`, if the https://neo4j.com/docs/apoc/{branch}[APOC Core] plugin is installed, will also load the `the `apoc.cypher.*` Core procedures / functions,
as well as other plugins that may be using the same package.


The default of the setting is `*`.
This means that if you do not explicitly give it a value (or no value), all APOC procedures and functions, as well as other potential libraries in the plugins directory will be loaded.

For security reasons, procedures and functions that use internal APIs are disabled by default.
In this case, it is also recommended to use the principle of least privilege and only unrestrict those procedures and functions which you are certain to use.
Procedures and functions can be unrestricted using the Neo4j configuration setting `+dbms.security.procedures.unrestricted+` in `$NEO4J_HOME/conf/neo4j.conf`.
For example, if you need to unrestrict `apoc.ttl.expire` and `apoc.ttl.expireIn`, use: `+dbms.security.procedures.unrestricted=apoc.ttl.expire,apoc.ttl.expireIn+`.

To unrestrict a whole package of APOC functions and procedures when using the Neo4j Docker container, you need to amend the Docker environment variables.
For example, if you need to add the full `apoc.custom` package, add `+-e NEO4J_dbms_security_procedures_unrestricted=apoc.custom.\\\*+` to your `docker run ...` command.
The three backslashes are necessary to prevent wildcard expansions.

Please note that if you have APOC Core installed, 
the same goes for the `dbms.security.procedures.allowlist` one, 
so setting `dbms.security.procedures.unrestricted=package.name.*` will unrestrict both Extended and Core procedures / functions.

// end::warnings[]
====
