== Using S3 protocol

When using the S3 protocol we need to download and copy the following jars into the plugins directory:

* aws-java-sdk-core-1.12.136.jar (https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-core/1.12.136)
* aws-java-sdk-s3-1.12.136.jar (https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-s3/1.12.136)
* httpclient-4.5.13.jar (https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.13)
* httpcore-4.4.15.jar (https://mvnrepository.com/artifact/org.apache.httpcomponents/httpcore/4.4.15)
* joda-time-2.10.13.jar (https://mvnrepository.com/artifact/joda-time/joda-time/2.10.13)

Once those files have been copied we'll need to restart the database.

The S3 URL must be in the following format:

* `s3://accessKey:secretKey[:sessionToken]@endpoint:port/bucket/key`
(where the sessionToken is optional) or
* `s3://endpoint:port/bucket/key?accessKey=accessKey&secretKey=secretKey[&sessionToken=sessionToken]`
(where the sessionToken is optional) or
* `s3://endpoint:port/bucket/key`
if the accessKey, secretKey, and the optional sessionToken are provided in the environment variables

=== S3 protocol without SSL certificates checking

To run S3 on providers that do not need SSL certificates, such as a minio container created in the following way:

[source, bash]
----
docker run -p 9000:9000 -p 9001:9001 \
  -e "MINIO_ROOT_USER=accessTestKey" \
  -e "MINIO_ROOT_PASSWORD=secretTestKey" \
  -e "MINIO_DEFAULT_BUCKETS=test" \
  bitnami/minio:2025.1.20
----

we need to put in the `neo4j.conf` this setting:
[source, config]
----
server.jvm.additional=-Dcom.amazonaws.sdk.disableCertChecking=true
----

Therefore, using this setting and the above minio container,
the correct way to retrieve CSV file named `foo.csv` from the `test` bucket is:

[source,cypher]
----
CALL apoc.load.csv('s3://127.0.0.1:9000/test/foo.csv?accessKey=accessTestKey&secretKey=secretTestKey')
----