////
This file is generated by DocsTest, so don't change it!
////

= apoc.periodic.countdown
:page-custom-canonical: https://neo4j.com/docs/apoc/current/overview/apoc.periodic/apoc.periodic.countdown/
:description: This section contains reference documentation for the apoc.periodic.countdown procedure.

label:procedure[] label:apoc-core[]

[WARNING]
====
This procedure is not intended to be used in a cluster environment, and may act unpredictably.
It continues to execute against the same database that it was initiated on, meaning that in a cluster environment, it only executes on the leader.
If there is a leader switch then the procedure may error and stop running.
====

[.emphasis]
apoc.periodic.countdown('name',statement,repeat-rate-in-seconds) creates a background job that will repeatedly execute the given Cypher statement until it returns 0.

== Signature

[source]
----
apoc.periodic.countdown(name :: STRING?, statement :: STRING?, rate :: INTEGER?) :: (name :: STRING?, delay :: INTEGER?, rate :: INTEGER?, done :: BOOLEAN?, cancelled :: BOOLEAN?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|name|STRING?|null
|statement|STRING?|null
|rate|INTEGER?|null
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|name|STRING?
|delay|INTEGER?
|rate|INTEGER?
|done|BOOLEAN?
|cancelled|BOOLEAN?
|===

[[usage-apoc.periodic.countdown]]
== Usage Examples
include::partial$usage/apoc.periodic.countdown.adoc[]

