////
This file is generated by DocsTest, so don't change it!
////

= apoc.periodic.repeat
:page-custom-canonical: https://neo4j.com/docs/apoc/current/overview/apoc.periodic/apoc.periodic.repeat/
:description: This section contains reference documentation for the apoc.periodic.repeat procedure.

label:procedure[] label:apoc-core[]

[WARNING]
====
This procedure is not intended to be used in a cluster environment, and may act unpredictably.
It continues to execute against the same database that it was initiated on, meaning that in a cluster environment, it only executes on the leader.
If there is a leader switch then the procedure may error and stop running.
====

[.emphasis]
apoc.periodic.repeat('name',statement,repeat-rate-in-seconds, config) submit a repeatedly-called background query. The parameter 'config' is optional and can contain a 'params' entry usable in nested Cypher statement.

== Signature

[source]
----
apoc.periodic.repeat(name :: STRING?, statement :: STRING?, rate :: INTEGER?, config = {} :: MAP?) :: (name :: STRING?, delay :: INTEGER?, rate :: INTEGER?, done :: BOOLEAN?, cancelled :: BOOLEAN?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|name|STRING?|null
|statement|STRING?|null
|rate|INTEGER?|null
|config|MAP?|{}
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|name|STRING?
|delay|INTEGER?
|rate|INTEGER?
|done|BOOLEAN?
|cancelled|BOOLEAN?
|===

[[usage-apoc.periodic.repeat]]
== Usage Examples
include::partial$usage/apoc.periodic.repeat.adoc[]

