////
This file is generated by DocsTest, so don't change it!
////

= apoc.periodic.iterate
:description: This section contains reference documentation for the apoc.periodic.iterate procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.periodic.iterate('statement returning items', 'statement per item', {batchSize:1000,iterateList:true,parallel:false,params:{},concurrency:50,retries:0}) YIELD batches, total - run the second statement for each item returned by the first statement. Returns number of batches and total processed rows

== Signature

[source]
----
apoc.periodic.iterate(cypherIterate :: STRING?, cypherAction :: STRING?, config :: MAP?) :: (batches :: INTEGER?, total :: INTEGER?, timeTaken :: INTEGER?, committedOperations :: INTEGER?, failedOperations :: INTEGER?, failedBatches :: INTEGER?, retries :: INTEGER?, errorMessages :: MAP?, batch :: MAP?, operations :: MAP?, wasTerminated :: BOOLEAN?, failedParams :: MAP?, updateStatistics :: MAP?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|cypherIterate|STRING?|null
|cypherAction|STRING?|null
|config|MAP?|null
|===

== Config parameters
include::partial$usage/config/apoc.periodic.iterate.adoc[]

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|batches|INTEGER?
|total|INTEGER?
|timeTaken|INTEGER?
|committedOperations|INTEGER?
|failedOperations|INTEGER?
|failedBatches|INTEGER?
|retries|INTEGER?
|errorMessages|MAP?
|batch|MAP?
|operations|MAP?
|wasTerminated|BOOLEAN?
|failedParams|MAP?
|updateStatistics|MAP?
|===

[[usage-apoc.periodic.iterate]]
== Usage Examples
include::partial$usage/apoc.periodic.iterate.adoc[]

