////
This file is generated by DocsTest, so don't change it!
////

= apoc.periodic.rock_n_roll
:description: This section contains reference documentation for the apoc.periodic.rock_n_roll procedure.

label:procedure[] label:apoc-full[] label:deprecated[]

[.emphasis]
apoc.periodic.rock_n_roll('some cypher for iteration', 'some cypher as action on each iteration', 10000) YIELD batches, total - run the action statement in batches over the iterator statement's results in a separate thread. Returns number of batches and total processed rows

== Signature

[source]
----
apoc.periodic.rock_n_roll(cypherIterate :: STRING?, cypherAction :: STRING?, batchSize :: INTEGER?) :: (batches :: INTEGER?, total :: INTEGER?, timeTaken :: INTEGER?, committedOperations :: INTEGER?, failedOperations :: INTEGER?, failedBatches :: INTEGER?, retries :: INTEGER?, errorMessages :: MAP?, batch :: MAP?, operations :: MAP?, wasTerminated :: BOOLEAN?, failedParams :: MAP?, updateStatistics :: MAP?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|cypherIterate|STRING?|null
|cypherAction|STRING?|null
|batchSize|INTEGER?|null
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|batches|INTEGER?
|total|INTEGER?
|timeTaken|INTEGER?
|committedOperations|INTEGER?
|failedOperations|INTEGER?
|failedBatches|INTEGER?
|retries|INTEGER?
|errorMessages|MAP?
|batch|MAP?
|operations|MAP?
|wasTerminated|BOOLEAN?
|failedParams|MAP?
|updateStatistics|MAP?
|===

xref::graph-updates/periodic-execution.adoc#periodic-rock-n-roll[More documentation of apoc.periodic.rock_n_roll,role=more information]

