////
This file is generated by DocsTest, so don't change it!
////

= apoc.periodic
:description: This section contains reference documentation for the apoc.periodic procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.periodic/apoc.periodic.cancel.adoc[apoc.periodic.cancel icon:book[]]

apoc.periodic.cancel(name) - cancel job with the given name
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.periodic/apoc.periodic.commit.adoc[apoc.periodic.commit icon:book[]]

apoc.periodic.commit(statement,params) - runs the given statement in separate transactions until it returns 0
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.periodic/apoc.periodic.countdown.adoc[apoc.periodic.countdown icon:book[]]

apoc.periodic.countdown('name',statement,repeat-rate-in-seconds) submit a repeatedly-called background statement until it returns 0
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.periodic/apoc.periodic.iterate.adoc[apoc.periodic.iterate icon:book[]]

apoc.periodic.iterate('statement returning items', 'statement per item', {batchSize:1000,iterateList:true,parallel:false,params:{},concurrency:50,retries:0}) YIELD batches, total - run the second statement for each item returned by the first statement. Returns number of batches and total processed rows
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.periodic/apoc.periodic.list.adoc[apoc.periodic.list icon:book[]]

apoc.periodic.list - list all jobs
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.periodic/apoc.periodic.repeat.adoc[apoc.periodic.repeat icon:book[]]

apoc.periodic.repeat('name',statement,repeat-rate-in-seconds, config) submit a repeatedly-called background statement. Fourth parameter 'config' is optional and can contain 'params' entry for nested statement.
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.periodic/apoc.periodic.rock_n_roll.adoc[apoc.periodic.rock_n_roll icon:book[]]

apoc.periodic.rock_n_roll('some cypher for iteration', 'some cypher as action on each iteration', 10000) YIELD batches, total - run the action statement in batches over the iterator statement's results in a separate thread. Returns number of batches and total processed rows
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.periodic/apoc.periodic.rock_n_roll_while.adoc[apoc.periodic.rock_n_roll_while icon:book[]]

apoc.periodic.rock_n_roll_while('some cypher for knowing when to stop', 'some cypher for iteration', 'some cypher as action on each iteration', 10000) YIELD batches, total - run the action statement in batches over the iterator statement's results in a separate thread. Returns number of batches and total processed rows
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.periodic/apoc.periodic.submit.adoc[apoc.periodic.submit icon:book[]]

apoc.periodic.submit('name',statement) - submit a one-off background statement
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.periodic/apoc.periodic.truncate.adoc[apoc.periodic.truncate icon:book[]]

apoc.periodic.truncate(\{config}) - removes all entities (and optionally indexes and constraints) from db using the apoc.periodic.iterate under the hood
|label:procedure[]
|label:apoc-core[]
|===

