////
This file is generated by DocsTest, so don't change it!
////

= apoc.uuid.install
:description: This section contains reference documentation for the apoc.uuid.install procedure.

label:procedure[] label:apoc-extended[] label:deprecated[]

[.emphasis]
CALL apoc.uuid.install(label, {addToExistingNodes: true/false, uuidProperty: 'uuid'}) yield label, installed, properties, batchComputationResult | it will add the uuid transaction handler
for the provided `label` and `uuidProperty`, in case the UUID handler is already present it will be replaced by the new one

== Signature

[source]
----
apoc.uuid.install(label :: STRING?, config = {} :: MAP?) :: (batchComputationResult :: MAP?, label :: STRING?, installed :: BOOLEAN?, properties :: MAP?)
----

include::partial$uuid/deprecated.adoc[]

[WARNING]
====
This procedure is not intended to be used in a cluster environment, and may act unpredictably.
====

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|label|STRING?|null
|config|MAP?|{}
|===

== Config parameters
include::partial$usage/config/apoc.uuid.install.adoc[]

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|batchComputationResult|MAP?
|label|STRING?
|installed|BOOLEAN?
|properties|MAP?
|===

== Enable automatic UUIDs
include::partial$uuids.adoc[]

[[usage-apoc.uuid.install]]
== Usage Examples
include::partial$usage/apoc.uuid.install.adoc[]

xref::graph-updates/uuid.adoc[More documentation of apoc.uuid.install,role=more information]

