////
This file is generated by DocsTest, so don't change it!
////

= apoc.hashing
:description: This section contains reference documentation for the apoc.hashing procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.hashing/apoc.hashing.fingerprint.adoc[apoc.hashing.fingerprint icon:book[]]

calculate a checksum (md5) over a node or a relationship. This deals gracefully with array properties. Two identical entities do share the same hash.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.hashing/apoc.hashing.fingerprintGraph.adoc[apoc.hashing.fingerprintGraph icon:book[]]

calculate a checksum (md5) over a the full graph. Be aware that this function does use in-memomry datastructures depending on the size of your graph.
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.hashing/apoc.hashing.fingerprinting.adoc[apoc.hashing.fingerprinting icon:book[]]

calculate a checksum (md5) over a node or a relationship. This deals gracefully with array properties. Two identical entities do share the same hash.
|label:function[]
|label:apoc-core[]
|===

