name: "Setups JDK"

inputs:
  java-version:
    required: true
    default: '21'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'