name: "Setups JDK"
description: "Setups JDK"

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@215b7e5f829ab9cac114c149667e57dc1b70b4bc # v2
      with:
        java-version: '17.0.8'
        distribution: 'temurin'