name: "Setups JDK"

inputs:
  java-version:
    required: true
    default: '21'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'