CREATE TABLE phonebook(phone VARCHAR(32), firstname VARCHAR(32), lastname VARCHAR(32), address VARCHAR(64));

INSERT INTO phonebook(phone, firstname, lastname, address)
VALUES('+1 123 456 7890', 'John', 'Doe', 'North America');

CREATE TABLE PERSON(NAME varchar(50), HIRE_DATE DATE, EFFECTIVE_FROM_DATE TIMESTAMP, TEST_TIME TIME, NULL_DATE DATE);

INSERT INTO PERSON(NAME, HIRE_DATE, EFFECTIVE_FROM_DATE, TEST_TIME, NULL_DATE)
VALUES ('John','2017-05-25','2016-06-22T19:10:25','15:37:00',null);