[[installation]]
= Installation
:description: This section contains instructions for installing the APOC standard library.

_APOC Extended_ can be downloaded using one of the methods described in the sections below.

[[neo4j-server]]
== Neo4j Server

include::partial$neo4j-server.adoc[tags=install,leveloffset=2]

After you move the jar file to the plugins folder you have to restart neo4j with `neo4j restart`

// tag::version-matrix[]
Since APOC relies on Neo4j's internal APIs, you need to use the right APOC version for your Neo4j installation.

APOC uses a consistent versioning scheme: `<neo4j-version>.<apoc>` version.
The trailing `<apoc>` part of the version number will be incremented with every apoc release.

The version compatibility matrix explains the mapping between Neo4j and APOC versions:

[opts=header]
|===
|apoc version | neo4j version
| https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/5.2.0[5.2.0^] | 5.2.0 (5.2.x)
| https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/5.1.0[5.1.0^]| 5.1.0 (5.1.x)
| https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.4.0.1[4.4.0.1^] | 4.4.0 (4.3.x)
| https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.3.0.4[4.3.0.4^] | 4.3.7 (4.3.x)
| https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.2.0.9[4.2.0.9^] | 4.2.11 (4.2.x)
|===

// end::version-matrix[]

If by mistake a jar not compatible with the neo4j version is inserted, a `log.warn` like this will appear in `neo4j.log`:
```
The apoc version (<APOC_VERSION>) and the Neo4j DBMS versions [NEO4J_VERSION] are incompatible. 
See the compatibility matrix in https://neo4j.com/labs/apoc/4.4/installation/ to see the correct version
```

[[docker]]
== Docker

include::partial$docker.adoc[tags=docker,leveloffset=1]


[[mvnrepository]]
== Maven Repository

In a `pom.xml` of a maven project, you can add these two dependencies from https://mvnrepository.com/artifact/org.neo4j.procedure[Maven Repository]:

[source,subs=attributes]
----
&lt;dependency&gt;
    &lt;groupId&gt;org.neo4j.procedure&lt;/groupId&gt;
    &lt;artifactId&gt;apoc-extended&lt;/artifactId&gt;
    &lt;version&gt;{apoc-release}&lt;/version&gt;
    &lt;classifier&gt;extended&lt;/classifier&gt;
&lt;/dependency&gt;
----

Alternatively, you can download the jar https://repo1.maven.org/maven2/org/neo4j/procedure/apoc-extended/{apoc-release}/apoc-extended-{apoc-release}-extended.jar[from here]
and put it into `plugin` folder.


[[restricted]]
== Load and unrestrict procedures/functions

include::partial$restricted.adoc[tags=warnings,leveloffset=1]