[[installation]]
= Installation
:description: This section contains instructions for installing the APOC standard library.



_APOC Core_ is packaged with Neo4j and can be found in the `$NEO4J_HOME/labs` directory.
_APOC Full_ can be downloaded using one of the methods described in the sections below.

[WARNING]
====
_APOC Full_ contains all the procedures and functions included in _APOC Core_.
You *must not* install both libraries.
====

[[apoc-core]]
== APOC Core

_APOC Core_ can be installed by moving the APOC jar file from the `$NEO4J_HOME/labs` directory to the `$NEO4J_HOME/plugins` directory and restarting Neo4j.

[[neo4j-desktop]]
== Neo4j Desktop

include::partial$neo4j-desktop.adoc[tags=install-desktop,leveloffset=2]

[[neo4j-server]]
== Neo4j Server

include::partial$neo4j-server.adoc[tags=install,leveloffset=2]

After you move the jar file to the plugins folder you have to restart neo4j with `neo4j restart`

// tag::version-matrix[]
Since APOC relies on Neo4j's internal APIs, you need to use the right APOC version for your Neo4j installation.

APOC uses a consistent versioning scheme: `<neo4j-version>.<apoc>` version.
The trailing `<apoc>` part of the version number will be incremented with every apoc release.

The version compatibility matrix explains the mapping between Neo4j and APOC versions:

[opts=header]
|===
|apoc version | neo4j version
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.4.0.1[4.4.0.1^] | 4.4.0 (4.3.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.3.0.4[4.3.0.4^] | 4.3.7 (4.3.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.2.0.9[4.2.0.9^] | 4.2.11 (4.2.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.1.0.10[4.1.0.10^] | 4.1.11 (4.1.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.0.0.18[4.0.0.18^] | 4.0.12 (4.0.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.5.0.15[3.5.0.15^] | 3.5.30 (3.5.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.4.0.8[3.4.0.8^] | 3.4.18 (3.4.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.3.0.4[3.3.0.4^] | 3.3.9 (3.3.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.2.3.6[3.2.3.6^] | 3.2.14 (3.2.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.1.3.9[3.1.3.9^] | 3.1.9 (3.1.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.0.8.6[3.0.8.6^] | 3.0.12 (3.0.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.5.0.0[3.5.0.0^] | 3.5.0-beta01
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.4.0.2[3.4.0.2^] | 3.4.5
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.3.0.3[3.3.0.3^] | 3.3.5
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.2.3.5[3.2.3.5^] | 3.2.3
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.1.3.8[3.1.3.8^] | 3.1.5
|===

// end::version-matrix[]

If by mistake a jar not compatible with the neo4j version is inserted, a `log.warn` like this will appear in `neo4j.log`:
```
The apoc version (<APOC_VERSION>) and the Neo4j DBMS versions [NEO4J_VERSION] are incompatible. 
See the compatibility matrix in https://neo4j.com/labs/apoc/4.4/installation/ to see the correct version
```

[[docker]]
== Docker

include::partial$docker.adoc[tags=docker,leveloffset=1]

[[restricted]]
== Load and unrestrict procedures/function

include::partial$restricted.adoc[tags=warnings,leveloffset=1]

[[dependencies]]
== Additional dependencies excluded from the APOC Core jar
Some functionalities require additional jars in order to be used.
This includes xref::import/index.adoc[loading] and xref:export/index.adoc[exporting] data when using services such as:

* Amazon S3 (`s3://<path>`)
* Apache Hadoop (`hdfs://<path>`)
* Google Cloud Storage (`gs://<path>`)


These dependencies are specifically not included in the APOC Core jar, but
can be added as separate jars as described xref::import/web-apis.adoc[here].
If the extra dependencies are not included, warnings will show in the debug log file (debug.log)
that can be ignored if the respective functionality is not needed.
An example of such a warning would be:
```
 Failed to load `apoc.util.s3.S3URLConnection`
```