////
This file is generated by DocsTest, so don't change it!
////

= apoc.merge
:description: This section contains reference documentation for the apoc.merge procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.merge/apoc.merge.node.adoc[apoc.merge.node icon:book[]]

"apoc.merge.node(['Label'], identProps:{key:value, ...}, onCreateProps:{key:value,...}, onMatchProps:{key:value,...}}) - merge nodes with dynamic labels, with support for setting properties ON CREATE or ON MATCH
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.merge/apoc.merge.node.eager.adoc[apoc.merge.node.eager icon:book[]]

apoc.merge.node.eager(['Label'], identProps:{key:value, ...}, onCreateProps:{key:value,...}, onMatchProps:{key:value,...}}) - merge nodes eagerly, with dynamic labels, with support for setting properties ON CREATE or ON MATCH
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.merge/apoc.merge.nodeWithStats.adoc[apoc.merge.nodeWithStats icon:book[]]

apoc.merge.nodeWithStats - same as apoc.merge.node providing queryStatistics into result
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.merge/apoc.merge.nodeWithStats.eager.adoc[apoc.merge.nodeWithStats.eager icon:book[]]

apoc.merge.nodeWithStats.eager - same as apoc.merge.node.eager providing queryStatistics into result
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.merge/apoc.merge.relationship.adoc[apoc.merge.relationship icon:book[]]

apoc.merge.relationship(startNode, relType,  identProps:{key:value, ...}, onCreateProps:{key:value, ...}, endNode, onMatchProps:{key:value, ...}) - merge relationship with dynamic type, with support for setting properties ON CREATE or ON MATCH
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.merge/apoc.merge.relationship.eager.adoc[apoc.merge.relationship.eager icon:book[]]

apoc.merge.relationship(startNode, relType,  identProps:{key:value, ...}, onCreateProps:{key:value, ...}, endNode, onMatchProps:{key:value, ...}) - merge relationship with dynamic type, with support for setting properties ON CREATE or ON MATCH
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.merge/apoc.merge.relationshipWithStats.adoc[apoc.merge.relationshipWithStats icon:book[]]

apoc.merge.relationshipWithStats - same as apoc.merge.relationship providing queryStatistics into result
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.merge/apoc.merge.relationshipWithStats.eager.adoc[apoc.merge.relationshipWithStats.eager icon:book[]]

apoc.merge.relationshipWithStats.eager - same as apoc.merge.relationship.eager providing queryStatistics into result
|label:procedure[]
|label:apoc-core[]
|===

