////
This file is generated by DocsTest, so don't change it!
////

= apoc.static
:description: This section contains reference documentation for the apoc.static procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.static/apoc.static.get.adoc[apoc.static.get icon:book[]]

apoc.static.get(name) - returns statically stored value from config (apoc.static.<key>) or server lifetime storage
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.static/apoc.static.list.adoc[apoc.static.list icon:book[]]

apoc.static.list(prefix) - returns statically stored values from config (apoc.static.<prefix>.*) or server lifetime storage
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.static/apoc.static.set.adoc[apoc.static.set icon:book[]]

apoc.static.set(name, value) - stores value under key for server lifetime storage, returns previously stored or configured value
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.static/apoc.static.get.adoc[apoc.static.get icon:book[]]

apoc.static.get(name) - returns statically stored value from config (apoc.static.<key>) or server lifetime storage
|label:function[]
|label:apoc-full[]
|xref::overview/apoc.static/apoc.static.getAll.adoc[apoc.static.getAll icon:book[]]

apoc.static.getAll(prefix) - returns statically stored values from config (apoc.static.<prefix>.*) or server lifetime storage
|label:function[]
|label:apoc-full[]
|===

