name: "Setups cache for Gradle"
description: "Setups cache for Gradle"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
