name: "Setups cache for Gradle"
description: "Setups cache for Gradle"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
