////
This file is generated by DocsTest, so don't change it!
////

= apoc.spatial
:description: This section contains reference documentation for the apoc.spatial procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.spatial/apoc.spatial.geocode.adoc[apoc.spatial.geocode icon:book[]]

apoc.spatial.geocode('address') YIELD location, latitude, longitude, description, osmData - look up geographic location of address from a geocoding service (the default one is OpenStreetMap)
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.spatial/apoc.spatial.geocodeOnce.adoc[apoc.spatial.geocodeOnce icon:book[]]

apoc.spatial.geocodeOnce('address') YIELD location, latitude, longitude, description, osmData - look up geographic location of address from a geocoding service (the default one is OpenStreetMap)
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.spatial/apoc.spatial.reverseGeocode.adoc[apoc.spatial.reverseGeocode icon:book[]]

apoc.spatial.reverseGeocode(latitude,longitude) YIELD location, latitude, longitude, description - look up address from latitude and longitude from a geocoding service (the default one is OpenStreetMap)
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.spatial/apoc.spatial.sortByDistance.adoc[apoc.spatial.sortByDistance icon:book[]]

apoc.spatial.sortByDistance(List<Path>) sort the given paths based on the geo informations (lat/long) in ascending order
|label:procedure[]
|label:apoc-core[]
|===

