= Number Format Conversions

== Conversion between formatted decimals

* `apoc.number.format(number) yield value` format a long or double using the default system pattern and language to produce a string
* `apoc.number.format.pattern(number, pattern) yield value` format a long or double using a pattern and the default system language to produce a string
* `apoc.number.format.lang(number, lang) yield value` format a long or double using the default system pattern pattern and a language to produce a string
* `apoc.number.format.pattern.lang(number, pattern, lang) yield value` format a long or double using a pattern and a language to produce a string

* `apoc.number.parseInt(text) yield value` parse a text using the default system pattern and language to produce a long
* `apoc.number.parseInt.pattern(text, pattern) yield value` parse a text using a pattern and the default system language to produce a long
* `apoc.number.parseInt.lang(text, lang) yield value` parse a text using the default system pattern and a language to produce a long
* `apoc.number.parseInt.pattern.lang(text, pattern, lang) yield value` parse a text using a pattern and a language to produce a long

* `apoc.number.parseFloat(text) yield value` parse a text using the default system pattern and language to produce a double
* `apoc.number.parseFloat.pattern(text, pattern) yield value` parse a text using a pattern and the default system language to produce a double
* `apoc.number.parseFloat.lang(text, lang) yield value` parse a text using the default system pattern and a language to produce a double
* `apoc.number.parseFloat.pattern.lang(text, pattern, lang) yield value` parse a text using a pattern and a language to produce a double

* The full list of supported values for `pattern` and `lang` params is described in https://docs.oracle.com/javase/9/docs/api/java/text/DecimalFormat.html[DecimalFormat JavaDoc]

== Examples

....
  call apoc.number.format(12345.67) yield value
  return value

  ╒═════════╕
  │value    │
  ╞═════════╡
  │12,345.67│
  └─────────┘
....

....
  call apoc.number.format.pattern.lang(12345, '#,##0.00;(#,##0.00)', 'it') yield value
  return value

  ╒═════════╕
  │value    │
  ╞═════════╡
  │12.345,00│
  └─────────
....

....
  call apoc.number.format.pattern.lang(12345.67, '#,##0.00;(#,##0.00)', 'it') yield value
  return value
  
  ╒═════════╕
  │value    │
  ╞═════════╡
  │12.345,67│
  └─────────┘  
....

....
  call apoc.number.parseInt.pattern.lang('12.345', '#,##0.00;(#,##0.00)', 'it') yield value
  return value

  ╒═════╕
  │value│
  ╞═════╡
  │12345│
  └─────┘
....

....
  call apoc.number.parseFloat.pattern.lang('12.345,67', '#,##0.00;(#,##0.00)', 'it') yield value
  return value
  
  ╒════════╕
  │value   │
  ╞════════╡
  │12345.67│
  └────────┘
....

....
  call apoc.number.format('aaa') yield value

  Failed to invoke procedure `apoc.number.format`: Caused by: java.lang.IllegalArgumentException: Number parameter must be long or double.
....

....
  call apoc.number.format.lang(12345, 'apoc')
  
  Failed to invoke procedure `apoc.number.format.lang`: Caused by: java.lang.IllegalArgumentException: Unrecognized language value: 'apoc' isn't a valid ISO language
....

....
  call apoc.number.parseInt('aaa')
  
  Failed to invoke procedure `apoc.number.parseAsLong`: Caused by: java.text.ParseException: Unparseable number: "aaa"
....
