////
This file is generated by DocsTest, so don't change it!
////

= apoc.map
:description: This section contains reference documentation for the apoc.map procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.map/apoc.map.clean.adoc[apoc.map.clean icon:book[]]

apoc.map.clean(map,[skip,keys],[skip,values]) yield map filters the keys and values contained in those lists, good for data cleaning from CSV/JSON
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.flatten.adoc[apoc.map.flatten icon:book[]]

apoc.map.flatten(map, delimiter:'.') yield map - flattens nested items in map using dot notation
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.fromLists.adoc[apoc.map.fromLists icon:book[]]

apoc.map.fromLists([keys],[values])
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.fromNodes.adoc[apoc.map.fromNodes icon:book[]]

apoc.map.fromNodes(label, property)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.fromPairs.adoc[apoc.map.fromPairs icon:book[]]

apoc.map.fromPairs([[key,value],[key2,value2],...])
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.fromValues.adoc[apoc.map.fromValues icon:book[]]

apoc.map.fromValues([key1,value1,key2,value2,...])
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.get.adoc[apoc.map.get icon:book[]]

apoc.map.get(map,key,[default],[fail=true]) - returns value for key or throws exception if key doesn't exist and no default given
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.groupBy.adoc[apoc.map.groupBy icon:book[]]

apoc.map.groupBy([maps/nodes/relationships],'key') yield value - creates a map of the list keyed by the given property, with single values
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.groupByMulti.adoc[apoc.map.groupByMulti icon:book[]]

apoc.map.groupByMulti([maps/nodes/relationships],'key') yield value - creates a map of the list keyed by the given property, with list values
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.merge.adoc[apoc.map.merge icon:book[]]

apoc.map.merge(first,second) - merges two maps
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.mergeList.adoc[apoc.map.mergeList icon:book[]]

apoc.map.mergeList([\{maps}]) yield value - merges all maps in the list into one
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.mget.adoc[apoc.map.mget icon:book[]]

apoc.map.mget(map,key,[defaults],[fail=true])  - returns list of values for keys or throws exception if one of the key doesn't exist and no default value given at that position
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.removeKey.adoc[apoc.map.removeKey icon:book[]]

apoc.map.removeKey(map,key,{recursive:true/false}) - remove the key from the map (recursively if recursive is true)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.removeKeys.adoc[apoc.map.removeKeys icon:book[]]

apoc.map.removeKeys(map,[keys],{recursive:true/false}) - remove the keys from the map (recursively if recursive is true)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.setEntry.adoc[apoc.map.setEntry icon:book[]]

apoc.map.setEntry(map,key,value)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.setKey.adoc[apoc.map.setKey icon:book[]]

apoc.map.setKey(map,key,value)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.setLists.adoc[apoc.map.setLists icon:book[]]

apoc.map.setLists(map,[keys],[values])
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.setPairs.adoc[apoc.map.setPairs icon:book[]]

apoc.map.setPairs(map,[[key1,value1],[key2,value2])
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.setValues.adoc[apoc.map.setValues icon:book[]]

apoc.map.setValues(map,[key1,value1,key2,value2])
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.sortedProperties.adoc[apoc.map.sortedProperties icon:book[]]

apoc.map.sortedProperties(map, ignoreCase:true) - returns a list of key/value list pairs, with pairs sorted by keys alphabetically, with optional case sensitivity
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.submap.adoc[apoc.map.submap icon:book[]]

apoc.map.submap(map,keys,[defaults],[fail=true])  - returns submap for keys or throws exception if one of the key doesn't exist and no default value given at that position
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.unflatten.adoc[apoc.map.unflatten icon:book[]]

apoc.map.unflatten(map, delimiter:'.') yield map - unflat from items separated by delimiter string to nested items (reverse of apoc.map.flatten function)
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.updateTree.adoc[apoc.map.updateTree icon:book[]]

apoc.map.updateTree(tree,key,[[value,\{data}]]) returns map - adds the \{data} map on each level of the nested tree, where the key-value pairs match
|label:function[]
|label:apoc-core[]
|xref::overview/apoc.map/apoc.map.values.adoc[apoc.map.values icon:book[]]

apoc.map.values(map, [key1,key2,key3,...],[addNullsForMissing]) returns list of values indicated by the keys
|label:function[]
|label:apoc-core[]
|===

