[[export]]
= Export

[abstract]
--
This chapter describes procedures in the APOC library that can be used to export data from Neo4j.
--

Neo4j supports exporting whole databases via the https://neo4j.com/docs/operations-manual/current/backup/performing/[backup^] and https://neo4j.com/docs/operations-manual/current/tools/dump-load/[dump^] commands.
It doesn't have support for exporting sub graphs or exporting data into standard data formats, which is where the APOC library comes in.

APOC adds support for exporting data into various data formats, including JSON, CSV, GraphML, and Cypher script.

In addition to exporting data in these formats, we can choose to export the whole database, specified nodes and relationships, a virtual graph, or the results of a Cypher query.

For more information on how to use these procedures, see:

* xref::import/export-csv.adoc[]
* xref::import/export-json.adoc[]
* xref::import/export-cypher.adoc[]
* xref::import/graphml-export.adoc[]
* xref::import/gephi.adoc[]

include::csv.adoc[leveloffset=2]

include::json.adoc[leveloffset=2]

include::cypher.adoc[leveloffset=1]

include::graphml.adoc[leveloffset=2]

include::gephi.adoc[leveloffset=2]