////
This file is generated by DocsTest, so don't change it!
////

= apoc.trigger.install
:description: This section contains reference documentation for the apoc.trigger.install procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
CALL apoc.trigger.install(databaseName, name, statement, selector, config) | add a trigger kernelTransaction under a name, in the kernelTransaction you can use $createdNodes, $deletedNodes etc., the selector is {phase:'before/after/rollback/afterAsync'} returns previous and new trigger information. Takes in an optional configuration.

== Signature

[source]
----
apoc.trigger.install(databaseName :: STRING?, name :: STRING?, kernelTransaction :: STRING?, selector :: MAP?, config = {} :: MAP?) :: (name :: STRING?, query :: STRING?, selector :: MAP?, params :: MAP?, installed :: BOOLEAN?, paused :: BOOLEAN?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|databaseName|STRING?|null
|name|STRING?|null
|kernelTransaction|STRING?|null
|selector|MAP?|null
|config|MAP?|{}
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|name|STRING?
|query|STRING?
|selector|MAP?
|params|MAP?
|installed|BOOLEAN?
|paused|BOOLEAN?
|===

== Enable Triggers
include::partial$triggers.adoc[]

xref::background-operations/triggers.adoc[More documentation of apoc.trigger.install,role=more information]

