////
This file is generated by DocsTest, so don't change it!
////

= apoc.trigger
:description: This section contains reference documentation for the apoc.trigger procedures.

[.procedures, opts=header, cols='5a,1a']
|===
| Qualified Name | Type 
|xref::overview/apoc.trigger/apoc.trigger.add.adoc[apoc.trigger.add icon:book[]]

add a trigger kernelTransaction under a name, in the kernelTransaction you can use {createdNodes}, {deletedNodes} etc., the selector is {phase:'before/after/rollback'} returns previous and new trigger information. Takes in an optional configuration.|label:procedure[]

|xref::overview/apoc.trigger/apoc.trigger.list.adoc[apoc.trigger.list icon:book[]]

list all installed triggers|label:procedure[]

|xref::overview/apoc.trigger/apoc.trigger.pause.adoc[apoc.trigger.pause icon:book[]]

CALL apoc.trigger.pause(name) \| it pauses the trigger|label:procedure[]

|xref::overview/apoc.trigger/apoc.trigger.remove.adoc[apoc.trigger.remove icon:book[]]

remove previously added trigger, returns trigger information|label:procedure[]

|xref::overview/apoc.trigger/apoc.trigger.removeAll.adoc[apoc.trigger.removeAll icon:book[]]

removes all previously added trigger, returns trigger information|label:procedure[]

|xref::overview/apoc.trigger/apoc.trigger.resume.adoc[apoc.trigger.resume icon:book[]]

CALL apoc.trigger.resume(name) \| it resumes the paused trigger|label:procedure[]

|xref::overview/apoc.trigger/apoc.trigger.nodesByLabel.adoc[apoc.trigger.nodesByLabel icon:book[]]

function to filter labelEntries by label, to be used within a trigger kernelTransaction with {assignedLabels}, {removedLabels}, {assigned/removedNodeProperties}|label:function[]

|xref::overview/apoc.trigger/apoc.trigger.propertiesByKey.adoc[apoc.trigger.propertiesByKey icon:book[]]

function to filter propertyEntries by property-key, to be used within a trigger kernelTransaction with {assignedNode/RelationshipProperties} and {removedNode/RelationshipProperties}. Returns [{old,new,key,node,relationship}]|label:function[]

|===

