= APOC User Guide {apoc-release-absolute}
:toc: left
:experimental:
:sectid:
:sectlinks:
:toclevels: 2
:img: https://raw.githubusercontent.com/neo4j-contrib/neo4j-apoc-procedures/{branch}/docs/images
//{imagesdir}
:script: https://raw.githubusercontent.com/neo4j-contrib/neo4j-apoc-procedures/{branch}/docs/script
:gh-docs: https://neo4j-contrib.github.io/neo4j-apoc-procedures


[abstract]
--
This is the user guide for Neo4j APOC {docs-version}, authored by the Neo4j Labs Team.
--

The guide covers the following areas:

* <<introduction>> -- An Introduction to the APOC library.
* <<installation>> -- Installation instructions for the library.
* <<usage>> -- A usage example.
* <<help>> -- In-built help in the library.
* <<overview>> -- A list of all APOC procedures and functions.
* <<config>> -- Configuration options used by the library.
//* <<user-defined-functions>> -- An overview of user defined functions available in the library.
* <<import>> -- A detailed guide to procedures that can be used to import data from different formats including JSON, CSV, and XLS.
* <<export>> -- A detailed guide to procedures that can be used to export data to different formats including JSON, CSV, GraphML, and Gephi.
* <<database-integration>> -- A detailed guide to procedures that can be used to integrate with other databases including relational databases, MongoDB, Couchbase, and ElasticSearch.
* <<graph-updates>> -- A detailed guide to procedures that can be used to apply graph updates.
* <<data-structures>> -- A detailed guide to procedures and functions, that can be used to work with data structures.
* <<temporal>>-- A detailed guide to procedures that can be used to format temporal types.
* <<mathematical>> -- A detailed guide to procedures and functions that can be used for mathematical operations.
* <<path-finding>> -- A detailed guide to procedures that can be used for advanced graph querying.
* <<comparing-graphs>> -- A detailed guide to procedures that can be used to compare graphs.
* <<cypher-execution>> -- A detailed guide to procedures that can be used for Cypher scripting.
* <<virtual>> -- A detailed guide to procedures that can be used to create virtual nodes and relationships.
* xref::nlp/index.adoc[] -- A detailed guide to procedures that can be used to add Natural Language Processing functionality to graph applications.
* <<job-management>> -- A detailed guide to procedures that can be used for background job management.
* <<database-introspection>> -- A detailed guide to procedures that can be used to introspect the database.
* <<operational>> -- A detailed guide to operational procedures.
* <<misc>> -- A detailed guide to miscellaneous procedures and functions, including map and collection functions, text functions, and spatial functionality.
* <<indexes>> -- A detailed guide to indexing procedures.
* <<algorithms>> -- A detailed guide to Graph Algorithms.

//include::introduction/index.adoc[]
//
//include::installation/index.adoc[]
//
//include::usage/index.adoc[]
//
//include::help/index.adoc[]
//
//include::overview/index.adoc[]
//
//include::config/index.adoc[]
//
//include::import/index.adoc[]
//
//include::export/index.adoc[]
//
//include::database-integration/index.adoc[]
//
//include::graph-updates/index.adoc[]
//
//include::data-structures/index.adoc[]
//
//include::temporal/index.adoc[]
//
//include::mathematical/index.adoc[]
//
//include::graph-querying/index.adoc[]
//
//include::comparing-graphs/index.adoc[]
//
//include::cypher-execution/index.adoc[]
//
//include::virtual/index.adoc[]
//
//include::nlp/index.adoc[]
//
//include::job-management/index.adoc[]
//
//include::database-introspection/index.adoc[]
//
//include::operational/index.adoc[]
//
//include::misc/index.adoc[]
//
//include::indexes/index.adoc[]
//
//include::algorithms/index.adoc[]

////
[[algorithms]]
[[similarity]]
[[community-detection]]
[[pagerank]]
[[centrality]]
////

////
== Performance Tests

include::big-graph-from-cypher.adoc[leveloffset=1]

include::graphml-tests.adoc[leveloffset=1]

include::jmh.adoc[leveloffset=1]
////

ifdef::backend-html5[]
++++
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
    $('#table-all').DataTable();
} );
</script>
++++
endif::[]