////
This file is generated by DocsTest, so don't change it!
////

= apoc.mongodb.get
:description: This section contains reference documentation for the apoc.mongodb.get procedure.

label:procedure[] label:apoc-full[] label:deprecated[]

[.emphasis]
apoc.mongodb.get(host-or-key,db,collection,query,[compatibleValues=false|true],skip-or-null,limit-or-null,[extractReferences=false|true],[objectIdAsMap=true|false]) yield value - perform a find operation on mongodb collection

== Signature

[source]
----
apoc.mongodb.get(host :: STRING?, db :: STRING?, collection :: STRING?, query :: MAP?, compatibleValues = false :: BOOLEAN?, skip = 0 :: INTEGER?, limit = 0 :: INTEGER?, extractReferences = false :: BOOLEAN?, objectIdAsMap = true :: BOOLEAN?) :: (value :: MAP?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|host|STRING?|null
|db|STRING?|null
|collection|STRING?|null
|query|MAP?|null
|compatibleValues|BOOLEAN?|false
|skip|INTEGER?|0
|limit|INTEGER?|0
|extractReferences|BOOLEAN?|false
|objectIdAsMap|BOOLEAN?|true
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|value|MAP?
|===

== Install Dependencies
include::partial$mongodb-dependencies.adoc[]

[[usage-apoc.mongodb.get]]
== Usage Examples
include::partial$usage/apoc.mongodb.get.adoc[]

xref::database-integration/mongodb.adoc[More documentation of apoc.mongodb.get,role=more information]

