////
This file is generated by DocsTest, so don't change it!
////

= apoc.mongodb.find
:description: This section contains reference documentation for the apoc.mongodb.find procedure.

++++
<div style='display:flex'>
<div class='paragraph type procedure'><p>Procedure</p></div>
<div class='paragraph release full' style='margin-left:10px;'><p>APOC Full</p></div>
</div>
++++

[.emphasis]
apoc.mongodb.find(host-or-key,db,collection,query,projection,sort,[compatibleValues=false|true],skip-or-null,limit-or-null,[extractReferences=false|true],[objectIdAsMap=true|false]) yield value - perform a find,project,sort operation on mongodb collection

== Signature

[source]
----
apoc.mongodb.find(host :: STRING?, db :: STRING?, collection :: STRING?, query :: MAP?, project :: MAP?, sort :: MAP?, compatibleValues = false :: BOOLEAN?, skip = 0 :: INTEGER?, limit = 0 :: INTEGER?, extractReferences = false :: BOOLEAN?, objectIdAsMap = true :: BOOLEAN?) :: (value :: MAP?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|host|STRING?|null
|db|STRING?|null
|collection|STRING?|null
|query|MAP?|null
|project|MAP?|null
|sort|MAP?|null
|compatibleValues|BOOLEAN?|false
|skip|INTEGER?|0
|limit|INTEGER?|0
|extractReferences|BOOLEAN?|false
|objectIdAsMap|BOOLEAN?|true
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|value|MAP?
|===

xref::database-integration/mongodb.adoc[More documentation of apoc.mongodb.find,role=more information]

