////
This file is generated by DocsTest, so don't change it!
////

= apoc.mongodb
:description: This section contains reference documentation for the apoc.mongodb procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.mongodb/apoc.mongodb.count.adoc[apoc.mongodb.count icon:book[]]

apoc.mongodb.count(host-or-key,db,collection,query) yield value - perform a find operation on mongodb collection
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.mongodb/apoc.mongodb.delete.adoc[apoc.mongodb.delete icon:book[]]

apoc.mongodb.delete(host-or-key,db,collection,query) - delete the given documents from the mongodb collection and returns the number of affected documents
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.mongodb/apoc.mongodb.find.adoc[apoc.mongodb.find icon:book[]]

apoc.mongodb.find(host-or-key,db,collection,query,projection,sort,[compatibleValues=false\|true],skip-or-null,limit-or-null,[extractReferences=false\|true],[objectIdAsMap=true\|false]) yield value - perform a find,project,sort operation on mongodb collection
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.mongodb/apoc.mongodb.first.adoc[apoc.mongodb.first icon:book[]]

apoc.mongodb.first(host-or-key,db,collection,query,[compatibleValues=false\|true],[extractReferences=false\|true],[objectIdAsMap=true\|false]) yield value - perform a first operation on mongodb collection
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.mongodb/apoc.mongodb.get.adoc[apoc.mongodb.get icon:book[]]

apoc.mongodb.get(host-or-key,db,collection,query,[compatibleValues=false\|true],skip-or-null,limit-or-null,[extractReferences=false\|true],[objectIdAsMap=true\|false]) yield value - perform a find operation on mongodb collection
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.mongodb/apoc.mongodb.get.byObjectId.adoc[apoc.mongodb.get.byObjectId icon:book[]]

apoc.mongodb.get.byObjectId(hostOrKey, db, collection, objectIdValue, config(default:{})) - get the document by Object id value
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.mongodb/apoc.mongodb.insert.adoc[apoc.mongodb.insert icon:book[]]

apoc.mongodb.insert(host-or-key,db,collection,documents) - inserts the given documents into the mongodb collection
|label:procedure[]
|label:apoc-full[]
|xref::overview/apoc.mongodb/apoc.mongodb.update.adoc[apoc.mongodb.update icon:book[]]

apoc.mongodb.update(host-or-key,db,collection,query,update) - updates the given documents from the mongodb collection and returns the number of affected documents
|label:procedure[]
|label:apoc-full[]
|===

