////
This file is generated by DocsTest, so don't change it!
////

= apoc.temporal
:description: This section contains reference documentation for the apoc.temporal procedures.

[abstract]
--
{description}
--

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.temporal/apoc.temporal.format.adoc[apoc.temporal.format icon:book[]]

apoc.temporal.format(input, format) \| Format a temporal value|[role=type function]
function|[role=release core]
core
|xref::overview/apoc.temporal/apoc.temporal.formatDuration.adoc[apoc.temporal.formatDuration icon:book[]]

apoc.temporal.formatDuration(input, format) \| Format a Duration|[role=type function]
function|[role=release core]
core
|xref::overview/apoc.temporal/apoc.temporal.toZonedTemporal.adoc[apoc.temporal.toZonedTemporal icon:book[]]

apoc.temporal.toZonedTemporal('2012-12-23 23:59:59','yyyy-MM-dd HH:mm:ss', 'UTC-hour-offset') parse date string using the specified format to specified timezone|[role=type function]
function|[role=release core]
core
|===

