////
This file is generated by DocsTest, so don't change it!
////

= apoc.metrics.storage
:description: This section contains reference documentation for the apoc.metrics.storage procedure.

label:procedure[] label:apoc-full[]

[.emphasis]
apoc.metrics.storage(directorySetting) - retrieve storage metrics about the devices Neo4j uses for data storage. directorySetting may be any valid neo4j directory setting name, such as 'dbms.directories.data'.  If null is provided as a directorySetting, you will get back all available directory settings.  For a list of available directory settings, see the Neo4j operations manual reference on configuration settings.   Directory settings are **not** paths, they are a neo4j.conf setting key name

== Signature

[source]
----
apoc.metrics.storage(directorySetting :: STRING?) :: (setting :: STRING?, freeSpaceBytes :: INTEGER?, totalSpaceBytes :: INTEGER?, usableSpaceBytes :: INTEGER?, percentFree :: FLOAT?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|directorySetting|STRING?|null
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|setting|STRING?
|freeSpaceBytes|INTEGER?
|totalSpaceBytes|INTEGER?
|usableSpaceBytes|INTEGER?
|percentFree|FLOAT?
|===

